apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dX5mxzc16VT6I4yLvodCrWezEEYpAP4DOWT2N3xl7LecmDiA0R4H4g==,iv:IbFRQ2h0XQOgk6qnatHS+t+/aD1ZIpRVvwz9WU2REBc=,tag:oJrSX9+kd0EJj7rpfczWTw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z0Vra2NZV2t4b0N1ZWJM
            VjBkd3ZoU1oyREtFbmV6b3dyWmg2OXFKanlZCjAybFRxMHE5a0tLRzRwcE41TUNT
            TTNLN0JyTmFlVW11RlUvVnpKVDBHcDAKLS0tIDNER1FUekt2K0dSNlNDTTJvQjN5
            NWhvNXFWMFY0UzVTbitCREJIMFJjem8K3tzKQmcka28bfTg/kcRNra1XMNd5Xqk/
            KQoxktLGkStVvJLVngMSv7Rm6ZDtvD8k3YL25BFWQrP/fOCqa3kfcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:37:36Z"
    mac: ENC[AES256_GCM,data:8lDRfkfIWtb7OoT90193Fs/+wMknO4xNOm8Z/cZKhE09xlHJGL6RF7nqsh8hhCaaDOkYUzUMO6XcOle2LV41gfJyZfRLDQ2/yGAGsUVHAzm8AC7RL/2HGBHgV1WXo6O7YGrrwVu8Jle1wFu/N+edgrfMKmIN0SpknT8cksNLhpk=,iv:nCNW5mbfIK/YCtn1u9lqFhcjlJtpYJbVtC21wDs6dO4=,tag:kJtjal2c6mWCPA7646xkPA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
