apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ly6BWOdTkTjgrnDLmFnV1cKjWUyhws67ZGfb39bKR7YJBvODTrJLpg==,iv:w6W7kVmh1tF6hDaUSqaTfaOWhzsRkSe48YmM+m+jdqI=,tag:5jD8lIIUv/ERvYptRW14Sw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoLzU3b25hR1RKNFNKVjRH
            aS8yWU91U3RWSWt0aEJnVE9wRHR2dkRaL2prCmlZMXhyRVE0L0FkTWRUSEdmTUpM
            bW1CZ2FPam0rSUNOUFFFcytYZEM3ZXcKLS0tIFdwcmxnMmFVZ01ZK2hKOEpnY0JD
            cjlIOEViVHorZXhJNHJXRG1WTjB1amMKENgmA5p9CwCavWr37/IdkITkayvEWTaF
            bClycATd2eKB3vegZq91sj78AhwkMmRRCuRSfTwwAkLkpD5o+AHlRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:28:21Z"
    mac: ENC[AES256_GCM,data:3rEzogxjEQ2WVwFjtbtOwKczDnclII5kVlYbuz8ovZp0Lyq9NbKACql6ihFCJWJUvHSZaWfrkuVdbuUK9+s5mFX3DCj1EVytJg61DTMCq6KaDTNI0VGNtJ+sQQGYnYC6fnugR+rivwX7lxGcLl/vUFdkvey1JaJPfCvq2+/ZDSo=,iv:L3PKXi3exVv1TfkTAG4yKTRvzyFmNh3FF4Lllln4yGM=,tag:Lbc0s5E8xA0So30tLYxCwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
