apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:p1E0XqhLHiDU5PQx4IVA5lsGghwgpdjrMBTzZt7Vu6pe6htjVEYStA==,iv:5WdtuhcizkhQ7QhtB0DytmF2/vKkKIm7bbYmMRQkCjc=,tag:corrp2susbcHpXAzIJ342w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4djRuc0ZndVpOMlVpRGNE
            OHNPOUZzdUsxeVppV1pubEhIclRRaDNHVURzCkhHQWpkNVFvSHA2ZlFYci9MNFdQ
            alJmcXFNR0lmMjRMcHRFZUMvV1VZZFEKLS0tIFI0Q2NkTXErSnhZcFBBc3E0eWNI
            S2JDMjFKc0ZpeFBwd1VXb0VVVTFuN0UK+u2bnicO+X3/Nnr6nYU4Qc9AO4Zo9bA+
            hZckdQA+Szq0X8JANkiLoGjvw5tLZzn3r/u2BOiQHtax6Fci64HGrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T12:58:56Z"
    mac: ENC[AES256_GCM,data:W+j+mIE/wm0+iFSTaLSkQkjx+/a8+YNLXhI8C9Xhk5zFlun5t3cn+IS+ZO6nuk/vssRLOfFGguwQ/VFRpNQW2pA9Rpf9M8SCzGtJ+g9tKlzsh4WuF95RpaOQ3/Z6ajeQ3hOJoAPXpFT+GanuVrUWYVTsTxTqYNwtlwFdx60uryQ=,iv:p36tjkP5yPcwny4dt8VMp2Rv4DqQgbhbE8LRiwabOfo=,tag:RLi2DsbWsz8IBKminZWTBg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
