apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3p6R2S2FIQyr7VrB1YuUVBgB/lJ4M1CkFe9lv7reous6LFvnAC4Nbg==,iv:cZCrSdIQZMc3/TYywST6ojyS14hGlAa3lINXDtTaQIQ=,tag:GB+FFZci7QnzymEyZmx9Rw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMDl5MThVMlAzZENRRElU
            R3RUQzFReXpGV2xzNy9aL0ZpTEFZNzFkelNJCmhVWFZ5N3QzaFRZWS9IajhDUlFD
            SE9YdHdzbmRyeFZYenc3c2ZvMkpRTU0KLS0tIDVNMHZ0REhqckhjb2tFdllBZ0JM
            Sm1vUThOYnBUemd3c1NUUFlMajlPUTAKCBZYv8c4ykg+EXzdB9NXuju+H17ZtTVX
            0wnbvf4da+4qlKUJVA/p77z5mhH1ApJuXehKNiciC5trl/tBTxXVvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T16:17:44Z"
    mac: ENC[AES256_GCM,data:raHD8CZ0soh7bt5hu1SJ1FOZVvz/bZZRfWguUKSNR9QVt8YLMd6OukmlYjVehXuh1Fw9mO2BCOAxy97hUvVgLQcjQ3jBYI+t980iPK66ff5hW3hcqa251y7FxC8+Y1ZqE70IK67tcI+9ST+iUwI1qxDh4KAXEVHcg17GUzvMJiY=,iv:C6HNqf7FES4IuPyyhLnu7J9z5/4U/40z05y0z7IFDYg=,tag:KTLQEZXPaXnfhAaGGFHFNg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
