apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bV5RA0Ng+AesCPHH75bJO1+gQjfMB79PKjCitoAvVE+0q9WqI0e5Nw==,iv:a+Rw9cruSV2bqjmorGd93SNAoKBSTCmq79F/DQgZtpM=,tag:7z1x5m55zm3BLY3bOKRGTA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QzdKMWEwMWgyckpTOUVQ
            Yk5BdDNoZU5pVzQ1d1VlTEI2UUhib0pGQ0dNCi8xbWV5SVBXS3pOYVJOVnlldXdv
            dTYzQUE1bzZGeUVEdXhVUXRVQXIyazAKLS0tIENVR0JtU0pyL0JCWmNFdHB6T2hI
            SytwaTFrSklDanUyb0VLMlBDN0tGbU0Kq+Bx0pIY0CeGbjjonfD1aUxPDSB8OMJS
            3WRYT5U8ausJfcCZyYWhpSD2rc7+/Tu5ohP0dz61NT20p1PIDygnqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:32:47Z"
    mac: ENC[AES256_GCM,data:U9wXmvW3HHojW5flWzgU894n0ox+Tsoxgizuqf+TysMxeeSAQmlJ98TeVd89pF0Zg6XnPWNda5YpdqsiaEOJHofaPX+acI4JkE+MNbt7mgJu994IhEeCWXMkOa3OV2ImUzlLWnydal/28i+IQm75gJAXtY3N8rhBizQbIXrxaUI=,iv:zelhNrgapJks3NuxbRhr5P2um/mJJNkxFiG8CZZTnKQ=,tag:ecnWfJBTeofoDpYHh87bgQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
