apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:pK1m1vL+eDUt5nCGY55Oxadr/hj5ldONkHvRoOkTKkIAFfoRygFyEQ==,iv:fSWXySG+vJWF/9mt98Ll658g38LsLzl+Y71+Bud/NA8=,tag:eL8pVxpmYNJ3M7WE+G+v5Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWmIzd090SVBqbjFqcFk1
            QWNRYlpWc1pmN2VFRnVMRXFmLzhQeTh3aFNvCnVvdWdRRFFCVytlSnlsRGRseSt4
            cWE3NXR6MWhaR3BUTlBoVnJkMkp3THMKLS0tIEh6TlJ5dFJJTk5GUFBaeE9rTDFS
            Mll4RlJCL2xCVUxaaFlZM1JXNWlVU0EKfKO16VhDeFA09PYiTW4h/U+kL0qEWBdY
            IbEv/lFj8bkpkp/o9FG7pxr6fFZQKb/mBPHuaRoyeswZfyzu8R6REQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:43:10Z"
    mac: ENC[AES256_GCM,data:chvKHAWvudvMIcYjL0sJKawI2frCRsW3vExd6V9QLWXKBUE+vJ5PbWQnc3kGVb7+U8CIVDLmpOdmOEI3nlXlWJN3VrnhEZqfk1pAilOPjZrLp4tZZVWlEm4/sW0Hjm5Fjm86HVZuNnTAJ1nyzyxnDlctr8Ngb6eio5Qza0+cw80=,iv:23cfK97R1GENq3p7KSIgX8ySQT4KXRvht+AAyk6lEQU=,tag:eKmW5bh3ijL9DpgF0a+6OQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
