apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FP2aSayQAHIgHZP6lR0xu2o7jdZSx6OHckPlJLpMStz0uKepJcwCeA==,iv:zMewco4eqpW/k5/Js4+ZrWG/3/eD9wkTrRBX98qyCe4=,tag:+xtFJxa+5xIMmXdiMvRyAg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTDJsRzBuQ0JiaU85cnJn
            d1hjM2ZvRytVVlM3WWdNVU1zNm83V01LeUJBCnFRcWNUWHBlOVJveTB5THMwNXpm
            MUgyQUZFcllVVzdHMW94RGowOFlDdE0KLS0tIFFOMHJqM2hQSWZxeU9BQkxhS1Zr
            blhiQjJ6WndNQ1N4Yk8wMzFEVitmMEUK+NS5ccdGaqS37QjgA7PlZVBTU4hzDn9y
            Qk431IGjyU13iUKYD2kAEs7AFg41X0RrSHVRUqswzW4nUYXW5pCR8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:17:23Z"
    mac: ENC[AES256_GCM,data:f7A/5UjSYjY6IKbzb5aFOS5pVIJqOY1+HCHP0VJowhYZhQA+/YYavFjlpU/i+FZaEFluW0TD2leEeYKjS0GZ7zIG10ytNb/4j4kT1vWLGSWv0KtPlLR/vyQ/BNZZRiSD+Z6LruFBLsdU4jddz+ZiKZ9Zc2HY6075SLUYmWskxM0=,iv:WDrVAOfExY6+OGjmb90r9uoL5ccPSL3e0HqgKYtIflw=,tag:2djvnQJPasQ0YHrBLq3Y8Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
