apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:oS/eU4gkPzm96RMAuO+3qT33sd0cmC7xDrZSdMQajCZsWL0LKvAF1A==,iv:Kw2jgNzKAUANDeOHlsFkbDfOD/FXeNTfDbV31HdAo44=,tag:sHOGbpdZ3DG+TsS0J9kRYA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMU9PWEtSdEhMSGpMQW1K
            ZEJ0ZG96V3d0alRUZXBUWU5WcGxnamp4alFrClIzdnV5RTBkN1lhdW13L2dZZkNm
            blNzQ2ZxcTYvR0wzS3p2eUFoeXVFRlEKLS0tIEhtQmdLcG9RVE1IbVlLcVNWSHNk
            VHptclhENHJVS29rQ1FkdXRWVndyNEEKJlFkSnz+KFnlhuxaT5l9S75YrxeulThm
            VHMQLR2ujL9+JmXkp67AJCesWUEnjFGJXrPWjuKLKMqGfv90QVN0FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:22:59Z"
    mac: ENC[AES256_GCM,data:SMey/juYNvsQV8DuWNFvX2kw6fdOkwcckrsZBfoz3VpLmS3wTkU2WAf4OcJEEjeVHORtwTs435YA2SgtNCVK64Q1IWRMUXm0OBDVJNrLmAc6thSWeb1x90NkZMDwrKQjU+6a8KJZETkMie2Pp5fDBcaLX9XIdEIRmOLO7Dwv+3M=,iv:KMi7aRM6ku7pwOZTVCbM+yIrrYpqBCKUkh4uCxaeI4A=,tag:31ejD10PGLyAGjmNAmwP1Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
