apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+kWxqCLEL9fVozCEbdJHueWQ16pj6MCkNyJT/deoO+r/PPVFuLnTwg==,iv:vJRr4H07sT2PzbUCPmVd7sIPdXBswjLyHirfhxuDA+s=,tag:QNovuFNFWmX1qUgDxmTQKw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b0hza1BnL0UzZllJazd4
            WWpiUGdqTWJiTXl4UFJ3MWZnQndkTTJveGp3ClBVdFkrQzlrcXhUdzdhMkFYNjYx
            NFI3Vng0OHBRbHY2VEdNS1lLYzJqT2cKLS0tIEJvNUNPUy9WVWZPLzExNVdzVlhp
            MXdxb2JvRERXb0xDdkwyOUh6bHpJc0kKUxJbST/uQaqiaS39JxcnAzPrm3j807Te
            5QLXwguKLbsqobvDtur4I9Jpj6uvvOftk5IyHeWb9oDJPuhHfVli4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:33:51Z"
    mac: ENC[AES256_GCM,data:6Cly0cdQ8FI243csXdF7243v45mNGgqTzbhDLs0rF63EhjAt/hqWtO0aIYN8E1En62o2rtPTEZrhP4TPB365neoPiBnIYE8qvjyRmCRTp1bakPEDzHWlZixJ037wJaRavBING2MRDg4QyafjyS9gzVTgvOkB9a1VBgP/zyiAozI=,iv:SiMXRXx6VQFtZ25FJ11KwKnJwvdC055js89jdArLkBs=,tag:7RLZta7l7g7xtW8baaVRXw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
