apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SdsfIu7wmgs5stsadReIR2z8LAuMiY61Vjr/+hFnkXZBeRyeoYaOoA==,iv:Vb63bwuzjt8h1qf+qZ5K8/28WBqPK9jM2qjMFsdY7+g=,tag:XvVY74ZG1k8YqY1PPNEGwQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZUZodk9jelNKVVo4OGww
            dldsbzdlcllKTHZpRFIvRDNDelc0V0NyUGtFCk0vZVh4ZFd5Q1o0cUkwdW9iWkFK
            RUMrMlZiU3d0MHlmY0lwUDVUQ2Mrd2sKLS0tIEgxUGswcXZITHcyWnkrQWl2TFE3
            alpDMG9xVVJmaVlmUUFoVHhvMDlMZjAKPjZb75OErZaYuSh/AhiOyEnPZGbJTPVH
            XmSSpbxAsanpQqQiNjy2Yoeq2kAAaK2kYW2qjDNKnqDbwVnBQI1F9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:44:57Z"
    mac: ENC[AES256_GCM,data:Ax51LnuNQh1swhRuzkwPl/j6FeCb0ejWF/qq/Iz/6vmwhxwChJRRowmhhUHYnT3lTu1OJteqZ0YWmT7rNKOdg85BfDA8wvptL7Rc+RvqKI/3CDqLFtRqvf3UX0XIceEhP3bQNUg3U8KrZ9k6XCFvDb46UgnkNsHC2R/1APE4hYA=,iv:bjVlJU/8uqRxcfFfR46ar5B90pV2rHQ9M5TRN8hcrsQ=,tag:Bs2Eo3vAYl7EL1MNiWDNHw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
