apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:pqlqDOJ9vYhlSuzMokQ4cwaW7d4QsOWZe6rrzciVJV6CufvWKXMRvg==,iv:ItOeKkem8+2X4or74wbu6OCsDuaWORLqJ81NJudwkUA=,tag:OW7kGzdcA/vF7C+J0raTNg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMEIxWWUvVnZ1RVFFU0Jm
            UVVRM3VmZkdsaTBoREllb1B2d1RuZ0dNbTA0CkRwemsrSWIvNTJBUkQweS9RRzVv
            czhyRzYxbDNoS2ZCcDRPeHorcWo1MUkKLS0tIGJOZGdiOXYvU3l6K2E0YTJGRUFJ
            RGJYc2xYOHJMbm4yM3dva25OT0FhN2sK5ktJgOpmxN8XpF0yMKwXvXykQ99svVVE
            0xEJBmDAGN7CP5/gtbx1V9JOhNutnJVgG0NGsbpBd4GYpr3JmstDCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:30:07Z"
    mac: ENC[AES256_GCM,data:1cAN7MSNceHcSaRdbfDBifEGxh72Tg/ua6Yh0ygNPZ4cyEca1J52z/SM7C7+wkny6doB/URLG1o1av1UIXPMKrGBrgLX28GWfVRGdVIsLFSchNKbfoaDiOnmnsqyLHIuCb1li5CDO9MOkLr3zwb2szKATAQl3w7pn0tk2Z7/Kt4=,iv:rqBxcSxMKjVqVTd1rRz93aX93d9oBNosTxS4yOT6Iuk=,tag:H9lzPF0eI+w91tC95Q7NYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
