apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eGXm+OfJcapSbjrNCIoPlY5ZkF+jps/5mODZvkpLsB2CVGIoaQZD3w==,iv:ZzO166x8i5xM0O5Oie59nuFDk45IGBeojPSYXx8Ik8E=,tag:s1GZmciWzv8GPYqIspt16g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUWpWZkNzdlByTkpBTlNW
            bFRGdXh0QjhJdXZMVG9Gd0VKZVAvK1VJaTBvCnhLazQ2Y1FIRFNnU2dHTjRCTUhU
            UW83TndELzkzUWR1dTFNMVdEVzcrV28KLS0tIE82RU1jbWhscVpydElQY0U3LzM4
            Zm9EVi81eEVkemcwOHVzMi81dnI0a3cKKY9Fa6iYjy27nF2FyQTMchPxD09jZKrZ
            b3ton/QI/IPY0JJwU4Hfnk492IZKGt9A9Gu1e8qZHJRpWhaxjgp21w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T05:22:34Z"
    mac: ENC[AES256_GCM,data:ai9yeEvICvz9JBbqDoyL+Kfs4tiKcklTqs9BsmPyta0tYWVuKMgNwY9ZOpaFd7lNWUIxW4vR15QhRUZ4LQuDzeFUsuZCFsfiDyTXypURg+4DM2yIJb0K0whhaA60kLF6atg36o0ddM/dCi+7S1nqRo57zjfm60JByjg23diMBxQ=,iv:56H2OkZH413zN8XyUoK9v05RVkjBUnitZY/7VRQKidU=,tag:NUVKYVg9lZrf3ECrHtcZfg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
