apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Yr6+349BL3IcC9ODl4GPUoCQWtCzr+mtRNxNi5FELnbdWMw0AW11IQ==,iv:TtRJTEqSkpBsHzpVjK9o/JH3TPFG7lNxqnuFaQNR3ys=,tag:YnFF6s/ru3StMrJfJTBwUA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eU4vYlF0YXdnQjZqWmMr
            RitxNmlsWEV2RStaNUdxTHJMMVRneGJKaDNNCnpLRjN5Zndkd2tiWlJOekxnT3FR
            MEpGNVlLbkF5ZGpJNi9BbUxOQk5zck0KLS0tIGtyZ2VrNGlHUW5uYW1DZlFmaDdL
            SnFGTHZnRlBvUkJpWVpSS0JMNnNDYTAKpE8jFjr/QJP+WjjRgB7vjXkzEVPNh9ij
            Cmxl1/VzXjgHmG2vLf4pzqNQu9/ngNAMnY9uL0HblhhuL0srttH8TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:31:28Z"
    mac: ENC[AES256_GCM,data:tvuSzXCN79hdbVIgvw7Bx+WcwZNYJetkpSjYyVkKeaeCPGSinz7qkINYPrBfK/f4FRK+ZGxWPv9iGSDwQesoLC4ptL1LpBCtS9KUD59pWbQDDRxyP1eZjb6oN3IcPhU/qpsWNxv9kpS4DOLilUSlekHlBI5+K5jKjVfJEVjXxQI=,iv:iZSKHHV3NOJsrjHkPH4uwIgZIowVeX0VbGi+fHmG++s=,tag:vRo4GOQDeXd0jeZ/x1L/Eg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
