apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AqY49SaC5JbZCQQ0gHxOUWt8nO0hNlehwO+t67i98EVcnGfKoDWUJQ==,iv:GkwS/zlNCP6RHeX0P/Fsd3w3lfzJEDY5S6uTSPBzd38=,tag:MmJyfTEJ3UBOP1HQsbI2pg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU1ZNZEZmRDFTcGlTK2tU
            bGNUVHEyOVNqNGZtUW1HU1JGZ0JBcXByRHg4ClBadkZtTytUTCtOUktUV3hMMTBD
            aStQMnc1UmlIT2oyL1RhNVVDNnBKSFkKLS0tIGRuODN1cjYwZnlFOWJBTGJtQVZN
            Ris0RG9Hc29FZXcwRzRrVUV5a25PSGcKwgxRO33gWv90Wg+SzxWNdKXLfpSIEG/c
            t4gE/N7X11ojvOlP7YEQCP6nV7o4XUol+phuoOo8iTfncs8Hlum1lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:07:11Z"
    mac: ENC[AES256_GCM,data:nXZw4Fy+2HHAZ4X9phEDrk15fPUWolu5K6Xjt9P8VauinM4e625m9bfD9Lwn0m6GPAz+iH/eK9QnvY132Jn6q0As89WcMAZD6iIccVapPx9tSRpWu/Hc6rtrsq7+MQADvfG+wwn0/jGYYnDNtYGXX/TmFtvzo9WG40EqQ0rveXQ=,iv:p53fPBmqYaCjC46Aced2oj7L2ROn5Vk4UDjEN8OmLzY=,tag:uKZjJunToFWwrWgjdCHpQQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
