apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Y0/lWI7eaUHxkUA/Gb3VaIMHyCQKZLNPAjwgmLjgv3TdZBuXcVhE+w==,iv:8+EkcfaQymfHy1nvPVvKrqb4Zjzb1F8n6jvrXET7Egk=,tag:3SeRoI2IlIz8xM7+6Bmy/w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d1lYVUM5UUpNUWM4UnQ3
            clF5LzFLUTVqWEp2N2Y0NUMrWFZ0WkhwVDM0ClljZUtPMWZTRVJWTDlPYmhaK203
            OHg3d3B2bUVTbzNRMjF0Y24xaVRWSlkKLS0tIHJRS1dXSEFITnBtbGdxOVg4UktZ
            dVN3cVh5R3k5UTRlM1RoUjVINzlHQVEKRJIIfhCwdjhfrcK07L05szOOWg5yUiJS
            i28hK7UEBFsHkIT9fuFoPS6Q77fB2nwSmLzkHsN1m4p/0phZcflK+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T23:56:07Z"
    mac: ENC[AES256_GCM,data:7pQIS1KNUBt5pRFcSW+HhYQFPDoIKFdS/5nBFYKydBuXdYXSTVfUeD/eRpdL0Dh6Vx7if5g0e5mjeWN6c1iwU1yfHcIfFHGusHRmSXblNF4+1fQkB4rjrx89Sxer3Py6dG9RtpxSBgiQ/Q2IoTFy11vapnfgDoZruMtHvlfB23I=,iv:FS5kA8wp3TJYFH72qe5RRd/0wxyK4bssbJbNdfr7nXs=,tag:hSa8KNLLub6Nr3dsms4L3A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
