apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5GuxCQGMSC+ifuQO1PpM4KuPyAQtXj0CojWCXCv36nv0oDS1lT7xiQ==,iv:iaItVl//WBxz7ck0iRxrsnx1c7eckbD7Dj8Dt+WT0Do=,tag:Mxn/jLd1HyMIpIAgV+NSzw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYkkxRDM0QzdTYVk5T1ha
            RE5ZRklNZXBabHpvOFd5clQvOVJYMS9IekNRCkRZUEFIdHhqR2kycEFXcERHSzh5
            ZDVkb1p0QVo5MVVsYVVHWmNSamFNc1kKLS0tIGRHbE9TS3FWQjJ3VHRlaHdrYnVy
            M3FzQjgreWo0bksrMy81REZmTzczUFEKxiuaImeqaWqXYC0lzE0PL9sQLBa0TNPU
            YgZi96pfnOEk2kUIRVqXiNHnbO0ErskXi2EG+rhuS1TuEdp7lKduGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:33:51Z"
    mac: ENC[AES256_GCM,data:SMN212z0HuvL/M4dQrhNyVHf9cvi1nRKH/va8fKujIhFBZMjIGx/h16E3GcBDRpg1AZzbXwu69TtvgQ+zoiMzihFiRen8sNMyCorzGCkyvVtTnkYhVwwPDbrIeshp40pMPPZlxvjCknAJwN4v2iKm2Q3zqFZpMnVf8oLZDz/S+c=,iv:0rI2XrbxNq4cl+MWKVQPfUohOIxv+DUcSF1u3iy/toY=,tag:tSx2KdvROZ/9jBWQ0caJlA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
