apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:A0hQYqWB7MhX/MdpKHWfw4oNH1Ekj5UBxb4bZ8JrffR0dZbOVa1SMw==,iv:SH4puq2uV5MEAkvOs2VkNiRIB4X0LO62DiptVMmkJt0=,tag:6ZlrGn+N6V3t2U8wcUT1LQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RW1TZnhDSWJjN0cvdFc0
            V1NyV210WUFVSUVBSXNMVlRoS0ZFamo0UlEwCnZvemJEWFJqZmpReE9LczVBWFYw
            eXM3MXNsQnJweVVwS3dMcFU4QVcxNUUKLS0tIEl0ZmlKdDRQL3JXOC91QnlHa25Y
            QzlGYldCcThKNUR1SWNRMjlWMjlRaVUKKZ046ItW2fjW4cg7CrI0ZE9AvoSBBD7C
            pO7qpWVbx5QJxNErItosAxpwkTDcOnPAJUcuzj/drzF48yO4CzvATg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:51:42Z"
    mac: ENC[AES256_GCM,data:n44PDPFZxJiReMoMfEVEgho3pOcq1Qb+8RuyWXdBLtOE8xDhCFY6ehYTEDkpw5NrHJutGSNGelOZW6Qq/8H2wtA8w4n6edmXQngLiGY2Dpyckjos/NdqT7cSX9vFS77Bo+4AcrR1hbQ8UgEzMVeS5TXZD/zxMV9SJ3IO0PS6+eA=,iv:AwCjAqnmB89aO/TEXNLMq2WSMbFY3tLYP3rILUkAomg=,tag:qtMaMX3VnPBv1nk8Rg8BKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
