apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4+I3/GC8wDGgoYA0jOs5oPDcJHj8bnkoJis4Qrx4ohOzxTUYNmijYQ==,iv:Y6DJenibPCgu+DECXQLDDF5W0tsDoTeWM2sf1eUI4BQ=,tag:0msOEz+Hh/pHHFA23vXvPw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMHQ3eWZTOXJwcmpWNlZ1
            RFpnMWE2Rk9vc3F3enlOUGk4TTNVaWRjWDFJCmdSM0wweDhkcEY5Uytib2NJL1NJ
            bGpTN0pUMVd4dTFGQWREU1UyeFl1UUEKLS0tIHAyUUpuMGRxNHpkelhkMjhqbVlZ
            S0dtYWRyRTA4WUlpaUZvdnNaZXlNeG8K1ebjnJgTqCLjdA2SBFTIIsR1iKnD+ZN0
            VaETfXJiZsriiXvFHVO1yrHDxaL09BSYFccvtN6s9SguLuZb0SduHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:23:57Z"
    mac: ENC[AES256_GCM,data:9aLsmWCzLpVaGto56Ao9DnV6FCwTFQTqG9M8yXI+48oUtXn1tdFyfbQbyUSw0geQsVDlg7O6Qzhmrnll+/MNLBH+iA8PXlERQlhKnnPz2ioujOdrC6tX/BviruOlqLH0eVzkFdamSOC4vKhP9LKOT3geeFwMJ1ewtHFLEruL0/g=,iv:VqaFZcCv8ukjqo2LzRm1beqFFruL5oCqJJUNJGvPyrk=,tag:0E9DV0rKGa03zLVJbfhNmw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
