apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/lcSBG0yFFjXwyf6YBJGYyRL986R5X5V+haZP/raPKJlH8RC6UMsag==,iv:IFLGllvYOQNJ8YB0OItDiyiFBE/KQY+aLDaoznwiFQU=,tag:/3tiHAgrAbtEuS+Ym+zKMQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ1g3dnpNSSt3NS9kUEpY
            MVVLT3llSURoRUEzUUlkeGN5K2c3Z0kyV1g4Cm9ab2M5WTZxRWRXT3RMMDIzc2dC
            bEhKYTVWd0t0TlZJdXZOOVphSDNNa1kKLS0tIGd0ZHU2cmdvZGlCSjE0RzdDbHdz
            YzRnMWZHcU1WUGZTVnpOSEFSZFd2YTgKYcssBuqdgMqmpSXpiruD9xRCLt2njtPm
            csIRiBejN55/y7JOMY8ZPJbd4Nms1S0Z70iPbrQih9FfdXqBM+KFeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T00:03:03Z"
    mac: ENC[AES256_GCM,data:ogWvlGYQzCWrqBhgxaWzp+uHXXVNJt5SI9xoiSgkjtgT8T+LcCzLp88pYRAg2Yl/VBlVJCuwnxEGLJw9ZbQqiqj1Zrudt9mUsng3UzhjVMrCwl0Qvv+kgzcQoyHWQgsfvfS2YPFOoxVVsvfOJTU0ibe4+pQF/CxVEBLAykcfz70=,iv:MhNyshTKzqXY+6JazrejRaS4zrEamjEYxSM8X8bVGO8=,tag:D2qEyAuNKWQgv6J3JPftHw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
