apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ys0ChoWl7o5qyI9JLHJHqViwBuVGCN1JWmLai9yPnvqcOwaaTqC67g==,iv:5SIcY2IM79g7470JCziB+K1uIUdYR5CIdGSUmBOFAYQ=,tag:vH1fUo5URtdZLZiblxy7/Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ2p2V0xVWGxOSmR5K2ti
            ZWlseGJycFVHTUVWeHRPdDVQUFVodjNkaFRRCnp1T0sxUXd4NGtWR3BiSkZEZytK
            TUtJL09jUXZzeU5QQmFoUGFZamJ3c2sKLS0tIDRUWmhDclhEVWNOS0tQUmI3OTdh
            TW9tWHU4bTNBbHNvNE1HNytGdDU5UEEKsZJKNyqA+ItYngYFxDzKWWHfVanZZ6OD
            Hq4MXYOLCQx/XfKdLcWtHEYlXDYhilhfvIPkR8S8QGI0DDmvdxjC/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:15:22Z"
    mac: ENC[AES256_GCM,data:alwqixneUf4850Ad2yKMekqXTKFrbw706d6bhfFxP8ulHAJBfVG/RwMuBCmrqrl0UD7Ko9w67MBWaT44JFfP2hEONOpa+d4R8y4z+746OnIptrrKI5v9RfzXuyY/yfFiyjAw0Y0IR7xoYALbfeLk3EVY0aSMw1P5dVmLQ02tQ3c=,iv:e5v6T1aIyIfMRPGXxtTcN9izxXMgNHrr0aUC6LmbFF4=,tag:E8Iqp3o1RjzM1w6aF8JyCA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
