apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:f/h9dmTXl1aP6IWSpdtrsddLth65aJ1pceA5sVedTai2U5aan7Xq7w==,iv:wOktJ0oKdoDwKD0bOLRqj+g5INBwBcHwbwVEyZUPLv0=,tag:ySR0tnVdj0F5V1sQsaY9ug==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMzVxRHFoWm45YmJqSW9h
            OTRzNmxvUm1CQUlVdW9IWFJYall5RlpkaWp3CkJ6VU9LeDduK3R5S2dzeWpZa2Uv
            N0t0TDM4ZXM1d1Uwb1dlNjFGWlkzbUEKLS0tIGlPelRKdGFHY2RPdklJZG1DNlQ2
            ZjNoanM5U29sS3JaWXlnd1FHOEZ1NUUKExPF06HJi+OaZQLn5gY6cCu6nb0r5T4I
            U5lEgdJ+yIj0kyewx2fk3g4dJsPUlfMJU3qpzvGiTqxuENvi2IAfAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T02:37:13Z"
    mac: ENC[AES256_GCM,data:IWk283kNgxGAlmyn7EkfNfqWJ+GAeBeHA1srgJx/Q8fNzKvtPeIyLMi5USExlGNF6IcH/i4kPUZ50o8NZiFmHKKy+lL0zG5a+AZhLKl0VtRB7sPriaGQ21BDE5OWxp+8cNfJTowrCPLcjid3A9ILyV4MHvF0Rya0fe9TaSQgbmk=,iv:ZzKTaE4XUIfwh6c3me4f5fJsjNzg804aRNNpSvnSASc=,tag:emCIrwnSQFnXaf9pFEcIow==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
