apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:W1wpHxOv7jhuvkz5Shnmi1BBiIUp1PwI1W9ngU6W3iFYurbQ4vFv+w==,iv:oToDptwp9ceeJSAwZi0VtSAeCeLJAdTpBBf294D0Zto=,tag:8Dyk1o0+tgVUA66otN4dPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteFZTa3laL2IrQ0Q3cGk1
            RWhZbmlTNFhhbFRyTU9IN1pocStNTnJpS3hrCkJJOW1qRWZIS0dPcjYwdXEyeUFI
            ZnNOUXVMa3NsUUxRdmpORk8wcGF2Q00KLS0tIEk5L2x2SXB2WTNWSURKZEhiam1X
            WGxCbi9zSU1OdEd6ZzRYdTIvWWd5cEEK65pumLrxSkvojuMv0IZIcjgLcTRmO62X
            WgBTQtLLjRitjBR46n+R6rCoI3KLbqiErX2CWpPKy0SGrJzZEHnGAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T04:04:16Z"
    mac: ENC[AES256_GCM,data:JBHuqBYHSKk1mQjMxTCf/i0SlZ5Vp08v8fAKRkEXPv0ELG/UuNKbNfGu5z/6fJXvrTq/9Dh3Y3ap3B1UkD2rQixHjfezMjZuw+60gVrjkF3ZLUuvmfh2iK5n397SW36b7pOSHibMHOaWUlL2/LURGZvaw0HMo5KkKFT32LC4L2Q=,iv:narg977h6SUR1BCvGNlnQFoJaRZufse1uPMySYtb7qc=,tag:bis7YcMvXUX+nKDOdL9atQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
