apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sBGsNUdv6AnxXF5prgeuidgKKMLhnyT2/ZXhNf+6ORJBRcbjmU7RZQ==,iv:mBmGuEXC6V1+WbGYggg7WbsDTcf0+E6U4P5Cc+WC/eU=,tag:3baCWIOkB+kN44V2sxiYqA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTHlGRUFjRFlDN2Y0bFN2
            Mmk3Q2hVb3BUTTBrSktSQnFOVVpUR2V5VTF3Cmd1bk1xZGZXSEZPeWpha25SRmY3
            RkNnMDBVQWo3WU9rTG91TkdRWGVVU00KLS0tIDFMbjBhdkRsUlJtam5tWjUvNmdm
            TW9kQWRycE9Ka0FFU1YvNGtMZ2xZbEkK0gjQvPBltWOONf4et7vLjz785dvaO8Nv
            YRvK7MeBxx2RA4FpcIKoOEnlI8h4MSPCYpgY6c0+mAmutq1PTUBrqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T00:30:32Z"
    mac: ENC[AES256_GCM,data:thThhO/TT+Ki5vjcOMusEL6dCr+cb36wcP6wjh6A75uYv0HcoEtenXXWtzdEQySTw1VMg0soSIqhMXrvuB5/Qd/R/2M1vD6+hWxpxuMc/slI4IPDJCNBKrXEOxttc8i8udQh9QIoaTTDH5QaWKFjjVw9Yl/hkVlOikNiSIgWbTc=,iv:KhPViN0FsQS4nJM8WkSMingf5cAEGKFKol/SEDExCS8=,tag:9hZkRg+khxoeT/AUf7fhlQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
