apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qPIqcWwHHYcm7L462w7cCOlGMyNrChKjmec02Kc/ew1pnqPrghBwRA==,iv:cnAM6m6i9STpfli6j5Df9wGBprHYShNerBMas/lh+aw=,tag:MnrpCNt8xtJFik1hiGqQCA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcGt0eGdvTWtXY1JjRExB
            K0pKR3V5ZkcycEdlQ3VuTkdWazNPL2ZqZ0ZFCitUaXhYZlRtc3pzd1lQTUFRYTJK
            d0hqY2JuYm9tb1lXTy9mVmc3Rmw2YjQKLS0tIEVidGd4aFNhd2puejM4a0Q1RHhQ
            bm1YZ211ZW9yS3ZheTYrUk9uN2N0alUKvwfldHTHvR4lb6cmOSN2NkZk5pPYMe34
            qtPd/3HjvRIKmQKz3lQbwx46Rd8cwq4GpfwktV9DUgB/dJrbT1cLBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T00:01:23Z"
    mac: ENC[AES256_GCM,data:rSGmG427QQLSiLsRCHrZpT/EWHuv01n9GTfWwzDbo1w8YbjfIcfS2j+y+0leW8x9WRa2MwrwlvsCg5basoi+EYhWYOTazX2D0RhiCVu4MCRsBDsy3GE7HjNjBHg/ktd/4ZccfzNL089Nmhjb+WESZk8bOrD3YKlK3cRqjz4CAlM=,iv:PtDOkn9JnIlEOQ3p4aNW4MszQx0CsvAhsvfOkeioGgI=,tag:nodZs88nOmUliU/1NIXejw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
