apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:fzFrevVd1yyAlxudEfydWLooNERGtki8lwh8ReyCqNRP1DRHRMt7Vw==,iv:7ifEsco8lcNW+ZgKq88fqOTtx337m4ELW04M8s9MGF8=,tag:aZEkyd9UoyYPP4Px8qfpNw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZEJXZGlNS0hDRC9BUXgw
            NkNPUmpoL1J0WGs3QTlmTk44c2xxTWtHbHdRCnQyeGV2ZEVBbXlpRzJLVjlZb1lQ
            ZXl2ZnAyZ05UemNCK05sa2dmMURUWkEKLS0tIHlKcG1JMW4xNnVnL3NpZjczZW82
            a2JCWFM4bGhoNGY4emcxeUs1RmYxVVEKVEPxU55nXZQfmzDVgzdJYVUXIFC7rKXW
            3RY0YAsmqI0SHFSAH3Euv0C6rDdc5vbllhyf3GYWi6j/zuR/j7ZygA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:14:10Z"
    mac: ENC[AES256_GCM,data:25YGYLtkgKabNlB5lHoVYwyr2mi2TLYH3/D7ZJpu53cr9M8vmw9WTOUX6cuL0qr/6JCljunRwTIffRVgix+xlz9Lie/C2nY/3s+KF1iguXgBQAYjQabdWuw6aNuNj2YnPuWP2nBd4TjFIlVzGI2cBqSfH2lIQgJz19U0TEoQ/Bs=,iv:/Yc/MU8yi3lpGFNm0n4FqV6y5OLRsqxTVFXIlG86cSE=,tag:dv3aRBrqUzr4wG8Ip1Wx1w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
