apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zzQm1hLxpzA+hc7Bw+AtAAQuX819NmU3ZHD+iXJQ9PifFtRKGbSEuA==,iv:yCHkocgdh3wYAebwKNgPyUfnoOYaIxCWKPBVfgZ/Z/k=,tag:iWqp4ShXlolI0lRZfBOkew==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZHJPZjEyWE1rbmlKaDdE
            RkNlbUZmNVJJRXg2L3l3Y0hIcGFkbnYzYmg4CjF6RUdqU3Z6eHM3WkxuUkRXTHln
            d2dvKzNqTWlpK1hCY25nT1gwRG9NOE0KLS0tIFhCT0ZCYnpuMGtyUEFGL0FQdlE3
            K1laQlArcVMxUDdicnNLSUxCRlgxWlUKsAIvJBY95kym7DACd1AvYEmoefcpA9TQ
            FZjWdAiEMYIT+/PI2mjGtoHNdGsHEG22SlrGayW2judQolXKsea7WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:58:08Z"
    mac: ENC[AES256_GCM,data:PSyvpaqLQtfV3tovYVyyq4W5DtrxwZWYsj09f3HWsg9IwPbJiMSEcROcQ05RiiIyWeT+6mxt6VQqIyCdvfwKOp7ZuXrwL+g1WfF0sUKfuFwlxH/IOCEfAkS4+RuvqI+VMp+DNxUZssL998oj8xlg2RudQXkxWankLsCvDsGsWcg=,iv:ug6A4YAT6tVmdYC/n4Sl+KhfNKH98c6jN17GbZmn1dM=,tag:WKV2fcSYLYxP5Jugk1QlKg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
