apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:f33KG3wPAnZhvIZZS4xFOGGn7LzVFYPyA8HrDNVzZCS+bUzZDZAp6g==,iv:ojubrygprQqN9iolidnQiCM/gdVQsb4DdofG1+CsjIk=,tag:l7JSUFeHGMw12MiyJKbI4g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYUY3dHg1NERVUTlpM0gy
            ak1pdkFRc0VyeDE1KzVxWml5RmIwVE95b21JClNoem1KbWUxNWFqU2VGMVN5R21E
            ZjZ5NjNFY0xOMm5WZkVBblNiNU14S1UKLS0tIDIzSFFMSmQ5U3k4TDhFbnNWRnM5
            RGVCVHkyYjZkOTg0eTMrb0M3OVgvc2sKbgARo4QurzBBHDMnAJy3rxVX1gprxJF/
            wPYXXHh4JDgp2so/4SD2rWK+j2JAjRlwVCStbRnhL9hzUTKrIQcKHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:35:21Z"
    mac: ENC[AES256_GCM,data:OygpxoUFXq21L2Oy++4jfBoAYoQRobSjEqg2t5rLeG+JC45M3qlQX6gjWmsHjZYHzd+Xam1uJkw3NtJlZSNz1p+/ckHXVNN039udsGL096NyUDnoJp451nluYTjsGTytnbhuR60jOhgGwkR2bhIGTlz3TPA2Mw1nBUdcTIAzpEA=,iv:tJE+/ccR/HXoBJxQI1XRkad1kAjMYVzn0I/4osyAs5o=,tag:+sHp7dhYnGRSMaxMtvfSSQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
