apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:71K4xXotwEgb1jUpxBm07CXhEzwlqHeJXLKArYCFgvaM3xEWjOQFgA==,iv:BG5bvMHfIRjR1A5n0RRTISfLT8e1d9GR9kl+XJM9Hmo=,tag:9tMpqGqsbcWuTfoaJJZKGQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1JVcFlpUGx4eENELzZ3
            NnpPQlNWNzdBY3VReloxeGdpTjJ6K2VWMmxJCmxpODVKaGw0dFlGc3BjSHgzY2t2
            VUtvTm5Gb2ZIQ1p4dEYzcUxoUUt1WG8KLS0tIGZMcEhIS0dXL2Zod0pWV2kzYnp4
            ajlmMWlIbzdqV3VVYVhnYlF3T09TSk0KHXbBttrYyHGzU/yzOgquJo/AGbFS+uxs
            V5Ro687V1BY1P7CaFUJbHdmuSd2lLU7lQYxoYy6OFOamW6a+BZoAmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T09:25:19Z"
    mac: ENC[AES256_GCM,data:I4BInmH1MkMgJ/aq2lO/hFqQs+ztwQ8w8ivjo/QNZVS2hCgcuHCySZQwQxTfT7ZwtxGkvzDKFg1NryEfkSRH4zi5AKTH1CcMK6bKKDZpvQjiYdlIQ//jdZ6ZFfWsPZlttETuh+k/THz0wcr1+X7zuHPw67MyIliRCojKIsxckY8=,iv:KpoMfwVergSH23Qky+ueOs9IbqVuNZ5Lhzp/50ezy7s=,tag:mDkqVl5CUL1LZxDk3L7ZcQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
