apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:R8NKnKlL+PmQT1tZuNbyb1QensuJxvR2bWgFA8REIFswFdTIYskn+g==,iv:xhFvnixYbIPFvreZn+6DWrx4k/ZGDjmOzyjg+PU2bA8=,tag:W4o6mnfuDp7wbnT+JNXDtg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcE02dndsQU1PekRBMzdR
            dFFZZTZBWEJpUlc2ZUZGLytXSTZNT29razNzCjZ2YXQ5YTJ6OGJQa1o2TjhqdktY
            UEVzc0dqbUh0aWcybzh1V0pkanp0REkKLS0tICtabjk5dVdzMW9jR3dWTlNBanNs
            L0p2NVpDMEVYd2pCM1loODgrRmFBWk0KgElMN1gIf179plSSpOtBnJLJjqbOubZp
            d0U0HPfK3EHI31GD26upZl4mkiw6Ig66qc2F8yk0LzQvthzHvOnlNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:58:57Z"
    mac: ENC[AES256_GCM,data:5ku+K5tSjjMJmgGpDTyMLy7cmp13pUv0nh7FpVu7bVTMon8JkcAxEiua4L+FyA/NaBQ7XJY5AcibjgOflboM2VYBuIjcUxyrR7ALkiHO5EjHQN0689sOlo/93GyGGQR6PasqZM+aQyEHi52d9k2kyBez4QKd0Tr8WbEByEXfkhI=,iv:m9oZEA+lYceR3DKJN3CCutpKvPPtgS3HtSbqG4L5GVM=,tag:M6YneIIOhDv4wSe0uYcgpw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
