apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:plrmqlQFf2psvk7c95Mm4z2PxF8dUVt6q8ZCKh+8stsZ/QChqztmew==,iv:Y1Em6tFkdEIY0q7AlqqQUa9XPE7uBHALn+DURIGJPMM=,tag:YeO/nbq9Nuje8p8Fbbi0WA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc2VmN1QvTlBTbFMrTjVS
            WWExL3BIRHU4NTVBS1pnV3ZtNWdiUC9tUXlvCmNua210Q3o0MEhwdjFhTktZSEtn
            eXhjSG5ZZURwd0Mrb1JMTGx5ait2TGcKLS0tIGh5YldraU1tVTFFVFI4WlNYYVJa
            UXNHOXlIcVc5YTNwYStuYnRRODRxTncKfRd0YxMyQbvzXfQjrZ9Z2/fSvIfr5sWg
            xQkHJi4DMQEj1WIBQ9jG5LAor6wMu4JKdIQbTIEljgtxRTAYCJ5/oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:11:19Z"
    mac: ENC[AES256_GCM,data:Syy54GI+jihlGoEsVjIppZGhXKO2bRojaHDl+vBFO8U3eSgBkxNUR7S3QX5hFFmp0+nfWT+uin0y+biQedl9kepZu+5GG5hEY8v+77n64XgQRtv4j9g5HSSwmBqqvHrwkQq6DS6TwzOZYcNO+RqB84gdPwHt80txK6Ra5XDLtk8=,iv:oRaPWVouHUjBBXPN48n6jMx6ta/wSwzpSiqcrSyirOk=,tag:I8MM974BLaEyrjNYEE+x9A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
