apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5UlARl5PqNNwfp+Z/uzQFf9O/TXatGnEEDmlM4m3MBDjdj1BJ+/RzQ==,iv:l814CyMoON/RCykEH3WVaV0ioooPMY+uRujpC4E6j4E=,tag:TAiZkttn5Bnys09oew+RIg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWEZsWEJEb2Y5SzNXWGZq
            NEFQaVhsM1RoVWJSdGkrcjBCSG9NNHRJemtJCjVZN2oxS2RjWS9pYUZDMGFROUZk
            L3NqeDdNSzZLNUd6S1JVcVpMVVpGcHcKLS0tIHVDUFo4SHNBRnltc1FKZXdCSXYx
            RXRmUnJDQ2lTYURTYXFCbFNOaFFiUWcKogdqRXzStsOe716NuibORAHHlByj01ok
            c2NQOaYkUM4HVWfEEyRJOhpDKnLani6rMuTAqEavcI8q1QcWMqmDiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:21:11Z"
    mac: ENC[AES256_GCM,data:xOgGWZsFurB79gtX1/aSMpfojBJUoFF/XjpTzGoUWS+5DzD0SUNoHQKKNmT7fgTQahSQwQ0xeFlCAJPOabnZd/V9OCQwqbC2aF/x5vR5cqzTKLeTY0R9v2VtKzUZahs1qvljVWYbjGO2bxG4zA69kGdrexpf3ucZhJC6keRypw4=,iv:pEsvi7jMShyOVTgOPUBRx1wsD9SgFArJ5NXXJv39N30=,tag:rSKmQhUI1lHUWULsDHiq0Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
