apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:GnNoNULpCBvQSlmIu7jtgxMXRucGiKNE+6/adbTjntcuGYQhTALt9w==,iv:pHVF/i57yyfFoOMKHiPpOvok6bz9lOOy6jsnPbVwws4=,tag:ZM+4MIQUrCYw+swevDBTgg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTmEwMW4vUXVybE5QbXNx
            OHBTSVJ2ZU5BODR3a2JhSTZvcnQyKzFNMTJnClRSL2V5WTNTMlFVNVluUjM1b090
            bzR0ZUF2dDlRMUcvZ1NGR244bFVLRWcKLS0tIHBWUlBGcjJzUmQ2WjFLZmJ3SGVr
            WHVwS29tUnhoVkJia3J2akJaOXljQk0Kyx6kPfOxwRhocgMk+kcxHi+puM/Dd13m
            Ph42lBaGVdtdmw524QTh9ju+v4RKa9yaJYVd+axRFa4UmZDbJnJZlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T23:41:10Z"
    mac: ENC[AES256_GCM,data:cRkKpICkVJypGDXwQlWOVrQUEMsU5LU3KuL9YBblw87HoGx8J/lBeMNN3t4zEzHSW6l2/D4hCwXEJr8woo2PaHXss01tVK6o427Sr8c4DRm9leXEnXvmVff/oG8g+fpb/sb1GcaIPvjnGgMxdOesr8jIMKzru+GIUIhPYC7R87Q=,iv:iad2sex35tFfRQPAagnLaPXyCOu8hUL6dEifz23SOiI=,tag:8v9pC/+SpzSKN8V3cjVWhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
