apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:nbJo/sPz/Gs9SjEnnshVKVzLKTWgJfk/Jj1LK7Zg1cXeWqVjU+1bJA==,iv:olv7eYgO9ifXyHsWyqV7uKiFcUTwdzs7ZjG8xy2IdlY=,tag:smdjBiOJDlytuTD9yiMmbQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRVU5bm1yRTdVbnAvK2VU
            V3V1QzZ4d3RGaHo2bm5pZnc1aVRZRHdhOVNrCjJVQWpPWmk5VFp2aWZwQ1FjZDRs
            UHVwYXdXVXFCU1FTTUVuZUw5dkhFc1EKLS0tIGRDZWRicXlTWktqbFZVY2psNkYv
            QlROZklJNjBQT212N2JqVVJ1MHFyVlEKzPAPBgZ7sQ5bfn7Ls+WB5vbzfJw8mYki
            ut4oYNd88p7w84NFUHItu8LJti1On5iszSQaJXJ566K2XOzl560eHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:24:53Z"
    mac: ENC[AES256_GCM,data:F3AjmAzFyLL2dR3i1I3Aeg1rlUhCl0R1TGs/qE3QP6jAk2AHDRVY+nwtoGx4gni+3rKaSuhTEpLmYGuJ5acFDsX9eaTWmSr+fWDXvwvHGsVWZic2F+7fneEtxz95ZyGjXS5VxniPMvexVEPXRwMsaPLZ+X2DZDeJ5su5HVse/Z0=,iv:EQYOWEkAksMNrKprEgVv7wARKqp9jQMVapbCvsBovxI=,tag:/Wks4FbJYR8Wf5WSZiXOnA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
