apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tL/UBq8XriTLkzo+BcxxDP2oUc2yKu5MR1Z9Eyxac49pOKXMM4c+hA==,iv:j8C/NhwfrCLNSG582l0niC1WyQxlEcB7bhSF/q+C+aM=,tag:zhEZa2Fmu3nsXZSM22WziQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNmxxUklVYTJZUE5JdHJN
            cnFpdnROY21JWFZFSDI4dHhiS1dRR004cFQ4Cjd0N0FOT09POEZxY2QzOWNqZzcy
            aVQzR1hpdG44S1I4RlNGbUwwamNJMk0KLS0tIHFuVEJpZ2w0NXhwb3B2cGlYQ3VX
            K3lNZlJpdCtDYm5mV2NkTlB3UlpzSnMKRx+qNNZeCJ3+7hbo3EPz94ZJKfN3QdJB
            n3i0Qbunmtzoysg+gnWBtWXANEIQuJxcIsUOwuYH3SlqelStVpwhpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:58:37Z"
    mac: ENC[AES256_GCM,data:7ssyS/3xMBXfcH3JNikOZ+4r0FrF/ywR+6LLNSD6tCp84pRoj9Y2MB5pmxfwsbITcefDq1SFLlsPtfi0HCepTLFyVlhz+2g3REaAT1G6jzd9gvGXXmBYCMzo2+18YYtR7TDCh9kVcUKrUM/AIz1u4XW89MZuYy3QisT07X+cWSs=,iv:k/1lJZeRml8z/u+N2yt0ih8ZKb4C90x1YCqfO/xNAOA=,tag:d84lE3OwOkVj3fXl04yujw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
