apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:oNsqk8VRzvAlnJYqxrccvE2TtjWuwabjswNSWKEQ9Vgi2c4APf1u2A==,iv:ZYweluQ/gelBuys0BbBWomr3a3acbdxK7H+xGqpH+a4=,tag:+gkoPgWcWyi809sx7t82Ew==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY1pIbFM4TmVJQkRjd3Bz
            SmdjRUd4enV5S0p2QVdzZEgzNDhrbGtRUkRVClhZZytFWDRrRnRKelJtWkYvOGlS
            dytCL1J2d3QzN0lHQlJtazBUQUdMYm8KLS0tIG1yVVpCYkV3YzZ1dmVNSUFqOGNF
            NU9GRVpTaHRBSWdUdmxDQ0tkRDVya28KQLVEM2YiLdGFOX4qEzld/9YiStiTpVle
            eGvi/RZwLm2D7qgvKUrOWB2MaYn6xDyOdF/05xfHpr1oSUON08N2pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T14:55:33Z"
    mac: ENC[AES256_GCM,data:g8VEehWzOvEP0Ne6rjoD702S/cdP7ieqXIu+Jf6KjCV072c/Yc58OtkK5rUPKmrQf0Lx7ghPCBmjpxd+rpL3/fT5eY6Fnuj6QaVypycy7XwLnlGgaA6obxAyXrR4Ag8geOFu1aVj20UoydHktMw+u6rk1Po/WqzBGpxhtvzoBGc=,iv:R/d4KcLW3InwOhwzlh2xNBinmQ78mfrBlFUrDqSQHiI=,tag:6t+LIgTijWr06nWMw6CZiQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
