apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hc/9ycXCGjPYc7HKe0guahjt6340uQ2QoL+Az97JscTeg7Nimw7g7g==,iv:A8v5Eyo6CzTjM31w8OCohVwZua0EHPHJV+MyQpVnKNk=,tag:yTIAulabrZnRFEMuaRNqvw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdk1XTU1pVENKbERYZmQ2
            SjlJc3I4UGFoN2paWTZKdWtuL3BRemt6MVJrClBTS1pvWHEwUU5jQWYzQ1ZhTnBG
            bGhKelJoYk5pS1lpTkRDWUQwaEdUWFUKLS0tIGxaTVh1ak9XZEdtNkZmV1p5UzZP
            Rk1MMTBZVmtmVjhTenBrTmhCeGNlSDgKgYOk3D56Q0oC9QB0Uof7e7IQXve0gib5
            Fu8yEFQwF4TMlXuRggn11dSVDhBlW5/WApd1zIEDek+f9D2FuAKp2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T04:10:41Z"
    mac: ENC[AES256_GCM,data:kyml9uSaVph87C+nM8/BhOCP5gEr4aoCXK16dWiKAYz3/ACFOiNh1gF6zkLQVQZqywfxU8UHm0TjbuudUHdlq5g9T8wRzO+WalmBwW2JEGBmheAIBeo5PUOAZxnkZM8nPfCvSJUa3YPnZzsCfuSDm1MD/WFLBRELAPGEDdSECBE=,iv:xDFpt/FexHzx63+WBROnwIgy2A9euXwTRGIaNJzy0yw=,tag:GjI/4xtIe7T2Q7579nyvuQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
