apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ldobG1RXy7dosFLDlvp238DtD7DqRYnC4FO4fawBw4jGhaq+FPhRkQ==,iv:bIuublMrES7shOYvrsYtCxE+3Za1ETFKErBNvmxSiFA=,tag:l/hLN2l22GYaVu6jPZmF3w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVTB5TWprMFVpWnBKeUFt
            ZGdPbTBlYXlWRmRHVTB6WlhBMGEyeEQ5dkdRCm1pc0xLcnQyK2YzRjN1RWZxZnl5
            clJjeGdUNmJITFF0OHd4ZEo0WWhNZEkKLS0tIDl1RDc1T2E1alIwbzlyVHJCay9I
            ZnllVm95UnlMcmdxYy9NQ3RTMEppbzQKTE842lSyjWIjTTpDrPsOSbLpgM2RtuIB
            AsiVviwCD61l3dLHKyq31djA1OnhjDdA8hlxU3o+5vsAnDBEYuLfvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:38:07Z"
    mac: ENC[AES256_GCM,data:Lgo2DJaG2wvAF4oKUghC42Mtbe4VO4/3adgG57+k7xEG3JSXintXe7eDDHywrBfFzuCeLT0/Baj0Wphc0ZCBM2KgrsLraEMWkwKzbcThzDVlpaVuwuXc+XLxYK247Zbo1P0OkxWNTNEZw50LgQkuHXDONtTPu6bEpHxnXG9jDeM=,iv:g8trd0yedqzTfthsIUIIFAwX3zv4jXM8bo99ZClK998=,tag:QMawFgxsmrOwnPXoMpu9/A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
