apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:YkcHd+y+RE0ojptaXW81AMlKFyQwJcQ8s/xMSEU6gTGjC9Z3e32+9w==,iv:FszQaR/CSBQfOwMKKs60HZKrlOINJ7Q9Qr9j5oJobxk=,tag:gBNDN3RYtBsi6zwugWOi8Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M3o4VUp5S0djbVBUeTha
            R2VQUmxGb1lsbEszd2tqSzRHSDBVNGwxZHhrClhsc0FGWFM2OFpXeGR5OXg1TmFQ
            V1phSXBUK2JNaFo5bzM0OFlNbVR5TXMKLS0tIEQzNkxZQXRDdU1GMXRSQ0w0aDFi
            UU5yc09SbmR4aU1xV2JvSHh3TmYyTW8KIqmGV++kjPN5cU1c1gRJgYR7cKya0Cos
            Scspyp9EC8k0xbRFl44oAjBWTk7dN+SjsxRBXibVmdyuYzMLZxClyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T23:32:16Z"
    mac: ENC[AES256_GCM,data:ssjNza1YmM7Li8L1uu1sWR8HccrWpsKbrIa8Fhlcia7WG8xMd1xMa8rn5u6vnP/glujf+TLi4Ozjpb02fCpe7gdrLtS2qBoYh0C1akyonVs1zn1V8kN2I45RaXM/wHSn3JoWPUFctyi/0LNXwUY0fp+gmPg9Z6ip6w+1x7j5OJ4=,iv:1ESbFx5fRgC+ls8ize6+oF1UzVHwz+tbzK50rbBbsrQ=,tag:9t+NQ1NvAiakx79GouTMBw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
