apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:94wtx3TbxlADnMeToiBzUzNeDkDNPk/QxlWdND8NdniWBA2881LERw==,iv:wJbfTH/KLsQTX6ENUoVItU1BOvRArZ/mEnWK/wLlMT8=,tag:eGC+Aa6BslpJPkifUTE6EQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ3JueFlieS9GR0Yrdy9l
            SS9iQlpNOXRIQ2ZPQkZuQi80QXNCY3g1MzN3CnQxRHFrNDdXNHBEUFlTU2dGdktn
            V201cWlBQlNreEJXbmJQbDMxaUxUbzAKLS0tIFhvKzRhQ1l2NTVLbFFJNXBtOGZl
            Sy9iMHU5Smg1RFRWbkNmbnVWYVJBdWsKGP+OFXZDJHTnuZSMsLBdl689lYBSvjiQ
            eo55um4mXoStqLZ2ACJRbhmfjH85gc8oKqtV0bfO17uUu9bKdwoMPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:21:42Z"
    mac: ENC[AES256_GCM,data:CjMhXy8j/LisVlk8e83CyTCvWIOUDYxRkbBfVqiFnqXJOxa/tdHPoHs2Vz/tle5Zbp7h0uL9nYQ74rNsf1fnm0hgriT0TUt2kdov/iDcN0a3LGw+mWCx7knrJ+B4l9AQweEX3UOYjn5LWCSc2/IZTJiovp3jGixiLugfLEQhotg=,iv:tkhBLzQdjR5g26ee9uml7cBY7ngNNuZMkMSCZE/E8SY=,tag:uFhPPOM9K5lPPI5lDRskmw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
