apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:gf1XmEyAGy5+oeGNrp+/KZhbIdHHPbKVOh60maT4GWk8qyNiGBNaEQ==,iv:bPfzFX1B95LMLomNPTj10y4A9GSkb+353+l1NjRnGQ4=,tag:6QMciHBygbUT/Howj+z4bw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aGNBYnQyWGJlbFppTXFU
            RW5hcnZDNzM1K3dEa1ZnQTN0TzNpeEFKYmhzCjBwY2pwUHZqNFJRUWZQQytudFpV
            eGo1Y2xpYzl6M05IVzhvVXBJNVFrUjQKLS0tIGhmRlk4dmUxNTE0RnlTdGN2TnE1
            VmtBd0ZmUmNETE15OXJ1N1Y4L3BibEkK8/BowMuhT+Q7RUqF8XiZnde6wnPIa+pg
            YFaEB22DJAd/3Usrhik8bh4c2pIv1FholWHkR9vvKyIB8yb1SaxOmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:14:03Z"
    mac: ENC[AES256_GCM,data:ttkomQoHawXcwf05nH96zuniwKuR8tl35ZkXbG/8svf+cDe+BDllLC7W0ub+aV9crJ9RWUx65ljs1V+/xC5bWYBp0lnwAJXZROjKyrdTQvMb4g0OWcNdqcC6Z0JQtpYKsSOyqSvj34bIiSB5JobwW23OF6kqSTYrQlrybqG6Iag=,iv:pMyM09ydKkOPQGSiuxXwAQXlYMLUnwzmv8pIDCQvmSw=,tag:Flw1OZvXsVeBhlbscseg1g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
