apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1iWp1Mam2ZZA42BErCaNnoL9UczNyyM2sjLyoTQ0BuyXnjTIIT0vow==,iv:bb+wNgUKKJ86kWKhPefmkkstA22mFZvi1xKdjfNQkS8=,tag:ATIQHnS3x3CLua8iJx9Ovg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTFFESGRidzQvajBtUVZi
            TEQwTDNZOW5HL0dPcks3T0JNOFl6WXBwVmdVCmJlNlV4ZXBCKzR5QjJGYWx6aDF4
            bldXc1QxTUdmTWpQVXRwQnJsQTRRS0UKLS0tIGJiMFQzaGlaMFZoRHIxbGRzdWVI
            MWFkRmZUL1VWU3VIM2F4SWEzdVJDTGcKsOR3wJDtgpBN5pibl6vQpIX1Mq2m3vVZ
            k1uzBUtIAMidUE6q7IQxvAVWiUtFGIk5ZfiW6zGx23eoIhnKsX2GsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:42:40Z"
    mac: ENC[AES256_GCM,data:eIuITDe63TH4dZFhxnrM1aDxb3Sw9SOKgFu64df/i/mytVpPH4zn0i2WmZZRi/UU3t7lHf+GpAVyDdxW6tcWA1vMZGNbbu+YauQX6Y+g0Azg4ADeIVM3NS8DIqWVZ0CjVgU+z2oLi2+ZvKvvCKxKs3wGdmjWQaUQ84fbblOMhrs=,iv:n1+mwfRO8CaoTQ/1GestlssfiVvEiYDF7xuH9TlADfg=,tag:jM6eORhsjRkqCFxHMPHMgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
