apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZgVpV4LADteaC8MXfPqQ2wBHBxBgllwi2gFrzr4IvFT/ou95HrJNOg==,iv:jRuAd17xepk2mKoRcejJtI0DCJ2I++CZuRe7+X33qXE=,tag:aEU83NJVoM5XDG6yyycZww==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YjR0RDloQkZWL1ZlYTA5
            MDBlaTJuRWZaUUREMWNuaHVHdDduTzFGR2lJClJMdmlqa2IweUVkQmZaaHQwRUhT
            ODVvOTdQVjh4cWo1cGFDbDl2ZVh6VVkKLS0tIE9WenR3U1prM1BjZXBha2pxWjUy
            VUZlOXlxNlhYNmhGNlhCL2NPd0JQUmMKjAfVeP4aJ4xpTllTgdZG3AVEmXJxp4iL
            Fa7LdQY/0OKGPrFtB26vllLLOP5O12s5O6AY5Pk4qGU3lBzqNX73sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:25:51Z"
    mac: ENC[AES256_GCM,data:HydEM7p3I1Yuj8TErXcHBzQFITgnrwPUq7zn9dMtRwYM9soZyh5jm5/3krYU6V2bwuQ0e52s14WDpkxPbww1wjIHR7JVHlA+UqHOj3f0aVXZS7ZBHzPKMiby6AedI5TajdAKRFVkw+3vWSg9Og6eL/H0yPBf737MeCn3mrYMUE4=,iv:DftA4NDpm8QkSN4nGjwrkA5jXVIYnV45EKTyrGa3G4I=,tag:XQlZtoeZsggQXpHrNJtGAQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
