apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PJmJ1dX2POvKZQ5vXHS8IID5x//V328CSg7gs2zpjNPY/3zriqRkww==,iv:1VAmnll2safazoIee2X0V7PlHAl80bc5jVRCTqdV4xo=,tag:ksgLyPvcumDYL/dzEPWxTg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcjJaazR5ZjJhN2YydCsv
            LzJzbkIyVTE4ckhGOXJyaU9UbVo5S2M3L1E0ClBmWlVxZEtZbTc3ZFJhRi8rZUJj
            ZlBTTm1saEc1Q05Id016UXdpVFNVUVkKLS0tIEhkNlI0eHgvY0FRN1pYREJyazJt
            STAvaHFLVVdJcnFTUVJpcW5MNllTTkEKvmG9K/CdJMhrCxciq3/yO6JR6kkWuYgi
            uBT7AXWC/dzHw0UdAA2nexxro6f1cEiZhv2t0241bNANq3gKV+/Gjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:57:13Z"
    mac: ENC[AES256_GCM,data:mSKF6H6qd7t/JdkAmr8Yh3lU0P/J8QIMM8nJCK8pNSvzfmq4OeRLEXNVr28+zML3u0b7tpzAsNgy4tX9Uvikr+c1XRtpKmPCMES2WnYl0Af8BO9qy0t8/+hbKyWXdvNerVA/paKexgpFADfvkhrx2ZrgQVy63mLAsZLxImKmOMc=,iv:SfJSWcwQXzahOfK57LXsGFkNZTVEgSrAEyEDxG5sFYQ=,tag:zISKvWk41XqpEtDOO/lRgw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
