apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7WONMH1uzE3GsnLter4Yrq4KnQ83o/AW9n6Zmf8Q3rxI3J/XRWanNw==,iv:BnC9MFii7HeW8bNGCBsuykVAIUex0EUZCOyDoQXUkv8=,tag:wq8qIT7unfBoGv3wdT7KlQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ3NvazdDajZWZ21NMUpv
            NDFuMU4wdTgyN0dueVJza1UrQXFqUGExbUVnCmJDdTBZeTJiYkh6YzJoUVc0WmJL
            RDF5UXpDRjZsMVlxWlFRaXZlZVp1a0EKLS0tIHMxRlRHam9uSDJ0cDNmQlVKb0lh
            a2I4eER6Tms5cXI5K1BScDBnYlNhRk0KH0/oGLecACJYmsJ3ZnszSJAdpVkkRJr9
            8e5xwi4Gf1rtHgNVjfjmZ1kKrGOuKscH2HR3CEXR9P/W8/Xg4nsFWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:18:24Z"
    mac: ENC[AES256_GCM,data:JE9YV6tV7dzIOGjCw6eZb12/GtL1a3RFbb0Y/5simR5EEy1TTMC7kq6tpd/gH42ZXJ5SFzlMUQbRWGGlmlTUAuqTz4pjUWWUa5Z74bRMpGy7LRrt8a++T7Gs4U28EIpAruFV2uBN7Y6BahQGM0K+HSTHSi4F87r/sN08xSenMI8=,iv:3wPFZYfYbG9CN0kzcZlZZukgIcRmzMi04EAB3Mdrrsg=,tag:7u3v6sJi2EvSkYVeyrCCWQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
