apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7drIOt5iuTGsbTM9imGX4WWSXXlVvnmsGd77ERg7Y6ZfBTwnAotRHg==,iv:bmU3UtFolVgKuT96v31pDS2AqHaFmJ5hOoumN+WxmRs=,tag:4zaVWh3GBbXXUgE7h1wElg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmb1ZuNnRmMUUxZ0duWXFq
            aEM0dzV2SnZjRHJ6NERlT2k5MlVKbFN2a2hRCm1DSERsYzZUT0dGZGNLdjlzWFhO
            TldlRUlTcTJDaURVL1JvaGpFYTJBOW8KLS0tIG5Pem9nUEhzakUwK3ovN2Z3QW5Q
            TjZNa1g5c1RiVXphdmtkSTlHdXBsNUUKV+7549jSgXkLfbA0lGbM2DFPDYYRx+3T
            AsHtsCLucVgzsQJBb4/TZ0bn/2zGHJNiyIXbjbzp+2w4o6wb7iOPNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:40:39Z"
    mac: ENC[AES256_GCM,data:yb32W/Nty0qkWpAJx/YuRCARruPFHvmPDd0CkCfUyT7rsS7rhj6t/8b7Ow6MGifiMgS4Tg88fUMfcb+4ifKlmKT120ckGQLkFbHEuNjyvvQISuEdcoyaRgBwr86Cnjtz9gD+p3Fi3jWLzSG1hrtd5NU1mFSYjPqyllVRLgsI71I=,iv:GLc5v9jW1fn0Q3mIXpjU6hI1G4iSUao9VJlzPBbUeOg=,tag:7v+sanfwvdGC3gxFCnsF1Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
