apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UpnF6nZuATp0ihJAPvBNnyUOfyZPlnWjH2sFIr/F5iNhQqNhcYjYzA==,iv:VsiWV3TvrTMEJqT9IWGPL5WhOpXffGy1eMpZMGx2s1U=,tag:kRTDu74Mxel8/23AcMzmzw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bWo2bFd3aHBwS0VBYWJB
            ZHh1eWtLbkl2d2FQNWY5Q1ZzUFNuWXBTM3hVCmtKN2dQU2ZrUmdjOS9oUzBYVDR1
            KzJveGRvVFlsMjVMa2Ezc1RtVnZ3Q1UKLS0tIDZtY2x2SWVta1A2MlNKOVdER2pu
            SXlMUVJiVTNKTHNxU2cvejZnSWt2SFkKqPEjX5vhd7u04+6QvpkF6VMKUTVPlY6H
            zgog1rRyci7edpWm4+4ELhZ07gjYf65MUecDv4djulE43CVqZzwE5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:12:26Z"
    mac: ENC[AES256_GCM,data:EjvN/gEVz/JlmdS3mjOj73zjhVwswCjIkdARnbrh46gex/T5EioSoN1gHKaYKphMZfRHHjCEt5ARy7fxwsAlaa72UmPy+4ZZFMCYMOji3ZmS6TtPOeBDj6BqdcPDFFp7VBTyJ/irWTUNqZQGc0Ql4JXZK87INTVimLcnRfjeug8=,iv:2770yHnZlWQexz7jaRbRPvC3zwoXD3imsa/AW1i7kl8=,tag:NaAuMUauAOKvgxqpnXDUmA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
