apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ilTjrURpB1JPASHBk8QC307FwjoMg8hOZfNQxt5Ps0z/TV4PsHUdkQ==,iv:lUGOWsiexOa4ZH+k0ZmA+dcjwIZzh62/W41sHBeDsLU=,tag:8Es8XQme359fHo9jABig1w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVmVMZVZVQ2Y0RWN1RUpM
            cTlxeVVQME5ZNnI1WUpvVVVDMWtIMEZReUNVCjB6UnhWMThoT0lBYTNJMmVxa0ND
            NmdCYTNKTlBLTHo2Qk1wQUIvM0FBd3MKLS0tIHBYRE9IdlB0a0lIRlkxcCtwZmJh
            a3lBalpMdTNMWHhSTG00TktOd2VqTTQK0qCu4OD5U0ZexC3hmS85rRgjJPF1SN49
            Jm4om09xM9nET2Ks4VoqSrgMPiVJfLBBAzWPY8EG+7LNNOPJJBqrVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T01:12:48Z"
    mac: ENC[AES256_GCM,data:yhaBd6f0mshZHZrnlbKBVp+3YX6JVD+FQL39yDTy26R5f45uwL4CyntgHKsy1CK7ABIsgwhVzDRhUfTv1qDklAY+RdkhLRqUcXCAwKp6IWyQUc3SM6sECJGmSbKgoIC3sav0P7l15Eos8cfLiUb4uK0Y3LLS0muyNRHY13ReFDM=,iv:349iCgmY4MHuApNAqoxeeAb/3USV4YZbIR89dRKxhvU=,tag:kGzzP2ejeEULSW7JmsCw+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
