apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kpzJ6x9A26osNHb8Hvc3SFofV3F3pkb17bIfEKXg8NQn1t+bPO+bmA==,iv:78JTIaSQ/iIwYEY6BGLkW3BO7Vk4zK9oIhFueMKLKkQ=,tag:8B093rQswhbleIMJ4aYIfQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZEhqeUJUUlVrMDQxNmc5
            YVI5NEh4NVQ3ajRTdFVaZUhnSlhHQ2F3bjFVCjg3bVdhbnFFUjZabGRTWVJxa0Yx
            dXBmYWVKcUlaK1JKdGplL1VjazNoOXcKLS0tIDF6dk5EVmloWDQ3Wk1SNlZvWnl1
            bjdibWNuSFhSRnNNVThpdjBYMksycHMK/ciMuUdXM5jwto2y5dWjnQdn/ULvTXR1
            Lg2ThYbwR95REZdxHtnxWlSXrCNg68AdSISWhHo8Ubb/X41wxvNlUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:44:23Z"
    mac: ENC[AES256_GCM,data:cpxloS/kUoqEw8Li4caVrixLXd8ZRdjtGfLJawDSHn7S2PYR4CEkEdTBaFxjYkR9bncPFE9tzemhx+lcxHvLDXRpjDgcVtxguQvneVEAvrVSxfSW1E9Ss+Lle2fns0zlvu6EB1wdPX2ylrFWBVYMWt9XVTiQtw1W21LYxMqZwxU=,iv:qQmpDEI4peT+vmaNFfZGLMDXORo3AhZYkKU02jIZD/Q=,tag:8M5x1eCwMpSRtGUREpB3zw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
