apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:g3U6fzQ7E+EggDkj+cscjvPTmb8zFbbAgNiEn2vUN8YrdewSjgQLhw==,iv:7o+k1fkh7AGHXrWmtFp2GWMt+RQ/Ekh+GHQgehvoj3Q=,tag:kwZZJPuSXndxDK5uHRSUhw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK09CcUs0OEJ0VlluVHc3
            Mnp6L1VkazVsT1B0NWFNVWdXQmVtTGZEY3lBClI2NlBIVWVUQTJuVkhHR2RiSEE5
            b2ZDVk5GZ3BxYnRqUjhsemkzYkV3VEEKLS0tIDkxZy84dm9ITDlUWnBETTVhZ3pt
            VnNLSWc4cWpXZE9nS0NGcGhxdnJSUXcKmNt+1zIYQA9ypTGdQMA1Zawjv6f48oOB
            j4MyY4ATfJNVxupBmtCMvY0L05RMY2ejoYay4Y47o651PU99hDlWZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:34:21Z"
    mac: ENC[AES256_GCM,data:VSqUM9JsSsG4E6JItPgzaxZ+13G1VDztMUT6iPu9quRAgBi3YLNIOOaEg8s9D2TsAjqgTfq5KK9nyYS4b+XiE/6gJvcrXRQbP6Ahws+fm+t+Kw2fOQKuyHhqFO7o5v7oloSZs0JzRVkyBoJss1Wrf4WE7lWf9SNslG+aan9V/WQ=,iv:kE5j36JTRKvx1trnHAyL0T0ECfwDPsDPyEEcxsnLkZ4=,tag:K3h/qzTfF47AEzzJXnedIw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
