apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XNOhhoW0kaMugxg8Yf4LWYrJSlnxXdp+2qc8Y/n7LV84Q8t4f+Hm8g==,iv:YvAkct/X1dznoqYz6povsXQhUyowXfnNor595E1gO7U=,tag:GOG1059ZGncGRXfJ3O1jJg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUTFsSWEwVFFZb1haK3cr
            ZkJCY3YzaG5NNUhtK3JyOFpqbFZqZGNCQUc4CmhPV01hUFdjdWZvdkxsYURmSk9p
            Z0FjckxHb3JSaHRZZzNxeGFjSGY1aFkKLS0tIGpqckZFRGJoNTdNd0ZTcWpRMGp5
            NzZQWElXVm5FS0ZYYWFKb2pMQjNlUjgK+ZxSDH3EPeYPrU6GN89oOCV7VnDGFVyx
            9ZQWhf2B5fljY1J9bTzwsAoJqpKLD9ttE306Dg0JDTdlgH8lVsQWcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T06:07:59Z"
    mac: ENC[AES256_GCM,data:YVbeYt6szmWpzP5ocxZJuqs3YtgyeyxsMA2BZn4QmJS2xvef4SbsALNNe2zzyJk/GKscLTU0fOJYKd8KVZTegz9B8KdyXk7bzlSm+iMF8YH9qvWeMQek1zoUwRgsglY54Hw032QjSQMUahvLoH3/WpcmEpCOKleXuRA8/OoNntE=,iv:0h1MPr944QGMNfdyMryS0T9+Y3Fkum8nNyzBCpBsQ9E=,tag:TbSuxQsd6vN2Kkz9D5dELg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
