apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:c5pnNCnWclzYP16jHarMWs5kxeKSF3wKvipIRkqspTvkqFMPYTxHTA==,iv:oDKWWU1D37psuw6ADuRazRMlF37gWodNRWxEwi1sZrE=,tag:GbFlW023RDs5FLqnGvOqZA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRzlndlVENHg5TUxBNGdC
            Z0JFb1R6d0pNL3I1L1BaL2RITWxFRzFGWEU0CmYzb3hhYlNmU1VHWk45ai9oWktt
            T1U3Zi9zdzlKYno2ZC9UTEtUNWRJZ0UKLS0tIDNycFY3cVdGN2gwdGl6ejRyN0pY
            NGphaitQU3NDMHlJVzVndi9iSmxXalUK6NNAL52+IKfVTr401O3PrWudxZMIauxg
            5kkirvXZHAQuzztXwmS2V5tJvNzwMg83zhQM8xAg3AjBLNXPBQ48aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T00:18:21Z"
    mac: ENC[AES256_GCM,data:1york+uCiGBFU4s2osRRitLtK/JmEzDp/shEy6H121n9j9cQtvtYTq7Lhuzzj9fXBEg+cXglDvPHLf2JUzUai4iDsqrOXTyUytW56NhP1Ekh0AndGXE55+bImEs2w8gzzEHIU6pup5UIlIW6oMQMQpbKqBog7Wh/1Squrjj1Bk0=,iv:MO60gT2i76A6sq92TFDe2viZizmG4H6g37cwMTp1UZY=,tag:czTqCSTCQIofghhSWnfaDg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
