apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+3769XLiUV3elLCkOjEqYjYN6Jko6gV7rxaIW29hTRQzhoevbltnFw==,iv:Kb/4P5rJ3CoqYuZM6XbIYqEkt6IrQj/pbCvnKf6CTP8=,tag:NhFn8H4Tgzg2IloisdRA0Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVXVrZnVVNGR6Y2tBS0RS
            NXY0YVE2WktiNk9WbmlOb2gzK2dTajZUMlFvClAwbmIrMGowMUVtaThMYXZ2OUVV
            ZGp2ZktPSENVMTVPU0EyZWRFWUVYV1UKLS0tIFhiQ0o5TUlrZHVFMzBFblFBMTRF
            dkp2UmdPMW8vVDduV1NhUDNVaXA4eVEKXt/QfpyLXL8vUnseRQ1OXpIUqXUWCDL5
            jqbo4YPLfeDu3Ei1NgWSPioJIW5M82n26l6YbU8frPSnPBvg1YAx9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T00:23:59Z"
    mac: ENC[AES256_GCM,data:VN+2y98O3+QhQAUaZadoudKpyA3q5zqhHkjzx7JCCWdsMCVlb814f1TU85RoguKCZxRsqTgSE0bxVjglGEgXEnuID4JTzT66ONLw14+DapD2pMK6KH12RyQqEGaiyKMeHNlc+meDeSk0f7dIvj6IEtn/ZjAnvMPiZHW0cngNLiQ=,iv:WwQEbHeTgnJjjb5EOfOmzVvyXalcbAn3Skt+SyNMPH8=,tag:2MBO7/Ajrl9uTN7C5OCk5Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
