apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zfQXqy1KwKJChukW7RlJPggvKAiroZdGNJDm46qrRsLZfky8GxEljQ==,iv:TdyoqbDObitXSXu0iPCR0us/VEhvRUi18pD+R5sB+No=,tag:8fzNpXpZvdleQdMgF9N9FQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZkNVbE9XSCtYSWJGdHVE
            eW5KOG5IZDNGTE0rUXJJQUEzbVdMdWtoM0JNCmhuaThNU1pRb0VsdXhlSHBnQ3VR
            cjRyNlVqYm80bWt5OGJqMDlnbzJMaGsKLS0tIGs3NENhZ3c4SEw5OWJ1WEVZNGNU
            aWlaUkFJOXFzM0pBR0pyM3RJNTN4dVUKwoT9pjsk2Xtb5IsXWzxO9e98CpFTP7Mf
            OsrTWmhT6Qn9NFvZ3H99rk7Oh7RHg8tV+thOBz7JUvX0J73BIFvYjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:27:38Z"
    mac: ENC[AES256_GCM,data:PCwKRRaRagExBdxXO6UhtTt3GnwWACc0PKdIfM/LDLHKhs8lm9G2sopvGIMDVNxXe6xh/zZICL4Ch0clO7dgnb1wqETnDq+oPArQf+ksDS3PHnmvG6an30jhXYI15hGiB+4Glzx2bw7WHkuBzv2Y46jvUDAFy3x2uuHMPTQT77s=,iv:KLd9xe41e97AySxIQ7Ny3PkMVoJK5IgZlDPb3AxRzNI=,tag:r4zt1E+dddsoK1vX5ncNsQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
