apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:lRbqpKowRZ3BrcjgCMWjxT2GiC3MlEhgCRicbIG4QbcpmiEIQZ3cbw==,iv:AeJeIbgTSUJ7aGTq6U/VC4LigTkvfTBFxpKm21BbJoc=,tag:EGULjerYOvWADV+5Hdg+8w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bUlFNzc4dW5CUWRKWXhz
            Z3B2N0dITjErZmwxZ0cwTWZ5TVJuSFg5RFgwCkdsNEFUWk41dGlJMWhJdk0xSGZE
            cnFYOFhrbkxXRDhIbmZ1Y3pCc1VQMUUKLS0tIDR2cTN3NmhDUGdtenUzek1VVHBM
            QXgrbHV6cFYvWFFrK3ZobWlhb3FqVkkKL3P/YokJJM7uDJoWWGQQlctzygl/XT4U
            DGF2FNyGKaZJwtaEc2rnV15B54yMo3fRtMZQcD8TbTmoU9fviUu4Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:29:41Z"
    mac: ENC[AES256_GCM,data:uJcHEMWc5lN2+0pGO0c46G5ye7o7FBzC1MSf6nvs8UpDvrdltxDsJM0MpfCsDp7HefA9BDqZwv/CmFv5ubMGeUpqnhKjBd3xw3xatMMZ60le9jrQvRU+7wGCiJhvde1kcBYIONUjx4EoPkwOAk0XzkQKyMfRVJ91Fo6+5McMjm4=,iv:/lRj7NC40oQg/SDNxYa0agntbcGUU2ncTgk7FgAx++M=,tag:jlAA7uRY0Q8bJibkCSxKmw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
