apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OczqSLgXz5fgflIVAqVLepKSi7cMlpFoyCExfNjBkOzOVWoxDlqw+Q==,iv:2cuTio3OpZQHPuq1AjKLuBykvLXQL/AZst1ZCY6GJa8=,tag:zcBRrUQiYLDdyuHoB3cSnw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTXRkV3BMa0poaGhxdWV4
            N01wb1RZMXdoOFJSbHFtS1dyYkdOSEs2NFN3CnZYV1VUTVVWNG92Ui9kQTFGUXQx
            SExKNExmaWYxcHN0U2FUZXAvN25iOWMKLS0tIG1jd1hFL1plWTdmSXJDZUk3akI2
            Y29MK1kwZWRmSXgrZ1FYNWNjSzJjeGcKn+rrEFCDKl4dF5ZkotznA0U/BXf/va5Y
            3Tq2ofY8frB4E8J4ot9IYKA+AZXzffIKTx/6Gf2VoEeUGpZThrn//Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:13:15Z"
    mac: ENC[AES256_GCM,data:8gg6zeLJsidKRvzhUevszFKaz/5hcHgeiRTssA64y7o3+90hdgkNYwlprsq+TaZ7H5qH/5+cLTsJePqz4ymO0lg/8L9zwIR8B3urdz1+SSIS/C0Mwov3ix30he9R3H2T6dqUNmhTNslZk2EME+lV7w8znIye0nZbDun8ffNZ3Q8=,iv:c6DpOJXoTaNR7byvflhcCeSmu8bA9TnQP8Ju82Nzd5Q=,tag:Pjtjri+1cy6KSKrSt7N43g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
