apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitmagnet/ks.yaml
  - external-dns/ks.yaml
  - generic-device-plugin/ks.yaml
  - homepage/ks.yaml
  - jellyfin/ks.yaml
  - kubernetes-dashboard/ks.yaml
  - lazylibrarian/ks.yaml
  - minecraft-dynmap/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - resilio-sync/ks.yaml
  - sabnzbd/ks.yaml
  - smtp-relay/ks.yaml
  - sonarr/ks.yaml
  - tailscale/ks.yaml
  - sunshine/ks.yaml
  - ladder/ks.yaml
  - flaresolverr/ks.yaml
  - jellystat/ks.yaml
  - jellyseer/ks.yaml
  - jellyseerr/ks.yaml
