apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:L9oZ/xDUqi38wNDGwrwKP95Y1AoLbudBTZIpeQExQb5spH+4kBBR7enki5I31T82VEVzo2NrvbAM+7TzIO4ZK/kkdTAfiwIJt018VLBI5emmdApxWFRTjJb32WDmUH3TYwonIB9G1bWqBSI2cEyqkIp0Gsf14KJlMX5MsbmxBJSqpqnYYacOkLQp7pFrK7OMbJz3U3hIImPRA7bN57QvG37Ir/AVf2Dv3bYGsvo6FjWCgb5xq+HoQ0G7LON0zg6nXtBUb3Z95RKhoDMhkrrK93hxJkKi3AE1EwwuG9ki53qdigevTZgW9fZwLIj0wO7NkIW9B8BY0Eo0/25YDWXQ02qUEgsFBwtQKbaOKlSdQ0ZpnqlsU/+ER+MAKkzAPf2w,iv:XZiI0ciH+WfhfGMzljDuvZyRZYHtUZVvRgU9hidyBs4=,tag:ZU2WVXmecOqEl0gb85rrfg==,type:str]
    identity.pub: ENC[AES256_GCM,data:d0rCI6cCkqwYQIenNOI/2YJtouYzxxflF2+ky28G9jMS5GkkwFm08ns3aUmYrg9Tby7W6xvBXNZjx5sDaJ+CBNu7Sk6YjeYZf9wTG3Pn83OI66B24P3ACWDVnKrS9Hq9SmCcFPucRLe9egzYmu51vBd4uxlxu1qEbqGckFGFwE3WC+IaOpzRrpmstD1UvF86cs6EtNrOex2SCiT6/a9hudpI1IYe5kPHSomZ5RDCCHrNEQgyu20031VDLhVs+kYH5ODfhhSkfjOYzINUtA==,iv:6O869lHd7/aMHKeSZmJaW62p6tfgtd3CeiPO1bQxJuM=,tag:3bj39gAek9vmjYIAIguelw==,type:str]
    known_hosts: ENC[AES256_GCM,data:0amtw3tROxLOxLQFlGgjfnlvswfAB4MOvsJ4/XPhF0pXUoNX5UkcUC2caE/1U9ebaZy0BgEXDvyxfVNU26Kk+XlqkNL+Y3Si2hdJoZktjgYCyuakrDKtgtTs8F0I481nRZvQZCiInzP180bglpwFg05/cm+4NhsRahT9S1LVGdTC6i60Me3fTWfJCYcpnIRLJb7TNflKSrSrTmsCJ6Br3X2S/WcUP4BblCoX,iv:JEXD5EyM8oIltfPU1ohF1e7cYOUEtQyFp1CqH9ZYFP4=,tag:t7g1Xgr9VmorcNseFPO3wQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL3BGWDhVUUF0M045RktH
            RW1xeXlVZ2djdXQ5UUpicWVnMzkyWG13V1V3CmlDYlZ3UUdnRVVHdGcxM1NyV0Rm
            UzFRWjdYRUdBTnprQXpWT3ZNNEtHS1EKLS0tIDdOd0FRSWpMU1JoWEV2UWVJTlI2
            MnJJVjNEVEF3engyemVjQVNoVTM1bEUKoyhfWz3O0W6OtjemMZKjr1Tho/dKHvT9
            FD8QOVANi5lqKwl7+PUDiJcDam/7AJGvNEAeRKLVoDJLX+az7+xTgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:34:21Z"
    mac: ENC[AES256_GCM,data:F2b7N6/L4R+bCCZXbFT4qlX2YkLeFnxfOtqzRkonIqiqQldLGIrZLCUnm18crEMUSNH97LpM26jLc0B9qcKHS6Tnd/C0nQ7HlXjxDe6OenY/o9BbKHCntS5+IVRIzNvkyylZ+kPc0ZmqvK+e/Kgw48Vf/1UwvVJv8MhC0Ljle1I=,iv:Tg5Akzyo3Rb+xW2CVAsxJMKRoOR9RjlWeTAXqJ3k0jM=,tag:UAph4DON922Fr9xEG1sFaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
