apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rn0s1aWcUILPNMPkIH3LqhAQu0IRitRRUc+D505oogGs2ky72RnjB/lWU/1leUyxidU/z4/W2IYm/Os3ED2lMFT7UaEPIx69CD2zLtxrnD94qGeXrGLTbY4U1RrC/FZFRB5HDskFo2tG0C9rt+UqS57WCsJcm19yU71EiQqNsYqDyhqFOCmnbnrLsSL2+s6sYBOO63WKzjtjeQLAGlrJROJ3m/4AXO+72uYdpxMJrog0WK5cPOqcfEUgBhisAwa+pkkU6iMyRFAMSgOxG9c72YRMaSbCKWgEwi5cCH/RyQGFjQhEQ7RA07pvaMPu5XhbswFHAYWPwe07DX6pn+Z6PrMoqHcqmL9e162DhDDpM4bgBGOb2/I6+gpoDHnGxFBM,iv:hy5lE1gXmbuTKQ7wzYuo2PAf4wBow3SV8tuLR9YGyFI=,tag:hwAIjLaJKF5P9jfZFiMbPA==,type:str]
    identity.pub: ENC[AES256_GCM,data:pFFliTAJCHwoILiKq/EAPtitRHfeKoEwmabtmC74kPQL32mGKg1aU3U7L/gzN5ixGxeAqWSEOD6q6wuWfIYetxN3TMorTihiuFWtJ2hxSZn7ocgRChRUuiePW3nMpj5uLyZ0hENHcfQvojw0BK4XALnN2NYfmVK5n/dWV3EkvZ//JddVP6nAwlTtpATE0I2W7uF8RO6ZQzQnNheMre/m5KzRMZpn9ZkyQREKfyLGbzzYVlxwdFELrE3GhpqbAoSkqMj0Mjdd/Q8tUvhWdg==,iv:GsleMzZBhOlNgm/jNDXNGfLKy0edgO43T24ng41E/Tk=,tag:y4F4FX6EJQ9qcdxyFtFTqA==,type:str]
    known_hosts: ENC[AES256_GCM,data:sgGhpwOESeAcTybeWQd70KCD0H8jgpJyuXCJPIiYpuM1SZDn4pU3uFyfBJ6SiosFIE9BTUPZ3wq6hrd3XyL5TYjXQWRnpRSXsdRG33jj1pPqgccdbw4cMB7jhkFo9aNh6bwL16VYZtAzz+B62s0X0MxpticAWWM58IPHWGInRo6KDmhpjzBEIVGg79DRZiJiVynXomFVASR97ckEZsoG+BUoRYE0I9r+fMK1,iv:znPH3rL6gWF6mSEWBd9Dktx06sUQ+/+SMvCJlQoQs5s=,tag:1yA9NdFFKNI/M5+TqoknlQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNDZCelh4ek9Ecndkdzlp
            WGY2Z1pPMHNyQjRvb2dFRXJXOURHRkVOd1JvCmZtcm1MdHJac1htalVZWEJLUGFN
            MUI1TGhXekJRTi9JTnp2L1p0VkhkbncKLS0tIG9SbUtUOFlxYWZYci83MVQzRTJT
            cTQyeSs2QXJ1WjFNeFM4R3NvTUlZSjgKhDa/Z/pJ0bjstn3Yz0kt/5jaWCtOY+hP
            AswXSzKVdrjQtZPZKaJBu1bN5Hsc48I4N0gnOZTIoBMQMDe/4kMl3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:17:23Z"
    mac: ENC[AES256_GCM,data:IdjL7Q4pGBJS0uc9hEAM2rJku1eqN5e8QZX/NLRsL1gAWg8h2HfFMATIrM6GI0SFLGgZJD4Ha6LM8UIjIfLvgYhfNs5bsA080ttXyYrI90gVBu8Va7rBLJJRj6EPsQm5X6tVmvx1f0UozRj//iU1J2MQxTBlicfPLQUXBUy6obc=,iv:cLNMI6BQP6wvF2GogoA8q17LhHAX/pnC2MXwAQp4qxI=,tag:qxfJNcAWqspxD0mAOmNCyQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
