apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BON2DjoXHrcYx/+qMJ4zlzU5Y4zrIdhCZwM2o573aisu+/GBzEwprZ+C+oMb9BlDrVaP8lFPoxW70qeuWJM6Y71CVaRA02lhOOrcc9zznrhWdE11utxCAu/fidA8dybBxEqqEQch8ocMCOL9JtA0QOyxMGoDLA6h/8kx1p4r32euWD6Zcr/0Zp6Bv+n+Rt/TODBrlPjtvDQWAL1+ZG+XMaUzsb3q+SJrgQDBzqcLM0M0ZVnSN2Tc+tVwcmC0myvVLTaCYMvp2ZHpFlZX4tLMV1HaiyI4bquXqsLaridcfUE6mnCf7dhpWli4wb/ldSfDqX+QA7P/9O6SpocZEjQlwWr5S21MldwerYpuS/pDuRDAjPedvRllpwef3KcMxne9,iv:5pIj+H6QS+QOfAVHMyYqtxBq6f9xQC6ciC6LYIv8MYs=,tag:Jwr4rnPOSomSmkG+DIKXVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:G/HbshHY4UEHu5nE33mnsRFy7xxakSyxmpBx1ci+BUhkHSZcuQ2MNpAoAiE4kp7PD23Lu3Mp7FhPZSiXg7nAa6KCEXqnDZ5aed2kb8qFfkLqPIRROAPisgWN//aYCXSfaXQEL7oH6gJwEB50J4uwsXE0t0kiPDJ69r4f53/pbidE8+dpFytrSvtCUT+XeOP3iJ74lQaEXT2URId30rcMgUrFNwF/6QTilrCzNV3VaUDlkip6Yn0de2msznSY4npyAfTMb+l40n+JhZ9nZA==,iv:eizLj/XsBNgMHiYpcrvI+JenfflW0nFZbnlXoTLWuIk=,tag:WxO3O5H3d8eSQ9wMiTfmkQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:pecsGI8ajc+lLgzry56RC0Jw24OeZUDuHhlX7Mgo5jS5l6pZGnTDXNYjWX3R8PHVqaqn4KkYtpcYPKjP0PRi2qYMb3TkONdypS4ExmuofOCnmG44J8PLmuo5y7/3Q1rzjcNfjG5I+zbe+94Ue0X71Ujn7jz5W3MKqn7nA6w6jhRxfJRsxgxLtsfw7hZhrFMDCcVsi6hOwrMr1HlLEvZyMtAv+6cgr0m6yU01,iv:U8L42idqwbjPCUkkQUj8OP/k4fpatNHrUKSZtINob7A=,tag:cASU9fdacYvIt6BN5g+fNw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNFgvTEJMWDFSZzJCd0V6
            ekNmaUpVQXB2WVNET0VOaGF5L2RTZ09DOGkwClFTc3BYMGFBdDBMaXBvWk1zb2hj
            WG8vRVFNbjg2WFJJeUlIQU9Xc2hEa00KLS0tIDBta05PTUlHeDF1SkMxN0JkaDZK
            OEY2Wmo0TThJeVZ2OTRxdGo2RE1zVmsKRlN+RJeTL9efML6IRR3HWgYQKZEsPwZo
            RjFOGAfQ3JMaz/60aEcDojRpDHUdYAvm73DKdeZHhzadAPkn9zjbZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T02:37:13Z"
    mac: ENC[AES256_GCM,data:DOwxDPthZ2Tis6piCv9YtUqU1HuHqniaUXK1V1ywil0rFw2wiqo9vxdG8CRXEJwTNydR94vw1ZVG8rqVUMRcS48cvHp+sIW6e/plsP0SUx2UV15EkbM/CsW9KE0AGU6saSTLahC1aw5jkxBiciOYO7NJ2VCSJxU90Q4g/gQJVwU=,iv:/C3EQBrBdWaP/WNdRjofCtlCpcMxBkxiCbhIK+pKKCE=,tag:ki09Ebt8NEaif4Oo6VsTuA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
