apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oqilt9FYu5BnV+OKN4gURei7cgauh1hLnnlgj4Pg6qokwMx/xOf+vTNxiavWasPfsLLBVB50iBN+L3fMC1ZovZfd59nGrPJzXx+pJbWe1x2urwBIdQvpAWYS7cLALu2mXBMR5IsrEAbTKtp0VHbOYjCFNUpXC9G0KrHwo+GDrYXM9PQgH3+wDeWKL52XrZHb4A6iN38yOKh085jesiLzSSejPs3/dSZZ1seHP8EWzd0ITrGkHTP0ZficYSF6TYWS7Pl2B62vHXV6TEFQk7rSJWWUgn5SlB3xUi/aT5wpKXW/zHYN7in79m3+a8ML8ue7898/6WuFbv/cFQDb7jgdsi8mAHONswBsJNnfVoJOiY1hZtBofdKZme+yU6koH0zp,iv:/ASsADHaQyVv4yF3/YyrAOCVOhzupO/N+rAM4WBBjk4=,tag:IsQzG0SFY5KPTEqkqfzrQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:jXSx+RWZxDNxfydWauqJwEc2UBVsDxZXuFR7vwVOXzeCwON+8pdpSSonWcrn/TJ8nmTszPOjG6abRnQbli3FqnDlLA2wK59GDsAtTcOA8kg+q16dYXCOXZgVfGjgCbvG5JuExLUoj4BWPE3y+oXmQFBczF0+n0Heae8c9jaa9OerGohNWenYhQnmZzw/0cSV/CG2O4oniWmKRDEwFxGFoFETiHKS+q9ShPgodCn7NCheK9TFad8YWFymKJK0oDP1cujDHTYC8gEUqqjAjg==,iv:8Sf/iOAKC5Mw3I+tTlA4FXTLr0a4sOm0d3U3AI5nxnI=,tag:pmbKWyLESNTFL+wAHs5HrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:IeYeyBXR+olqF5BlIjG+El2TayU/s4R8oQ0rlHheL1gOrq5ztsTV4c9xJRygR3aCDWFjYlAEx3uy+yH4jhzDT0LN06tvFYhT4CDkA8TQkyzKKCrLw5LOs6Tf4Nic7QxJ2xfoouA+Ykg/dts8bhlwL5bzXwFCRfta5Y13pDCr7CgoJbFurS7i9vo3wmsEMq72FEmvz2P1Rof/y1xp48OS+0x4yiep3kg8NX9U,iv:QujivTxOR5jZi52NpI7niYih1AD6B5HoC6Fbp4p4gig=,tag:bBqYZw/OrNsb8B19i8s+lQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T2xIMjgrYktIVlZ3STlN
            Z3B3RjhON3dUUVlSbHEzc1M5a2hGUzFkSG04Ckp6WGtld0hmSFVONURmdmhBUHZG
            WUdaQ2s4cHdnbmhsZDdGWmRWY20zaFEKLS0tIHpjQTdHZHBTMnF1RmMwZXNUS1ZT
            ZFJMT0hiSE1IaXc3dUV2aVFkQ1pYNjQKTVHY63Jj2js7liEQITd47Lx92QzvPaay
            Us4GHjgh5adijEsX4v4cjU0tAzwzHDns85kwdBTUsXwR1SEaNKU8dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T04:10:41Z"
    mac: ENC[AES256_GCM,data:XdRn9dNhnNQV5t+AClmXwr7WYW2EfyB6ZYtfz/xH88j/rAOtCsBH3uxXgvtOmSeB2H7yuUsNuc7ZNOc4MjH8oM3Pow72zlAgPeZ8RKbxxG0l9++mjVJJVuMDGuQvSfRCkoJJu8erwRS/TecEHMw/S/h+ezM/adb31LDRYAQYmUs=,iv:btu9etZPyJyIYQZ0Wt9hWzdOQHVSPP1tHYb7e5DTFZM=,tag:KozdHwRoHGqIJ0ArdvokxA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
