apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uZ7lR6/NFme1yHFsaaRnZFN7Mi27jtqG1hei2OIxXmpCmndkNhIxZbPbVAy3hnXR74E7GU6v8OEMgU3/Tp+lJWXD9DKCFkYxdQFQTdzHvxvuwM8xa7pu/pfF7vkdUjHGktyeJg9vottI5Aw3eSYNdMd/t7Sakon31P6wkEjQHIOtLAEHr07QvgE6daQH9x8NJkY98GNeM2a2CL6bn8Cn/gB15JSWxy0A1FiVB0jVPUwyJggKB/soKvwKKThLx2j//5QWXYJmZK7IwGir1/tr+3gC6xRMx4IdyIFK0/9yp1mdSzT7lequOoo2NmXuFXBiWjKHD/JPINgvuIbY8KavTmOgN17ypD5C73Zivrqd6/2ux08lxqV/Qr78dMmvIY7B,iv:WfwFSG5f7Q5YY9BlI05osTb6LLhTTj45EvEApTohHBI=,tag:6Dr+dMamYBDFR5dsIW/cmg==,type:str]
    identity.pub: ENC[AES256_GCM,data:y5H6XBXniwWxN94cjFSaDIwzPQiHdcK0ntAFbIPswdRAnxjmfuiKVMBgRLPsXH14IGV8G8HFx5pASZ/l4tkug/DUk2EPvF2b081sw8gnsHAkCLmp6kH7yTCCTotMUsc8yvfE5DzbJeB/kyT8ZwphFb/2f/tPswkL/u+BNhJZyyR2PRZMrtY7oChqn4G9AmCN5pXf6Q9eEC9nKMP5OASQesruexi8OCKBB/NH9x8JtMieQh4E1FahqxkqilSGrIaNx877fnGSiqZgX8hP1A==,iv:b0GpWhzdMgNCKNjqQqRRR6PdZDakbN1AV30aRcye58g=,tag:VHGpV27ZtZOagO30NXq6aA==,type:str]
    known_hosts: ENC[AES256_GCM,data:aRVYCgLNaxqEzkc0OdhsSKFMT4RNgNv+gz7cRodjYHWqnj2YbXIS4lPiFm8UlLDXusvnec8xDKuwH/BTWXa6GxlOiIuCrYY/PIdApP04z7So5YuliHE8ptsnHhZGIKkEEXWdpsvE7fs/pfBba21kQKeajdGPSBF1Dp3elz9+KPY3t1hKma8KdjGwV5wuhhK8KkDBdDWuSb2fTpV4ad7tZ49CkJNnBUfDgmvS,iv:r0Fo4cdGrSfHtY5KTjEPFF9NoC4zDjnOjuGiJNe5lpg=,tag:voJ7wIIkRbnydkyGKsWKtA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YWtqSlZ3emx3Vm95dXpt
            aUZ4SUlVVkdIc2JZSW5VZzZRWlorRERQUTM0CmRwajBxVVp0NnhSdFFNbmtCVGdp
            YnlCVnJhTW9uL2c2K2dUL3VzK1ZzcHcKLS0tIHFuNjNXRUNPbDQ5dHJ0MDE1TVdo
            VXhEbHRjODJ5bGprejU3Sm9sRmNBWGsKy3wDMjFIzQOFOrjrWvQc0fNOwGrnB0K3
            cX+K7l8638zIiPAZydzj0xg5nRSal2pkhFJwvVBw8WkU1i0i+46Wew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:18:24Z"
    mac: ENC[AES256_GCM,data:quzwDR5jYTKOSXzmMKhKi4cKkk8v6+IYIu9HUTbJBT1r6lKwTBrF5bWn+MlI8Etr/pOFtwwglGpMXwpLqY9Finr2Kmk3ZprSfXmBv1UHYdy0vEc8FJob/lLwZZHvupF77obfcks51j2ZPUc92/fDCkAJmxzxAN7jjhBllrk8WWw=,iv:KbP0vqCPEMbYSe/SHH2PWBpUbR0/gv1DcGTdtaiM63o=,tag:9MGMOPRmsHplnbO9p7QKFQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
