apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BA9qhdv6pAt7F1CTPCboESKxOARbTjIHnTgGIR3Wn/oB1dRa/LmfpsUDpp1E6SpXjjKr7Dh1AclB+1FwSs3bzcuhRE8+lKf0LpTaJBFzxzBG7eNyo5R5Ns7KTuqH32Ue4Zg6wjMy2bpEJVJSAIZl58qyOi/xnuZ2gbTf0a3I7eaV+v7Xmb3ybhzxFWWClmUQStXBAwT7TpG9Klh/7t5EqPmEXMRdo5KPlP3qvmxeb5Lhui/092XpDEVDaPL0ZKwAELTOtY13YoOvkwbbLm1ai0AuvBeyxvIvmCjsdXtcAgAQ1CxN4qfC/yLL4Gcjx1DKLDUfdpozrIV+QBCiwsHABpy1ICxFqoS8CXlcWW/braKQkNAyNnzVwQ7HSiZUE8Jf,iv:3LDKum0GULL7iPcGALjoVV8ZhFn2qHffKfT/ROl/u8E=,tag:i9kbfF2RSehdViUVtImJ6w==,type:str]
    identity.pub: ENC[AES256_GCM,data:yV8VgJI1Q2Qh+Ao8lI3IUt02OsQCiWytwYBrEP2iyQUWcJvUVhOUgQpGiR24MV+KkFpx60d35PK6Y76sgPTX0hAzOWveCcYk5eLztQQYi2te0RFtoL6qWEJ5DAT5mOZpamhVVF3hvmcWDsnAYIX7vCY7BapNhJKo6/gavKQGFD5ic1rry3tEeeZZXp/1S+MjSvUu5UvUVqGcNjf5q4WSyiu6/Ff8FhFP9k0BRdkMUTfWyhmzF1ZVgnAXP84F7K6Nu7UHefIZRavhl8z73Q==,iv:zdsUSoHmfmN4oaMs4xoItjOqJsG2Hb/nQabk6+3/3R0=,tag:VMyArcEeDpSJKjLcvbR1bQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:cEs6irVG2jfgI33fKTOqdcz6/LIv2647366GRRLqDFSiJNIh1bMVV2fb8u31yapsdHFRlz8YrUh7UFx7zUFbRXtkQqD29+JedVGMdrUtXhM6BhOAHHcacbqb+0W/jcbF6+0EYXuZFBt3UMdazixSKssrO6CItonLMNCvloSoocwgP0q+b8oR35SC2OY8nUs7bHpWoa8O+x21UmKRRpp0ZtuQuhxo8yBYgYaL,iv:Ag44Ch+mIyhnF4+0agNoSqg++OLofUdakc7vWnUSI3Y=,tag:bWolytfXDNtap3noGC+4Rg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bmlpVUFKczJrVHk0QjNy
            ZTg3bTF4Qk93K3pCY2tFMVA4WXJjM3R4clEwCktGdlVxTUhRR1ZZeTh2SkpObFor
            QVhNMXpUa1RyQVNIOFVTRDJJcnZ0clUKLS0tIFBReks0eGNlTlBQbzRkVWd3azUw
            OVI1Uno0LzJpdmtidkQrTzNYTEhJVWsKV/D9UsJg5aV/CPi/098UyKbOgnN80IcG
            CK9lUicEvEsIe/59VttlDHwKrehm+PaGU/xUAwFhbblp+05a6Cc+Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:37:36Z"
    mac: ENC[AES256_GCM,data:3jeofwWuP6I/CGnLM0QTdHqQMZnQS9qyouQMVc/5ItU3gnEbI0Vctf5B88UQ85iwsW2sUMYxo5ipni8NOEZpSc8hbE2lzAZEoHlzTLt6cGuiyvam8kgNc7G0zNa6GQMFkIFvayU/Gp7uUoZUSbRCoa5zhX6dG/cKKwtazrB3aCE=,iv:Qv0eapZlydFNin8oz4Dsx3amsPuwKdiQv4XlT251PY4=,tag:2hCFt6nqlIKoppqPokBC1g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
