apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FdvFDsRsi558BXcXp+HbI8Gs3vIW92MDFjJo/Gp2x5mu6MrGE5z2ORErdT1OZT+WxKq3UiGnLd2oGH8Lz+aeWEtsd5LAR8pjn2i9JmsbghjT26Jpx16Xuj5oN0l2uOAPZVdL7yuv5VBzfJ5MM0rQJhUcbeikJ2J5iWjL3yVHxpXNjGXDC1F1ve7rL3pbsP9EM1auJD0yRfNViie6h/H6iw2yLzSVegB8LdFTP+bLUb1v/X81XkHtPirJkMlsgvFrN2oa4pT6OT8z18jNayH+FlSj6zNi16FSvQcV2fSop/AKg2yQiZPMgS5w0JGRNA3cZd9os4pOb9iAFIiNMlCLsXa1GLWOHgZtfCAZ7BsgtLQftwOUEynNejaYAUP2vlW7,iv:t8xWTotUVKxF1KdvO/NnpZ8/SiS6wDLjxUimBCPqqZU=,tag:cTpFzoI0HxoBYorNH3hE+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:cct1pKNlvRxblzhiMUqk8KSqKO5B+bJVdB95DeeEUcu9HAHiEYL4sLn5yAWVb3dwRts0AHKosqMrTtCujzpRUCvbp2A0aLWXOe7V3LzKwsezDgYWV92fIppZiMgowiINp0h/QPcYrDjci5g7umjYjTrkYdo3njAuTo8Vhkkf8QgBUfI/6IaINla6HnKmDDUZWyrmH2HEpO+AYB4SivJlVCy5HykKkAueGa2JTyIlmSfb3PZKyPP4IuMsYFFkUxMuAomAVTNyKhnbjp/amA==,iv:8T5RhT9BIszv/FFzvVLAkSWypBl3Ii0HhRhtPNeczAw=,tag:EPufwg3bTSAJmHOKL0/kUA==,type:str]
    known_hosts: ENC[AES256_GCM,data:pdwR8rrdcM+Ftac7gfxdwVtInuw8M4HIZNFktqXB/z7OzNOij0CDGgsbldIUl2hLERv8o379a95kM723HMYVXp/CUbyE5wUdPw9jFTxZdvZdpdokPYQPNXT9exWZ53GwMQaCQltDOwQiOD6HSJFwhkLLCSBDUxJp73Va4zVeVqqmxkSt4/w/7UKVdQixdkquHmBFiaRyhBaUUOcELgp4aaw2maU/rUAywAmR,iv:7SX89Tcuvrjx+bbOxPxGxZbwRLgHs0UZb8xROHxFb1I=,tag:qxGVsbjASAWDT10CH1Tbtw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMWNWMUpuMVY5Yi9SanJz
            cW9nQ0NZem81aStqL3pVV2VwYklQVVhDWFRVCmhHVi9zaHREV0xSeWdwNHMyZkxK
            VXVWRGN0Sm9wa2FZelA0ZzlrR3RWa3MKLS0tIEc4aG9VQkcycUR0NEJIUGVPbDlB
            Y2VlL3hwMTV4bHdXM04wME53RndJOTQKCkw3/NWEBHxASF6y9AzQrbQU3p4XyJLA
            1KlNB/VgFGJUwTUkgIabJM7IEaRzOxWL97jy8N5SahXY5S1MvWHxWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:15:22Z"
    mac: ENC[AES256_GCM,data:vVjQ1oxlNtDNszEzPioErj/s2P0xK3WlpprhSO2pvv3eqzWw04yPdsbZ1YG68i2lvAlauT/ulFuitLDEtgm67l/4+htWFL3+99cs86aegj9/7+dUFIw3aZVDqNz4rAFErkt2aVI60QYu7MPPr+xhmKjhi55Jc/DgJhLPbmmQRCs=,iv:Ut3JDpWxZJA5uprG5lLt5qk7c2EzdNIHyjb/CU/iQQU=,tag:sPtFPxkW1wGSUQVos9CayA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
