apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jGeVVRiV+Y8NTfBbU9VM8afWm8Hd+Ade2UCkzd3whpYuqkfrZS18pmZK5NdldkHoEXHN8gdj39FePf5bBcu0I7Dl78f8bln+VW+5XDUCfWem1RqjJkx25ihMhTGmdtFiAs1F61RbRfq99Fd1mYsXoU8i8MzHZDsquCCmRDdqAfQFQC1qxxjB9J4QlVeM/ebDgTYV6eBlERHdXEQY4nwxJEqHzfp63u9XKSmLnTLrUflgp6fu/ixUBWp+dlYDVfRe+v7gy5zV4O03iZnP6578UoAygXvsuDg0WkvoGC3U4Bta/JZVIj0/hx1IzwjZJAtZpi3oljMDuSouMt7wAcAU54eUVLPGlaK2axXZ9hwlOXtYjwbI/rI5leona8KCW5p+,iv:KW3GVfy0PPkZxiVrWkEP4g4E9lmIqf03t5z+spPikPU=,tag:ggQaVtvVvnnKbhzbN1z7PA==,type:str]
    identity.pub: ENC[AES256_GCM,data:TlPx2kY/NWO/dW9TFMrToqNogq3GxZHjs3K7+XNxYF7JRcwt7QuZW6Y3c8a/dLsc2NEBZtD3G22N32MEnTsqEAiaw+pKY3WbwJWc6RoFLk4RQI2LQacm535jxhchfRLlkFoTnbx7Jm1R73Kc4w/aV04WmxvTzXGWL4BZnLWbEFa+l0kbyCdT3TQ85PrQgDRisD0tYduqwn2xw84jjl5yY96P91SvjMcHPEzDUOlK8PhB/UrAR/zaI2vNOde68V6Ii1Jd53qQ1ShNnIonAQ==,iv:nDZIdLCHot4tNM2BV9pxooHAruQmP4ltTR0v7mj46ag=,tag:L0P0NU8LTIxSN28/B5Gibw==,type:str]
    known_hosts: ENC[AES256_GCM,data:xJYPhiBnX4SMXNDkN5GGZg4iUfqQA0n8PQ2txgygrya2DVrxMk2aj0VUjAlw50oodUxHTlwVs9UphPGLZWWara5LGN5sqUHyw1hBEqKt5ZRV9QhexCLERVQ8h/msxNPH+OmcDTGa2BRFiU9VaMa1HEnLeUCP670OAPFIQDf6sMFonVjsI78EGE5eroFkwtNt+F6nDbWqk2hL9jDcmW3X+LoW/BGr2u/PHcB0,iv:AlTe0IlLCl6VauACKjM7j5RaYktFxEQsH0VzV6BoiVM=,tag:xEuoxg1xUIpgTifEWjOZYg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NTBZblNYWWhOT2pZcWVu
            eDNtYUVROHJ4S1pVZnQzSG1lUGE0NjhjeGhVClpOQ2h6L3oyRmRsQTFnQmhtUnZK
            Y0FhYjdmcEVMdUl6eTZWUTdZejF1NU0KLS0tIGd0M01ZMmlJUk52aHFoVXZmK3Z6
            aE56bCtuS0ZMcjZJVU5rQXRRK0xRTFEKNOI1kIZgtExD+KCE3RMS7XAr8Ym9tJGT
            0AgcMDYpwQOK9QBoArmhSk9phGGDLX0JZPdWf/TWE2euFLq9WqY2mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:42:40Z"
    mac: ENC[AES256_GCM,data:xdFfJIQF65tv2bnB2jXW73M+2YLSBg0NXi8N7lY1i1Tubp13Ek782YZIRA9iHWPSIHpWzDV6RHkoMDWJPBmA5TI01vNLXOeQsJQ4gs1b1G5YyIlJxcSCioMeXBi93M1yiVIRn1gTIUEmyZ2bhOvYZtxtNmXLD312sn9UnaLAMng=,iv:iFiAkWSpLwUvUKB9SoEcr6KXBGt8h/uz8NfyBwi/7hU=,tag:mwnzjQatf/MLrEFajnPZYA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
