apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:93K1pFHF6jwqCXVGk7rvfVNJNlqcxePoMOqyo7H7hVXGEV9x3oPNTVhR/ncYa9IpEPgD8ONBItmeZbEcIk5P0AgWt4Z2iGsTzebY+bP0j/WEIrRJb+p2VKLFW4furvLvQC+TmsMrXj6/a6+2BETGyGuXKf29kLB4HypysoREj4zhL/jEhpPTCoEac/a4Vi4/4/cuvXE+emO1OXDJ00tyncsslw0+7sIisjTztU2CZbYUoYszfYAZhJrCtYaz0iaK2DgiGOy8UGT4DO09L0gW+4RqXgeWKySVxJR3Z1paoLo5Jg8dCa64tQf0Q6HcmOBarm2igMX8+L3V8w3dxCk47/ERBl08V39ewctPdJh5u1PuCnDZP2IPpjKm2654KQ5a,iv:3EiQ2IxqZ7Q+BEyg0mVu2I9L3D9G4Y2uYGALjhLuM7E=,tag:Gg2VgTUvTIJkrWa6bWUMig==,type:str]
    identity.pub: ENC[AES256_GCM,data:pe4v36lIZa3pkQdCzBe21SmLVytu6+pw14FnEOiUuwTQrVqSXgISKMbaA0A1xZ3QkC3XnQa5vu9PeKwkW55lyUPpdiEfWJUNu8N4O32MicVYNIvFUrUgP9JBROPejpbS3TKFeQTo+h/Y0oExJnJe+5smjFXCOQSAG+u86HM1ud9sMYyXb3JGq8odt4O8/JMugP9jIMXaS7eV1uSg47ViEKoX9/x1y8bqluI5u6Lsr4jK04de9VchgZb+8Grf43TxTX/EBFGjDQjuTMj7lw==,iv:qHB22ajNjudnNy5A8wGKBhDR9W/13S/1DMs2QLsj2mk=,tag:1rplxNCF1uxPG0B8ZNna0A==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZMIRGUySSV/mjxHTjJordDzNwG9mHb7VrbdetEEvMf/BfMDbDy4p5wP/Ww1tbynOUyMEYBNu42kyL2HxCRJ21NThfYQZ9OSOjQEoTJ4CZX/QyfVCQamWOo5wK4OoKbcaQeBjhPtlgtI0GiqHlW3bLaH4H8FeqqoF4MkrjDru7hqST3UWGkfZE8qDxTvb1F3C/Sa1N6DwECZkOsdfPcLPIimtdEhGdqAny+Do,iv:bLiLWLJkL+qT1XPvcHkEazXnYskiOlw9coOC4qSA3vA=,tag:qSDdNUJNGVDCl6xndqJPOw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJam9LL0h2Zjh3aEVpakQ5
            emovS2tNcjZwRWFUOVptNEszdVZ2dklobEhzCllaVGJFRU5BWkZwRXRpVGxwa0lq
            bGVtRnFObWdXUWd4Y0RCVGxjSlNDVWMKLS0tIHJaVzdRNXNTRCsxOVNJVXJRWVVk
            RGszOFAvL2J5dmdkNDZ6ekFKcFVYT0UKg5qMi14lRmFkZVv8TrUs+CiIhC2HcWlg
            UMNNoi/+Fw2YeOM4qRhLafqI3vj0K8pfrfSHN0c74G2RirXCBTGRTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:33:51Z"
    mac: ENC[AES256_GCM,data:GuKYzy3SCTHaCAlTh9b96bJfDxtH+tLg/bsK/i3tKv0Sbl+MR/fMJspYGRHRUyZWxo3Csb43AyAkg/uLYtKzboPx6GEV3RRdCMfcNIOd4gx9JAJN8SpcSDVr6j/GIHICKSfIAWl4up7LB/MMllL9H8D9/a+9pGOmVCE6SsN1SFI=,iv:mv6qetJzeL+EysifWXR224X8EAlwqUrscLSNkkWyn2c=,tag:qVpUHcB+pTkt9fFxj8Qnlw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
