apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sfdRvnIUHvLTTLuaI1ZmoghYWduTsvbWXvh2iVRSe6Jx4sbG5Asbx/bcCAWkj+IfXhExKxAqHxRg6gOMH1k2Bd09WZcqCO7UVHSCBhfudY8bMpRPw4SRibiRVfJp9miH35asOVDD2JO8KizOwarNLxJntfoQqPbVUqvxWdKbs6DLnFhtT9sqmSwd585+7sVy89/Maw/rTF0M1+nluTXpS8bCCKwvIPiYOpPh07kxr/794QmsxXnKG9G66CZro1djqTzjaWXI2Y9LlccsTfo05FtL5NOW9wU+c6SR3fNwOJDQCf1L9RfXiFkWsif7XbSdugQCeU769AGUkbHtkA9lrjlW+onG1teatdIOfi3SbbfdM0tcL6U2K8zCM8N6D99/,iv:MjukevFpdIVdoQTc5GKieNWEXOqSwxyYn52MtSBz8LQ=,tag:fExRJl5IuyGCLPXE8Tjiyg==,type:str]
    identity.pub: ENC[AES256_GCM,data:m5PX19TGjcRJ9Tn3hzrsQq6eCIRqBRu6b6rl6km7OaPwqrSL5YBSmFSGPtS/ktFPhjumBOtHgtpyJLbWCa3R1yZ+SZwLQvVaXD0oks932/PTwqzKj/6UaHI7+f7qYEKk7SkqOowkx7oBrua97DnlAxINX38xARr8CmyH9WK05BoNboQ04WJIa/K/Hevoi9f4hHnDGBeSyDgpRONsLZTIyNxNaqxKW6lHTn1iB1INJQsM04DI/kAxy8cDGAeXYayXCFrpAZh/9AxAw7+eCQ==,iv:6OXBLT1VHr42S2deiintHf36K7ob9Q/vXf/CSk/7bKY=,tag:Hzd9QWQOWKewFTilyZZjeQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:MR2OaYjmpx8cv3TuADMSVn8+G+UxPUScH2Y3tqowjy85aaO565rP5VCJ6orXFlxvbzkFTvZgSLkf/Qd5CweShQb2+/M1n1WyVyqerJ6bPWE7RhH0VHpN6VvkZ0KdqWaovLYjk/1kA3q+iWFhkIIiI1Y6dWz9nhbECcRnbDmqCRksgfHfD4Nj1qWulmp4PcUx02uj/0VdXL5/1f3xkHxp1rxV9VskneLJgCNq,iv:wBxs2OvASDnhpxYOeri7ZIdZt0iqwQ0Daw6Q5TaOjdM=,tag:PJVM2ggg4n7R3OQmRVYQhg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa3pkV0lxWE92bnZld2pH
            b2xheU9KeVZSR1dUOUFqc05ub2orQjRDQmpZCmRHcHlxa2tIUEEwN3FXeDVhWDAz
            dmsyamlWUHVHSnIwaVBPQ0tGR0pKbXMKLS0tIG5NaWhsZ0tjMEhkeXJqWFhzNFUz
            TVduZDJCaWNUMjVqN2pqWFhvSVNtak0K7LAo5/RkQV7FVnnoVeFWh+B7Z+oo7DsZ
            +dneZCYoO8x47TBg3hpt5mR1VNnk/3FiLx0YF8GL1CfSA/lEgS2VHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T23:32:16Z"
    mac: ENC[AES256_GCM,data:osRtmJUmEffWYVXMaKg78Y93PbitPgrDeZs4Npw9K/C23MzqFVxyD0NBATrAHcUOAhhx4wuLkn7l/SlcGQRtsm5D3/WNfPwQ0XJFyM237jXuiUS1NYIDoY+ZxdCWYrGBIDZ8stD7+vioLht66biMk/agUTruOh2a1EItIoobwVc=,iv:ETQlwacReBxFqRVTZkm6xunbmRd1pv1c4p/HxWcKtX8=,tag:y7ujFke9PmD0w+nfwarTAQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
