apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xBhsxkd63ZPawyaLVSaVA0U8ho/HHG7pEmNodk9lKtjm7+g62GbCvBujJ55AUQd9++nhbesTxSBrrdWVrcXqTPTu4SqofCwErej6ZV7s/cIrWJmL6uMse5hLuu0T888VdZzqlk+1C2962yPYK+EyMvBqsPIYmFCeijbpjxZAaQQiJgAZOT4Kwm0i23tK46fayaIZtCqnaND2lYe0/h/q6umvmOEMndYqKbWH8AO5v+WVfHm8x6mvA5gAim7l6tIRWgIIpIG3WvHzuXhw+i1fYFFbEtzly2OoOP4VOi2GPUpuiZquNR6tMmNuJGFC0Fcw5nMZqUfU6bFGVpe0aRULE/DT8XTB1+L7vmMDloG1r01mg/+xZpmv2FXT7MMf7E91,iv:9ZqRklytpPQWoLYZWs8BazmYZ+TxcwYSN/zYpB9+M0g=,tag:fZAD/FfnI9ESNWFDpatsFw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vxx+XcYV/hP0H9blNKvQlOIUazFS3GQRVGY/reSh3J0d5ShT2S4mBA4zy5H9Fu7JhafFm1KLrxrr7zhuMgYWwoKc+CgFlV0+RhvYuyK/xPT7QKQEnc/TWNLX1FV8r8i7ozPf0ncDeDD+6RCgD2fgO6aMDOEtpghsHYc9pmdCKRxJ9iOaV33ikDxYUwM9B3UxKGOCntHsXD1HnmBE31Cowpin5hOb6UN2ALHGNqP9WoVSlXJbUiWdQMrnU7izox3Mh7HGXrjWX4IC4EGDfg==,iv:p8Klo7N5UVhjqBQhKxiATeoSi3Lv2xYq0FAoTlWfAHc=,tag:AUCkLw8/Gg8rZmq4a8x3mA==,type:str]
    known_hosts: ENC[AES256_GCM,data:j3PsqUN+sxw74lkRE2lP9DrSTWE5fGDlOby6MEhsPBE/dI/pWdl2YAWkOW+mST44yzDI+SyDRjoWmllCWCwYB23Bo2uevLPoC8hut8k+/VppfLoA0FrIH8HJKebRngdiL89xHgUUEJ/mG0dinTBcUZUXgaNE+cC9BAdIYw0x3sBBHB2kZFoPR/7RESSvgolhY06nd5wWUlf3PEsyLCYwaZL0qXxnhGd0lQB7,iv:YXit7mEl5Sm2odEqvV4MFpLVCkvERgWr8WuQXLtPcvc=,tag:BOjqLw4wApJA2nWX7YlTPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UUlHa3BQZG1CZDgyeUhp
            OVBSTnQ4MVNtMkZRYmFVVzlzTis1WmFOREMwCjZOeHZDRG5qTlNXRHRWTXp0OWlz
            c3BIT2hVeXljRFZhdHN5REpucFZoRFEKLS0tIGtReEs5L0IrUjNHdTZPV1BPelpw
            SENmZmFQc2o4NzNuQTRBSG5vdUJBZUkKh4P0Dlh/qyLiC6xhi1ZtyxszJEsMrM19
            5bymA+zN0JNqd0LpjZChk8a6fVRA6vZOkVubn13hUtDAoPe4qK3quw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:23:57Z"
    mac: ENC[AES256_GCM,data:xVXNWc0XkRy5B7Nch81h+0bXpstMhbwEignLqeENO/VY3uQPdK+w6WH34GmGry8NwKellV1sp5ByVAIsZeGzX9kX75K03BaN2AXSow0DNKGgnaJLn80W+zgEOFGcj2DwVumrzTipuaE6xyJxLbb9wKsZFsd6ypJk5JS2xHZnrII=,iv:dbl6j+B67eJ76ksQs8upJ6mp8qQBOupH2w05Xv+Irzw=,tag:Yd2L9i3Q8uxD0RTrDW1kcQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
