apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:P6iEFMP8fsvXVA8KZKJDihn6k3c3oxlssrCaqIxuqpx23EjAzAsqW+lthMxpvXXHFwiCirw4YW18fP6T5fNKtXIKwR4JQZu6V/64Js4pHeCE6XHqvvGba+lSqPoJQbP5JzVSs4G3hJXDAerkZBBihYWaJt5NRd2tJ12YlZbCS4k184DSln5f8krh4UAcq40B7+qCVout2+stezkcaIy4KL8SajtNULxGrg3gvGcUo095qBv1TaQritaTfn6t1GhvW8R/uoBoZfmliEHe6zXdbUcJytU/jF0KvV+YG/+EBTb/QPf9e+MCY3Qz9ven36MyHAqd1w+S0tt9fMq8+/5LOSRRaE/t10WoxEny+2RS+a9yTbRqwbzvo609kuvOPOxb,iv:acfSpHdIEWhBmTvz0Z+R52lQzvaXDf8j5VLh6GuVQKs=,tag:zyeK9/48FhBLQbK6/I+Epg==,type:str]
    identity.pub: ENC[AES256_GCM,data:76/R3JfRFsw2n5lScIhsI0XmVQrVuNuthoSU0/SGV/9t7xcukiKcxHUTxM9XCmsnHe7W4u+N6wiNshdSnKOYMarQzjC7uyBWodZHa4QiI8UBdn5D3jMmPHV/8F1k7gx1GPbs1KnbDbXBjgU+afWOST4e/6ps19QPbWP526GkXgXnXI4d2gssfuk2RmWis1daqsAOJ7CSDwU9J2kqeU9okl/87bQhL8r8F/csyHLf94ZjaSGwTi7YiTXrruYVeTfnXGH9yCmO46iQkghpTA==,iv:RRT/mCjqUq06km/SHUf7Zvt2wr/aHP3al3EhaEhnous=,tag:2oBN0kmq8iVXY7vyKTzI4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:Lty55e+v+qyxP6v1euvbo6a7aup4sactqfCNhSwNjkZ9tlHCw9EQGC5FrVQTdU/BJm85KGVeSoxkX7+zEQ8/junvCPtL9aYhBk6AIBjxW9BeYwUY6RLvIcZ2kgUBTG7YhkHR6bVHKOn/Mss+lp/A1IrJ/KTIxshHReHMct+JbSxO7EL1tTYBQ3u1YkRLzPdGCDfASisA92y0f1E0PgksFqa63JIaAeL8civr,iv:UmAXQXhVOHU0XOOF0edHhDPs8GKV1FcbilC98Lf5vIE=,tag:69+8dc9dVofKtwIDRvqSXQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TWdOdzJTVnllVFVZUFFy
            SWJLZlRMZmhIdVkzOEFqdFpxNGt5Q2tlMURZCnJFVVRncTdyYW1la3lYbHlneERi
            WGdoRFJ1U05xcCtIRWJHeTVjTnQzUzQKLS0tIEJJS2x6Umt6Z2JiZHczMTM1OEd4
            VmZRY1ZHZG5YZzdIRTJFVi9SVTVIOGMKqnX9eD1BPEmL1zGJMZXDkhnDZp3V5sc+
            mrsXuZjeZI1e407MkLWBiMXYIjl6xrzuEyb25ArIrcCzGc/8PkneEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:31:28Z"
    mac: ENC[AES256_GCM,data:K32VfI/Nc2EGBXYT6CHitGNkP0MLfgFIH3tTE0F0oJ18ErS9npW1h45TbyOybci5FrpHWCvwJfzC6XTDkjCerDk+bI4v4Yf++vFhMYmDCiGBJId/b78sYuSofGKxBW4YGdxKEF2HZeLTbG25BhOn8SvDzI3WLztaoXYyBaDQ3Uc=,iv:UUw9LBch5Ayi5ZNVX2nmcvP36I3ZDXTdsHtnsd93zhE=,tag:n+3Wej6rLsNUW5op7d7dJw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
