apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:I00qVH1CZdDm9fu34nIYwVac+tLkXBnZr9jim4K1GjrA0XqjnGJl9tZlRPraNzf0W8rYD1oTmwsab7O37x6vTxwAQ3gMUJCTLeQHmyiiDAcbAPH/3S8ePVpyCZ+TKfEdF87x6hqzysn4SsGBMWwSIBi+h8V0mAAPZpfeFdkVLH8ZCv1Zp7QgzGWJILaTtoQFpsjQIbWNfTuVP/yRLO9DwaoAMXZT/F5QHnVTN84DE9jkh478xdoduVv3uiS32K0VDDVCvTbs1SVrObLO4O3ZpYJgC8XdTPo8RX6yoVMNhklGhc6nfdB3TLuLno1mNhIzOgizSCEhSxsMRgNao8KQJzor3vSPpbmBBe62NknvOxrrwDanXFQIFkl7A1ayaQ59,iv:3C2HG3HKqLfMRlad3IRM6VidP1wY9WUNTub7mCuaVUQ=,tag:zADIKDueEb5/D5678JeBAA==,type:str]
    identity.pub: ENC[AES256_GCM,data:v/AGrt7iKRVCmYeQJCn71IV3K/XgdlHV/VpdRVcsXNOORqOpk23+imMO3zhZwWE34STMerAEhwdAcHqnIu1wZHUw+ekwCUk2STWplKKnSBriSzXECE0VTRr6wH4WmtrRi/Hxx8fvYyGjm7AhfgjBxgBU521hiYXIHXRjDFn13AsiVrvnidkYY7QYCqu29vKyUJbkzTv61QzdWsq5biMoLh8juhkpmVbA4hSeT9l+R3FAnHYg8uk5stuwttJa9egLixaV27ebSYobSGdhIw==,iv:E8n3wGnrjvgFHdT5vA0ExQ49fvyam9Il7CM2gnvTmGc=,tag:44SnIhNSei7jjIqR/8r+Rg==,type:str]
    known_hosts: ENC[AES256_GCM,data:rf+oAnnTX6/BLvKm/OcQnlOWpYagjEddqqMhcp6+XQfVS4NoJQNY1H9MNix3eT75mfzuHKvoBY1GZsqwtgz3d0P3Db3XW8SFUZVcF4wdKhqPW9N7JOL6M+da6WgmsBQR3mOafJw5KZIKeeeZ+L3l+PD911cPp7tpEIw4aHL1/w0mCStVbkWWUp/6+4LKorlqrMHa9SQJ3PCxsYQ2ndx9iOIjcVQVYB/1KTs9,iv:Z/8eJwQp32NiInBj49wtbAHpRkg03w6AvSNrI1EFAmo=,tag:K37liULfIOzliu5QWWTVOg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycGtDWTJueDZlYUIxMjd0
            blZpZjFJTjB3VDdNbkFVUjUrNnFuUUtsaENJCnYySFRXalB4S3J6OXduZXRrRkdz
            U0RPNGc0Wk91YklCVzdJeTZNRWN2TWsKLS0tIG90YTZ2UVo4ZzNsMDd0WGtIWTVQ
            UFprUDNkQ3U5endiR3RZZTcyeDE4UHMKT368ZwyIn4hmP8A+hbJLAZVFXW39aZ97
            xw2bm/8tXfsYR8w8OjJFyAw5DrlO8HpWXaJqKBJFGCKaUsXcLpZ94g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T16:17:44Z"
    mac: ENC[AES256_GCM,data:lFNeNUwwoNCT16/78aVAPUus60UciCYr+o7TS0bvofRMdNrfk/gwQJgRS5dM7mZdK6NGZC25NLl50QMsrkV7yk06GzRGwyJvX34DbaqMKh+dgEx/H7EK/kKljUao13t+FkKeJkiL1VSz4rZ3p9CHAfqyLz0L/pa6RH7HAJwxINs=,iv:kz8Fy1zfxt8kLKe/mqbZgBOfLxH4yjKGBR1wrmrrN2E=,tag:RNd2cPo3e/wv8vJfQrM+6A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
