apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yzx9kZtE9jtFk8m4abU8aBI9D+ie6Nw4enzvAbQIQAiIE4nHQUkhTd5ZJYc2JuFp4yyIvk7zK+RTf6LLyX/gi1Tunn7+v2J2ddRNaq4+8DW5jaEU3mbJbVmIyLe4oJciUhsbumeR1DtN9jlo9706B/9dZsnwh+2bevGohoz9rRWQTkd3DneSF9iWrDFLTe5NuKNOSuV4ENHEvoCxJTllVaWQH6VUfshGnuuaLxGDROVtqu29HBvrUHyvx+u3LI+lJY7Rw8ca/26OSUiItaLZNH6upCVwhWbWmiooiUxwBQhbGX7JYFvW5IRod+b/0rcDD7bPeY6rDa6Nfr9HPAg2bfFtww8A1gyq5cSDmm1SFyDsPKBupTIYYrlz70ELuM51,iv:vN/ohOjfSk21wbxRnWNEik9nwmOdnhlPFieUrk0uzHo=,tag:4vY6DgmzZ+r9D6C9czxlMQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:vO+8LKzlEajlD1PKmXeYdF2OgGW1aL78NVfxQt8Yl8I99D19c/kzyexGwx5ezrSkVu/xdkZxGLylYTYTq+d7GqcmXxMV3sx097WXRWQrbglMlaUfELFl/bQffSruIxJAKF8yFPMleRsdmxeyWzXwSWw06GAQXnl45kYmaCqm93XJ7R1tyvRI7scpc/Bre5DwUnjXWRmyGcIeNHA/HJAdPzimEkgXl1BTQkIeLv9gfT0ysmQSblkjZ6SOEXM26/au4wK2L6nA60hajZHG4Q==,iv:h8E5E9sTG+lyvotypUyJXk/3j+bhMVnvn6gfF/dfqw0=,tag:I6V7sSQL3/Pz1CVkX1NyrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:i7oZ7GiBurNQk7V8U/wmQjbHBW4tWKz6Lef9qgmIvN1lHeYpiv1fXATAaqxaTIsVHg+yR3CcfKcxqWPz2pbwWUULs6fsRDSz0MOMYiLiWfLwYV6/ZnbTjT2Z6cKeRJix91tjb3/XKkUw7BWw3QVcVeJYN+3VCn0tmQ+JTGqGxP3+ybMC1bNKktYou/pOrj7kfOhR1VqlI5NBt+z0mkEDwZvj/tGQe9eS+rRM,iv:pBKh9NAKloUF9SR7kLrAuKjs0nUU38wMGIesLr0aSQQ=,tag:l4OvvdxIu682N3Z8odqwPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWEwzT3NHUVhQN1liU2d5
            cThwT3NWa3ZkaVZKcS9UbTdQUHhXN0gwMldJClR6MjJYY2JsWjQ0eXdadmtEQVpv
            eWNqUmxobEdsaWt1MkpvSGFKUUE5SmcKLS0tIHFmWjQ2dW52WkJzUFFJQzlPekJq
            cnJHdmFkVzNGejNPSXNoVkhLTmc3bEUKwv17MyqQsoR0mVi693FST/ucHt06MfjI
            bnYRSTL5CyNJ1xiNfpzRqgHYSvSyKzqwiUxd0BD3zpCoA2jqTjK/Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T00:30:32Z"
    mac: ENC[AES256_GCM,data:RZ1yT0uZsOy4RMPIqgjz9PBIWJinkLGxDQja6RS/Gz7biMBfbRkmMq3kRscYxmYfpnYHok/4tuQEdRxaEUNLe80lkFiJligU4wjz9Ey3bTaG3z9cosMm+deH58ScLuLzI2BY1Nw6oa31H0i8/pNareLNY0x2O42vQVG20JdPsIk=,iv:QFL8ddPx1T6pCjx0FQfAg3Sp9NHv2mJsvS8FtZ1Mvtk=,tag:LWn4i4uM2J9geDWewF6ycQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
