apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AzyobqCAFcSQXlI6h3gOO/cW2gASPzEw0SdHu/E7B9CDcMtaSTEh52LSrBqDW5B0hNq2SFIfobh4dAqu3dkQ/Ua8ShT+8AzBpPN/znQdan6N96yxht3mLyPnip7B/w5QtPXv1EDX74Jby6nFBjn18Wmlxnh1cMClDE5mR5IBqw1gbzcpunUsF/o95P4Hbh7epTFduBEtYfb30qN76CwJ8kVuQpG8fdraJAWyn1IoNjwvsjSJ19xU6hIyMeruM69FAyzU52FDDlsz6TBNrmGFSzbhVR9Ke3gSUmC1cTQ0jWh3Y1DHPhiNs1/otRSaU64ifml4Ed9wLIsyFtKHbHglwTwNB/Axc78q3jlkOtJJUq9XEYGjPdIcbGitW6Ca7NV3,iv:oXRidO/Z9FT3Ina+d90Zf/Ei7JfT/pGbk/gfoviYM3Q=,tag:+h51k/bS4NWLe68Tpi2p8Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:zsTE5qTFsqSbHsJbc6bLZpos8iAXy433Ktw6dIYWd6IjkRzxR9Q2kPJv2skhU6GtCOGhfb5XEcI51tX7P/LNknbLkVa3UVBcqwUkXH3HU432wfeiiN+pRJ9CEbuKu4Q9mpX0SDdKANJE7Xn1EdPdN3uP8ilBx0bLvqPiHYaQMjn59XRKtQCcYF5omlAwkT/JwJZDHR8BrfSNfOLmIWR2Sz6LYwpsuch/pKkiernEGNIb8w60D5W2HnurUF0BLv+utB5jLFy8DDUX+V7cNQ==,iv:C9eJpf4B7JP7Q0z3Juyk3CW2Ny+86Ov+WP6CHfCqnDc=,tag:k89cgzx1kUTamalbzu/z5Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:XnUekI4oosHHHcT0TcQr6dkZ3lzNMfhD1W+/nTnLpEf0ZY0izuz89ltVZ7dOcQBLkpL0lg/sTiQh/Q+VZbkFhV2LY6MfRyOrGfsPaiIiY59F1Bpwoh3Ly8OVvJ3wMQFnGHWdadi7jwWFuPzZPLG30swmxlL7BuzHe6qG1m6sYmBVqhefa6kYAtXVMFyp/BQq2kcehUHsTpArr6b9za0zxbh11DV9sml8g1+E,iv:uxYP89uYq5VjX5eii+iZhGhBBFaeO9a1y8Z6AYbunbk=,tag:pEekE5NVruNWIkRyHFIOIg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxR3FZZ0xHTTkvYnZKZjM5
            QXZ2ZG5hTlB5dk84N0JySU5leDZJaVBoZVZZCjdDMWtjR1BVK1FIYzl2dTBTSDB0
            TGhlYkJ3alFBblpkKzR0THpRenpqaFEKLS0tIEVLMWtoSHFoNHFSTFNxOVhnYU1v
            OGtzOU9DbEhTcXFDRGFQNTkxZE04NkEKOSWJ3eLSttZfq+mcghkv8LYwPFALEUaI
            HFP/0/dGRUwTV4Gr6CAztxa9a/eMa8ID5KOSDFotiOF9QkIwE0hx7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T14:55:33Z"
    mac: ENC[AES256_GCM,data:iZ414hiNfO9BgA59+vKdLlkiRSBE4txjJfW1PNcwvqXJNr1jad5JO9NO6WxEBAuxHIfQ9mL1oIocbH7n0PWLZxbPz8XmjjRgFIeQ3Oy+zSZTVF6ftv4+cBBMn9r9AxeyT7DEPaYXgxFN/6e814pGf3cx74Nuq2vdxotIbG4qu5M=,iv:mjVlboEtRND/aWCOnlL4AgvFQ9fwQ6LLxKONYBwi0Jo=,tag:v2d+3unhUwxhbGQQuYgE/w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
