apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1yWmS5jEZOx/yHA3yb5qIZRG321QcbZuk5tqd1kJNx0LjkDFAHpr0dMvXlGBP0QuCLfKLUShVXLsFZXi6mKDliLUiX5yWk5hhl1hroxznrm1FFE+fFLDwJrrVR2XUt1A2UKDXbz8WGzGdDUrDhMBTdBmKkKaWZK/78gv8yqG6lc/gz02w7l94+NmfOKp4XASw/2tcs42uadzOktsOx4WP0E9Y+2aHxsfcGxLwyunbIJl2eF8xDSZPlRyLo8BE5YYxdwhvzP9m8SdgbAIKyvvNs4U5z4BR4CyZ3aHbEdK2XByaW50K4IPcut966nEJaQWrKkinbLAfg0NeNNm06SAlNf7wPzmwTIoiXGeyTDxKfRTzAgn0x+DtJMcJssD/asb,iv:bG3VzXmQEABonYs5Xig1iGS5MCUtoxuYPueFFt9iMoc=,tag:vbQr94isxF1fmkYClhs8cw==,type:str]
    identity.pub: ENC[AES256_GCM,data:9+Z1DOnV+3198wSuXn8w1/6NvR0X45axOmmh1vnznRggXP2sIe3oHiM7nSbVeMBNMn3SQ4kCPYWCTYTsv6uEj54sZ6HHgikx20Zv0pfeFPvTlftaSiZ4I4LSm6/72AALtfsX8oOpYURH5aoTeQngIlCvC8iwDPJegY5B1Mu981cE9lc5psyUI77MFRAy1JW7RcL3OeqW/UvuPWeb4kAM9EV3B7p49bdEInU6IysvtHBriJhOm6CNPPqmbLWWvdudEsdnMxP1JF8q0e2BXA==,iv:+2fvKiFhAarWSeo9/FK+cHaehjY1Qi0+2sMieQloyqM=,tag:4norILAAxNSOLtfzztCN5Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:pJPq+OsCFjTfFGFydVImumaFw/PeXLNhZcn6+Vq8z6Tq6/XS8F31qMNlhd66H35BcAxWrLyLlRIykIamF441SSwhUmH9vYgwxmZrPwcpmjbgXEjOCl9VC+OaMoT55po3i5hIcjdMCp/ryroOfv3u1jbvG8RwNgnC4HBnpYNmU6VS21zFuIJ28KrSLvYTFCoRIXRi0ljT+SDrur/baFAtqMyBNOh5ahnHKdV0,iv:Ilc+gR7jCP5dw7myWHndlE4foZNa8EQIF+Nm8BqXHRU=,tag:0sEjQdU5lrJaJpjFT85qPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBock1jQ1NsOWRnc1BVdXVO
            WUlXdGZuUUdsUEtBcjN6cDFIdlpFalNydjNNCnh3dGY2THFwWHcwM0UzcTFWLzdh
            Mm9XV0p2eEM0Vmt5elRJdWxQNDdqTUUKLS0tICtnYStKcEEwQ3U2SXc2M2dUNjBm
            cG54MlQrTXBDRkNaVE5SRmppWVNKbTQKYFbvpNkh5i4KLwlrPxlQWY7o+KlDe8xL
            cAt1UPSAvC72p1lVa+l/no+apLSIsxCQx4ObFY0xcuisbnW7gaPwUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:14:10Z"
    mac: ENC[AES256_GCM,data:kyqd/nE6QBr6MGx4XHFfaODgLWaAJtJ+/LgeqqabVQvD7WyBjmp62kjqRm0+m/42iRmmZuWTt9bnYPpNAUEL0f//23DNvcv5iASzysVcAjsL/BwngotfCu8zF6dTdDbjh2qP2K0UJS5ZZDnsN/ajbddE2PDMskpE5zSfCiWvuGk=,iv:Oi2WMYMrpDvL0hPDKGMiX0ABLlVGHJg6190fURbCUo8=,tag:FLYzSOZCClx3xHgYi2OfoA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
