apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:i2t5Y5BN1zYKsEMYaBYTWeVeEvtSc1IzysuQSX+g/4fe1//VN5hjNPnWe3Xg4EFN9XPi2LIBjWDmtZlu5Q88qI+8b04H0EOGk6Mpk3MQE7gQdl8tcpT5Xvy4mGA6EmH5nCu3U8XbD8ZATf00Xukf157Zkj5uS7ETWM9oGMp7NeLadlxccBHYfeb4M3goeBTPnX9LP2uGqKss4s5ykJEA/ED+d6EcMzPxFp0LgPsCyrd8dm1kTp5LXO+NYBTYWslsyt2VoPV5JiMc3ViiKbh4X0bb7jaFKeqjr05C/G6uW3IAoZxvWF0VY2idPRQrVNnsI/ZM0JDOI3B0RWY05oUWLMyHdYfMhfuGVfpJ+W9PneVpAfkEpWwSAGR1kMiBE4lo,iv:rbTFYMGKwE6LdPWBXufnkR7pLhvr5WkV8nBwqOKUak8=,tag:xk6czfXdHsQEIF+Bea2tsg==,type:str]
    identity.pub: ENC[AES256_GCM,data:izSX0ao4eg85BNh8wYbjZkISqcqQAgc07UATTTtDP9nY7ho7dVShAGPolG6U0v+ptpXOsEEp21Ik1ykqnbSkPKKfq9o0aB4q2OBB57iMZFtBCNePVvhHH5i25q2wNv/l0ICapVfztTOyVqnTN1g9WEPRJaOdC+BeOqAs3boMvCapxJrFw350orzdg9566SrquBx8gHU6Nqtsl5OeubpiA08DkSLIyJtFKPgyJmFB9cS/MY3NFOIzH49Z5qUwlQAS022zOi9VRMKOl9355Q==,iv:jdyY4oNu8+GUzJ7t3VSL1adUSMrpkMuLJ9UCQ72/b0w=,tag:EcSeGuxoxZe4V8/yxzH2tw==,type:str]
    known_hosts: ENC[AES256_GCM,data:oU3wVf1WEmF8RbG521It1GUfjTKdw0ChL3yR7njkn/Xs5ggA3gkD/sZj18BWD1NAS+Gx8Y7bpa6L6R6r81erilmCKZb8a1zL7CkbEVtfww2ZpPQpydVGnPTMrDolop/PDEIU3T/2HxNMUx5tj7tcktBTudfO0LM/tSlmedlGjtWNEgqiqr9LvOSZFU3KVryHihxgY/xkx8rG5kWLOfsbIrnBMSKzftSHMiI7,iv:h7tT9NVgE5ge48dL5IDRy7bb+Mr5mCgAi5mzSvrKIVQ=,tag:7xWop6VL5AHao9jeiE0Wtg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacDhuRi9Kd0VYaEF2d0dw
            QXkzek45RFY3a0ZJK2FPeGE1MDVYS0N6L2dRCllOTEI4K3lRc2l3c3ZDM1UyamtP
            T0tMUnhpZVBvQndTdEF4eCthY2pHSHMKLS0tIHVtUWxtc2k3RXhORW5KWFZLVTNK
            QmpZK2ZMZ1BnR1pJNUZ1dllVMTBOWGMKbAFCFxYRdGR2qY9hsAszNkU/S4s9Yc0q
            E+v0fwURvq8h3+UkxJ6FdqTN/0V/2qHZfQhYTPpTolf5ee/P4M7KBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T04:04:16Z"
    mac: ENC[AES256_GCM,data:6zm0WX7ss6X3caD8qpDbDSUYb+kDrWunHfdYd5Crr+rO3fJE73NnkpOkjk0aFtV/1N6erDoztULyOtQkuuoGbTgcFEts12HZrmkLqoh5fVYT7okiGQb44HkC/didygqhd4fUwAAe95i9TyR1apJBKiL8CUjLcI3nCnplCzTXDoA=,iv:IB+Qd8v61Fe9cjWdhIYiDwlKzuXI5a6u5Qiki33q/Fo=,tag:PO/JcElPtqsVZ1DjCsbYrQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
