apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:q7lqxJaO+PPKzm6QRZCog+tTYYbtM6X36kQVUQNPp+q2Q0vpUMhDV0vKZ359VfK/w/oZ1vA95kGdFulgsSdKDWD7bmP6a006S5xFaGmyyQXefD76hxOv8uz0gud5O4OEFJ/gNfhkrJxnhpVvBdVK+j8wNfRt/Y46j4XpdHI5pgnGlLdwvhEg5HPsahfapyjMDmkgNTMF1fuWAliGQrrtxFVZrdVd4N51+nhrnO2BIOd5zXevbsE1fkcXwcpVcSveciuaQqYIzafD/vCz2yQyjYwiXuTYOeBVQlg+gLEpIaLDHSTO9IzOjgn0f2S4x8TcDgJ8R/UmVIa1VyGAU2+RndtsuoVV618Rzd/u2wEt0oU7k7yotpBkAzkC4EVfAf+G,iv:Uo5XJrLrH3V8DY98vlwOCSYYUDkuQvvShEJBbeMeccQ=,tag:0KdE25HXTV2sEfkOhyKBLQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:f/VGgC2eFBfaZ9pab2Z8YGJZihr8OgmLjW9OpsggkHg12eFH+Ji3DfG8gqx6J8UzYwYoXJgDXCNmD6VVgQlinAJSR5tQ3rhYO/AIs/D7Yq14PLNF26B8GxH2qC+x730Jje69pM1A+Mock05G3IKkDWTMwjN3XTuvcvSbey3Nx2KE1R/ZTi+HCbs3FuisZ93aZC4htp76+WtHqGGabJD//d3VOivX774YeGcplGn+sNyfw046reUlTeQXQb57zd5pxJjlJm3lC7OPL5q67Q==,iv:0q7IHkfNVcjpAS2btJUusMJKXUPD3QXCLyK5DWo1t3Y=,tag:jfAnEQuFkyw5GRrqYx9LKg==,type:str]
    known_hosts: ENC[AES256_GCM,data:gLRrT5osh4Koh9EYGVkYXEabDKFCFTrUjqbKrnlAhrE+ch5t9KElLPA20XjqX+unzcyXpmKTbHrcqKuBq8Otg1HYExL73pzw/w7foQN/xBiCfl3qz4c14rw5CoeLVFdAZvZFoEf8HpERC4YlxNEYmI9OhdMZlGk5OQyn1eIC4EcPkG69uQxe4W+zT8XtgYElP+cdinVs2PoWEnyJBL3yTsZsVos5s1QJ7N4E,iv:GFrcbvWEE5R4xWpA/zctWunizH8B3Gi2jVe/hWBcrsM=,tag:r83hj2hHcD+4OeysZg2sBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ejZ2MUIwa1h0cnRLSDRi
            YVA0d1Y1REFBUFBrc25aL2NhWjF3UnJjdXlVCmlZZkNiaC9EeVY5OFI5M3ZBWW9k
            VnJ1aDB5a3dpcGp6Z2NHYnZzQkZsb1EKLS0tIDhoR3JPWnBWY0x0Z1FuQ1IwRXRU
            WVpRQnk5SGQ0MFhDM213TkwxcTlMV1UK6Uj4yHh5HtXtXO6CcW0TDr1sjQ4DlARY
            cuzBePJQm5bGQPm2J9gZLu8yYTt6srNJ/X8iCESdShQcI8AzMM9w0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:58:37Z"
    mac: ENC[AES256_GCM,data:sybMfRe3iF72wj22cP+5oDoH/gr8l6NrgQhEHkUY51Znx25uNSKPLya5ixkLjoKqW4PlLdcVr+JQJ8cNriAD0XGQnMV77dUTXFPJLATyvm7UJ4e8Hj+oVisE1yMhPmMK5YVLoZKbAkvetqPep5h+Ak0JaF1eH+wQYzWM5abX04c=,iv:16/QfPOtS8Wd+S8rL6X2HsFzUluejIwoPGUQ0LabSe0=,tag:32tjwl7DzxgZrMKNQvJVLw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
