apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PG5oIZPlzR8VQG0YRtyM35gF/7Ins7lL7OfrM+sA1FCeQZAgKwK80+eHfuxWokRuxYQku1Mo4wgKLoGSVkzLIWRajp2VHTjGYsLJ46tVYm12I9jW1BpDD7ktrx8JNvGgUhrg66OY9GQ5dHM81rntF4kCHZ2mnuUenNsYuHkHx3XeVBJ4prHsbrSjIHgsg/VNPnPVG8d+/bQCxXI3ADsxb4taoY0OUlvCQaYYmJLz0jDiIJ5emzIjgj1IQrc0L+B282BGc+nXxRLOgX3dTjTBeUWDNGSjHT5kmWMrqIMUh2m1MOjlJ3rRYmMJGrT4KzkcjvHBbYqUhdY0F+eL96KFXKT6bkk/BwUj7lD5nOGwJGGA6qwBDgOIG0kaQTT4B+cH,iv:cbRV1W3IzKfj/8Yeo+zM3vADFhFZGkK4I1tXZOQ3gUs=,tag:04FxyyGG5dwMlhki1TDOow==,type:str]
    identity.pub: ENC[AES256_GCM,data:TjasnQ+lNJnhaMzKTHra9gfdkKBqaOL4W7v8xMl4Wl8lllBOCvF7mcHHgoDIkyHeD8VdSjCOMG2rFd0tLgfvzijBKTyOJL2GyMcCkQnUwACIyP5dMXsO5y6mJAVf7uGx8B+Ai9CFNJH+PtFzKfJa5+0bE4+fqLPHDYfYUr8pYujGRRiTtv/awuejGLXbqwxpeWhGfBDZcbbTOeC2A7N26RmuAWzT3aGKXiHUTzGTRslRmMJ3wvNJXk+OlWUKf+V9MJjjiM5TBL2Vh5de3w==,iv:nH6yGrA9C7s9Z5E+jzxSg81D8f60FWpB1uJ1Yfs4kfA=,tag:I2bBEAXLn1RhUbj9d4EL/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:jwSqfwSgnpsLjsDineZwP+JQ4hyDkWqzgn8fm03e2CrWJqxLzmkp0O0cG45aJijPltJoMMbFhHaa0JpYGyJKSkcFYcoc2LiBZnjJZpDphfiVTZo1AbkwR+YJIxN7rKC7wkB4oQQs464DBqGaHyqkQMn6KO4lcWyfV/jNxv5rPhZ9PIOjS4enC1tFsiQbOhc18PCmHkcIRHQCx0zxC7cHmUHK8xM8YFAA4C+w,iv:sTGQOlSPs/aQiiNG67BCFmqOzTfZSopjpcXHeozsFbs=,tag:LK2AqcUd6PrP1IFx1ricjg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcnhGUzZLMWJ5NUl5UmxV
            T1dPUHMwWEtHLytVVjBwTmpIYXJRejBJRFZzCmx4VVZoTXA2bksvemptM1A5UjQz
            UFQvWDVpMGN5OVpSM3hoNFk3ZEZBWW8KLS0tIEpKYjZrNnhuVFRMVzZsZmk3NUs5
            M1FlK1hURm9jNmZZOTBRR3RYcFQ1M3MK2synjaozeJYDGohwdv+/B4SEBg8Uoelb
            KE3clM6knSCThdbi8vaNrFLCsv3MJ1ntWmCh7Gc+y7ol2TSWgpNaDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:25:51Z"
    mac: ENC[AES256_GCM,data:HUNcowq9svJcGexpLPlxSxYvuymwtYLLNBsuG+7lGea1WG7zQyaPPg+MaGn+kGSDIfPvJZbowk98F2Tozw/sL2hxKNEos5hKybUhV/sXmcWLPsDujEZqlqfJXl30vPpPA+JWV8MtAN1kKV+zXttXcv9mM5xZyZ7EYmT2z+obyv0=,iv:nCoKUkjEZsdXjrHYpmK9neTS6Pdwhrfdsz9Sns78wR0=,tag:f5cRlvUTGc9YUOlfM0IvTg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
