apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dZcDitt4OVQuWavo/qLtFch0JuEmU9wuL2CcpdLllqmntf/3fwN4dS9y6AfqF8mbrPXZD4GXHvv0ZyAcNTjrWfJZDIf632UC+plGf0wVwbmoF8yqdOXdNGBQqBP9cvQbRzzKtvN2V0Yy8Bz7rwTGOUzzCc1uSWopQodOY7MVlopLwM20xBzueJ8xT3VznvXXwl1ItyPF/X4ZBjUCBsDLzfseIFWpWVH3Y6TIpjQrg88nxAn6GBXt+InpGaSV2Kg0REptqVVjn6wTrqsdOfXdXG/SdRykVTZMXLdo86Q1MmctptAsgCLUghQy11JY/ADzNsofXoF0sqFHaIhljeBLyD4e6FiQ0aAw9as7RkDwwWN9cFRhjH4vDDLP4hshpYXt,iv:9/cHbNuFOXSs4mA/BZAEDgW4opNOLzzmFbI8TPgnpxs=,tag:9dg8O/M05SjxTSIyKuVmfA==,type:str]
    identity.pub: ENC[AES256_GCM,data:GOYpixEttR+S6ynsL9voFfCFn74qm9xiM+Nk4bL+9iEESJewMTs3JX6wZ7hPpXZhj6246XA2+epDjjCxmP8ggVwW/IR2vmKmwIHTTupbAAEE576UngRwe13zTUiPltI+DHoZlpPK70Qr2JSHLupG3mQ/jOcvBl2w/k1PUQlfOKkuDLDE97z96SbWn5K93ZStl7UY6LDV60gstpNuVsYZVHwEU0mOL3DqHRnOveLlNnAmpbpZ8HwMjTkBpwMOxW4X3dFA0cgxmry1UJ+qnQ==,iv:Vsjm0unxtGatZAkmEYj2ptVviFeWV7LKXzpwWYs0B/4=,tag:EpXAWqpTZ45nwRym9desDQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:nAf9Wt6a7oZVb095zVlwAw+sr9fR8xocc52AbgYN+9oBMmIZTgeMVLnQ9UcS7fKiK+JsQKnWmWxxIxmc6zzcVKWPCLbRIufVsJGpMfHn0K3fVlarAc0yVqvykXQPU/+rGMrpw4rJ1RWtz1DQXBQ2qbxexzMLK0aKMbFAmMSHEL45WcAqSKzyelXdSCUdol8KaBuL6YiQV6PHP7Hsd3RU6feonl2wbXlpkkp3,iv:3PQtAq7WscZ6LL9ifnJEXHQDfO+uFGNJKxxdcLayfzY=,tag:vgjCBK5y9GckQKWjNKgUmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcWkrRVROS3NWaGsxUjNR
            NlQ3OEtIN09lZ3pZdzMrTlB2Z3YwT1dnMUJrCnVBeDA0SXNEYnJSZEc2UG5XbEJy
            WW5UMTdVcklGWk02YUhOMFRzVDFoYWcKLS0tIHZ6UGJobkkzMnhCL3JiRzJ6YmFZ
            UkJJTHd3VFc3UzFhcHFTcUJGL1BYcE0K6bvnaZJC+Q5TQFMEGi9E5geOKyx/Yd/U
            z8bOtXpCt0MkQnK7VYgkP7WKV5wIHGgMGqQR3E0w5fTjTU57JOTd0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:12:26Z"
    mac: ENC[AES256_GCM,data:yq56ilDI+LnKPHAAeVuudYF4LiPD/mqsNVKnLR8i2mZKn6zu1qo+36dWEsOH/ogtS/ArJHhaGUdEt/lQNF6j08/yYkHsF/2nBnZO9D8Hw/RsGbg4/5Xk173K22CpApeLBlT6jqH1IH7D23dfN+00PLIgovz4IaJrBhJh+pR60E8=,iv:H0IYR3eaSBPGn2b/ibPOsgZelmz7+MhZ+LFDguSm3Ro=,tag:+uuC2RLihrsPW/QebJPfEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
