apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FmUeRzQSRY6BcxeWbsZA07TTUo/YEs72EYhq8RfNFRhdrTxOyONnqvCUw0V3S5pG8nY3s2crUj6bPvwG20AmI03YtDMy9b/5QXPpuFw4taz/rVdk5jtIaPoCOFxJWj6SjVbBgEXZmWsSW1zTvCJhybMYHsHdIo17wZSP5jUgA132wBfy1Ohcf2ZFsv2WXJnqa+SNfBPPPOJZbVjAeuAPFnCHs0tbpt9M8fAVQoE6HevGQL8DiHRaaBVzPYUPLgwYQpTiDwA1oxGg7jNL0r0bajoHi3u+Qs8Rz7Q5kEfpZuBGASf7rBfrbnrL1OVJ2pke7FsmOmlaQrWHKg90pVOwbGQ63zV0J5fLJeX6g0o64rdl1ZO8VmtBMiu2r7tJQA5+,iv:xaygXfqbQleidt4mjttAPCtJ6Gev3ZwcUv0QZ/all8A=,tag:PAeBdSsVXe8SuY4CUHJcrQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:JQ6p461wqSTpQY6fKconM+q4xFwhPZeKIRTBOOp/nbIa3jjHi1k1WYxmPEov8HuKe7Nr/qgouzCTWj9rYXsmsvVH2jk3fjbUJrtESNsoiTQ1aMvP9EWGPtDYKweY5Bx63cPT4v5qJKN0wZCCy4MRR3KBXp0UPzihnAbCKB1nlc2jgNdHMFHAaN6Y2Pzgjxnu1NJGBKH+Jf4AG/kUeEZBdxXZDWPQzfklkeBm4AA35hP6j4g3ldFw5hJg8njmZbC/vzbj1p7OdN/OY+sSmQ==,iv:wtuU8vcJvL/bXiMIwMUMIx6jdyMQm/btsrTE/4dunR4=,tag:mf04wSG3KE/VUTjAXtUaLw==,type:str]
    known_hosts: ENC[AES256_GCM,data:vVqPaZVbgo2m9ciM0scupjPtfg0Hr8c5lR4uvmg0d1Y2W+PJIcHnYoN/8otU4KIxperEvjTAEdpOnBkTNKsrSku2vohj38nLAwDxnFBup1GkWcWk1hmghQDgdzY+QTJ9TQur4W5T/v+q7+DBzLJaYmpM0TQFRlqyW6ZbSx4G6XkronHChZ+8QHzlQixkM2FMyy0WCOYzs7TZLxBxhpF2pFFKSiboXN/3e42z,iv:wgQQEmIfHH/gGYxBI5ZvY3acX4U10R1inlB9UF6kTf0=,tag:R+zalGpE1x3OEl9Dp70z1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweWdUNzliREwvQTZ5SVZw
            NnMzVmRMZFdGNUcxVWFJdWNMM1dsT3Bsc1gwCmJSaWxQaW1uRzcraVEzcDEvUWw4
            bDM0aG9RKzJkMFFIMG1YZElibVVVUUkKLS0tIEFEVmdtSVZBcW83QXpQWUFKQ1hs
            NjNoMWprK0JLVlFPTmNBQS9OZ3FWWmMKpp8fP/hk21xQhM45oeT/gh4sl9RkIixo
            BqqCEBt2Kndk8KPEHxZSnSQJkF2dF3g2lOfZuB9FaouHWXqDrqq1jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:22:59Z"
    mac: ENC[AES256_GCM,data:L//cQ1icN0Dk92CibPGfg37TWA5mQYwxcOh+kq6HKlUob8ZDkWDEYUZ64Tw+fwHyGtjQqlAUH0j1q7n6H4F3Pro+FbRAqg2aJq6BLxTubKHmdgUVNp/s2hyvFkT/J/5lQyX/JsKMvz7Ze9MWfG04rbslXhM3dqOtXzYYi2GZ92I=,iv:X23rvmCcoT7K4nEEzOaNy4K7Jrt+j/3lYR609HSGmpU=,tag:Aa1uSu/cGMDiZ5rOkw0zXQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
