apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JqRp6hpGVXlknKDqzb0p/22x+kPSSW6IwZf27jP/7WcI587V1aJfGoPZHNBerQGXl88Ys398aqwHASy0Fcz+67AwotLEHgkWVs24RHHaIjyP8TtA6yBi5ISIcbImyZzhkZtiIgyJCsc62ha8oZAm7rTLoadV0eTPIPfOCX5q3s9rV1s2qgHgbFOTIf7olnDjPS24vo/Ktg5TduaUn382x+pe9jp5wG0eB1YoT4FbAGP5nQRbLgj0ToA8ab+dOrdKugrF6UdvArrz2gzN9vp98jDBxDpZdDusM0KSpWdH/9Tzq7TpB019vlxYIyIKlPwtulz5GZs9raRC3napn4NCH4ABOnJEMIf33hrrC7Xm/dH8V/sBWdOB4F0Xm11nrapp,iv:O6PA9hK9oSn4tfjSPMqv95ptthoLvPQBzDLcUK/48LY=,tag:KYRMNPF24f2ufmuHIEbbYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:MMQyju+ZnenlEkXwgeD48On/hmraXw1pKIJtX4LZof8Rk5i1nPshBlzz1Ps0m73PIbp42FYW+QzHlL5hx7avVQ0DJAcZr/tgVKkhpnCrgFuKwpBa3+KJzpsYGBlw0FK5AW88tGUFXYdytoZ+gbIu6njBgFqBTkEx/eT7/838gydHCCyS7T6uQTjH8DyPJzo51mrNXQ/hVnYJ6ChwAQFWwnDvgGoGGLDnh+WJwNL4Yb4Rzg96pkd7kS0R69agM7XqUI4qA0kq7LL/kojQHw==,iv:pMJ47xMpvJor0DFclidT0P6QtFnXpWwPSgt1iHDofmg=,tag:bMdLYG/PdFw/tWv8wH880A==,type:str]
    known_hosts: ENC[AES256_GCM,data:Zj3nRnRq/5oXl3Tlj2jYmurTajMo/lZri1m6d1HHdKYMUhwVAK95g7yrV9FqYy06xaj/7t9ybQ4LmniwO6f4KLT0lwrNExJEtkPg22lalnXBwEbNebC+gEFghepWI3vHvdIoalXQuqMFjJxTpFz/v0xToiTvrfxFiDQZqUmwwIO+Njv7UJ/AlYxPmzWBe/HTV2UEkcdXdcExu42n0gB8ap576UMuw1R2hIrF,iv:6B+baacLwUAYZQrY2yDdaOWy/DVv8Yk/x+wPWgSlR/8=,tag:kX5d/E8NhUrLTfGNqZpg7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTGhuVWlCdVdNNlRuLzk4
            eWlIdGtQMjVoZjNVcEIvUXBlZjZ6anhFRjBjCkJsbjlOZXAyN1V2ZFE1TTNicFc3
            c1dQOWhxTWlhYm4vNDJ0TjN2bnQweEEKLS0tIGZEcm0xeUhaV1VuZGp4Vm1xTUpM
            MXJydmp1Tmk5U0lzK0c4WEtvTTk3S28KVL7bAkqzJ4VVmKw8/jVauLmY2d/ihJ5b
            F0q4nOe0H65L2Z5y0JryVqH/td666C4t4gExp6Vq3qhW7C221en0yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:33:51Z"
    mac: ENC[AES256_GCM,data:vX+2/sByiRe3JV3LqOR4dNTEUTJzXNkHVaqNl4kLStMptXG94IS87C1p9JBTPMvBN5+BA5RxjYyvB7XAWxI+ykeg1t+VH9vGByJ5CWlfqH51acM8b4GmH3JiC4DR1k1bH6WBZA0M2IJnD5OY3cjFby8PB+E957M1lp2Eo35labg=,iv:QavD5xhxxOrIxsoPiVbigXmF6AEXZao+Qq29syHkkoc=,tag:cRjDwxJpGNABP/QoDY0ICA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
