apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:j25Qtyps/LfkZV0bWasli37hxhy1f1k7cVcKNo5cr2HHh195uK9YlQwlhxCUMTY9lMiq93wjsDucEqTn2SDk8mONk2PxnODXndAqBxWCnBt9mrF8Rj+geenRWlrEqaqA9dHhJCLv563E617hp/LbtBjb/PvkxUhLnwQVEZyKgkP5f2V3wXAdtf+hvX5PYmr6ufoFL9u+ozCV9zNYV0HqpoDeUWPWPCyjZshaAhXNKW25l8jW86wSms6AQAgyZwkTT69zNL3alyFIRlZraU1timxSqvklqx9nw8VKqP69g+R6Si3dI1njlWkwS/vg6fudCeQXDk0t1IhH4NCTx3b1fjlucyYWIo54APGHY20If3y4e0+5QA0dJrqgP0K++Jyl,iv:zQMD60ITI8nGHplPl8y2ciJxZqY7Vgi5JsG+7qzgMM4=,tag:YNFOhPi/v3hd+jjjqzlCGw==,type:str]
    identity.pub: ENC[AES256_GCM,data:OupxmE1Nlb24U5VHIQePVfukdVkQLDkFDiM4k1rpkSRcEZcp53SFg7LSQRNzrmBGuVyAv7glqMZIodnB4I4qOUcmGKSitkebvSoqxyPWTmf87TT7ovidcx+orYWB9XnmkX8+X2IlAn1XWp/GV31BbL/eatK6cUU4ZRErsWiVJ9LlzsScFhACiJuOPLcIV1tKkPloneKYVYQDigI+VVx012kwi03lpLnXvpSukkUgusFWm8v8fge81ZxkhVCdu0q+ooQbWwGCoj0LopKBNA==,iv:49CKw3GHh1APKshXjY1044Zaa/bdIb7OgTkpME9RCCQ=,tag:v+F5d1PPQozhRKaxRFti6Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:+J81U2XGooENOe8ficrIB2hEX6AQPouMN/b4Z0zU1r39qcQmi+wK43OSVD85Sahwz6L42wpeoByDLJ5J9UgvBTXW/iJAKxvrIeT0sybf4fuTw+rRVoFQT9zmzAtvCoL/5Cu8dUTtedPz+vkpUF0f0NXHrv1UDw5TbZfsO0bp3E5eeOnw6U67jckG+BQFRExGlgNF/AAn9+/zJIubhmwvhxc1Vu00sWWIQGHC,iv:crVX/BpamwIiA4pEir3FFjXIpNPr20U/ADRVrv0TY9M=,tag:rGZUxxClc+MVZoIXT6lkUA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VUVWSEdZSHJGY0NWUHlW
            cTFIVnBOMlRZaGM5aHVjNlI0Y1FiYSsyeTB3CmlzK3JjbnY4WnFpS0VYMDNoc3Zh
            dk5MT3M2Y3F1cUZ5dG1UWG1EL05EL3cKLS0tIHo5VjZLTHA5UU5VWStybWFwQ0lj
            SVhFb0h2T3kveEc0N2Y2ckJiWTdVT0kKzlYphZWHgQ6cbFUbe+Ff+F8ekcZkGpz5
            6996PwFP9aAhBxm9bg8L6q5yYyBVZ1teGQIo3ohJ/Ofql2QJz9wPHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:44:23Z"
    mac: ENC[AES256_GCM,data:fzv5FPQ8dPMtivNCxqZWkiXM6NAYMiOgXWVkKcJv7a09OGQalzuf8gY4HffxVWYGU2/0pXbHTU8GGKcAIkvXou8pPYHqhBp1IS73nZOhTPZu00cF1fri2zslyWUbFbdRl135f9dCbvwQoaRp5kso8IlQEenoIsyMqXhBqd/MmeI=,iv:mTaGmCyTM5X0a1HpxiKY5SIxeAZhaRv3dDT09+M0Ydc=,tag:HPgQVk+u/8O87z9ykknwnQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
