apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZXGkifVzzdLSNVB5DnaVl9GA/f+z5yrp6LfHfhMPGfvBpo1z9+QwpOCY0yMWWu9ixoLRWLzabSZKJq+ECNm5fb3qJmE+xDIXwmI1FL3Hrpsd67RhCewnao+1WgjY854D04OqcE7EGkLBPNveWvJhXVjX0/LHTRF3dqpLjM7RVAcMKEF1xtgjwwkQPhf93sc/9VB6IDMvmPFVvhYJ90nDOo+KH73DtXx8y0qQknGeLTsoyXrP3Y4vXoIq7VTbz6qA+OfHDqTnRtibkbUl1w2E0q7kUBUg5wFGmppIo1h6Rhd3w0o4yyW0M/w9ooh/wAhNGSfxv6Mhpa1sXYsMnCGBhk7DB8yw73vg3WM58M6XCzzZvNjQqj2yU3HBVIqOLxEd,iv:ZhuXLgyfW6m87mXYYVjqA4TJFTvPbeMJoBvKluJUa14=,tag:a12a88PwKfJKB1CAsYY1Ng==,type:str]
    identity.pub: ENC[AES256_GCM,data:dNphRI92CwKD3IoMq33zSVbynEVP3cwLpF+1UpIgTsv6fetIhNpUToUco6TiSV36UO5t6Dxqb49uU+fcZTRn0u79b8SpUrw/2Mlqn1dq21hiBW9F3N41TIiKV9EgpmOGVkX4ofe93dLQ8kNxDGGgAmx8tv39YIaegJdVULfCMLWMrd2KhzEo77V9FZIaBOm2gVd7/3bURnBnWU3Y5OPpVBxhWlA10habHyI2rHzgpu3f5M2xtbzaCwY1rTYpvPeBoYxs+qnXh0BfPtR9Qg==,iv:FcXGsuOg7ijeyq5/EZWOoG9gVMoSfq9TqkM3cVG8SNo=,tag:/bonwozIJySUwq0LtXedWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:8KIqz7QEGhT9KRjIRN0QMnC3/KimgNkY75XE+sgJsCMFkGMb0+GfpllEHaNcatt4snvHPKxSgJQx1jhiWyHRUVOb1h/OXjIHhbBzivREiclLbfmKAtXxec2o9TWRydQ/S3VVb3uWyiIYJr12cOt7U2LRzdJrTbthYIlgRmJbdKJgoTY/E4DJzE43YmIwFUETwUdYOi+ieErjuqNe09NQs8hPaSFBKgjZdac+,iv:SO9XeM4pPAel8K/ItHKNK3VHDICo/sfRJvkAfeaI2pA=,tag:ofdsr4/yV+vwWfW/uxragw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkblV6ZEFpVHlTWlRLQXZI
            UVBIVmxjcnJTRmtEZndNdDd2eHdYM0M5NzFnCjFQSWFINk9NZHR1bk1lSmpzSjRu
            MFdDVzlHdFd4ZlhKTTNoVXV5ZWNnNE0KLS0tIEtLNGdCcXpmMFBPSEJrVC9DbG0w
            MmlBbSt1NWdYZXNQMHkrZGJ2YmFGdTAKwhqZ3GJKDeU4RuU6JIXYRbGSvtPU7bDu
            +urB9rXDV9McsC/FVT8OVrmrfsUu2Z2KUVINm0xJJggBBJ5imJdj6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:07:11Z"
    mac: ENC[AES256_GCM,data:YzijMSQcP7ZXD4ezXIFyIA92htzjhwjnymwdaWW26A3qRJPXoJ09f0XzPKtr8bRs7ZEw/uKUvFF8K39IHKd2467nqZIOANw4xP/qvYGKFHN+CiNbb+J2BLGWJH/j6WLCpb7at0ucT792konxXK7wFRt3kc0ktfjox/pRBjUwzlM=,iv:YxC1S5m90L/oUK2aikvlrnbrEpwoI+tOmiqKsA/eTvo=,tag:Y82ocI+XLTKEr8LJoGKquQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
