apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vujutTK3uQOWFi/cL26iFSFFNVJ7KoVVkEtGbQ1v5J6OXlJdF2oIjm1T9eAR2M3B425q1RyRMsDoPpVDqPu8naDi5RB8agAveLz4IiYPFPdQMlxBHltmiNdyYXmrKUdu8O5ODri6iw11YBxIZmzM5P7LLmXXRpwVtj136IldB02zbV0xuzdCLu8tZI5U8XveO4VKsDWMw21io+iLEOp4mjsVbWXx0guWGvSjblJDT67bmSAPtosuGHF7Wc+c38WSBjQakS2t5/1gNnXnRG/f9oPlvj6WwyqnTmL4TXXgMZLhz5VkoBiyBRklbPl2cP7tcQYdN7+jq7dDGNgnytVx6+f8F+NoZqUB7K3Kku/Jgmy550X2j2t1M6KAbt69sSc/,iv:vd491GRU98idGlMpcPi9IdZioFLhd8W3BsBJrSh2kcU=,tag:DC7P4NHQmTGCgbBIa5M7RQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:l7kPEzM+0ZrHvCC7PdIGjCqkw7D91U2YPpE0XLWxHOk1S+E0AiUPPRzxyu1VyF+n47cQ+QKE+tHXhZTtOMaRnuOTZ4aYXt2x5kSUmYXITXOKko7x8E2AbF7N8fyaBzsVGo+qu9/BFbqxASu3/KZJD89fKTDr1ixJmsrZy5gki6MRYc6zVp95CHE+0pitoGXpLZpVEROBx9Cji0ExvYBhV5RVEK9FDhh+BzXcFk2rsbOHUip/CymsggXq1hI6OhYX3u95GcR+aeFMWO6zfg==,iv:JArO6LXv2hxH+g+EXP1q0ZIgne6e/6+JQp8kNW/GJpY=,tag:CvH3+W2uSYZdVr0sxLiMDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:TiVAVRodUWmHUmikPagY7t8caBKFEa0LxAIxmbFenB2b593xNYB/wRboBoUdMjjTmRwPPgUunxb0CV54lL/Nvv3IEpxVF7Hmj9vNJpsQHeriHbqFODg+CrmqSqfvm1EvQrZfYO4t4TMAMYWinf4rH84EiBNdeHEbbpMKWhMCIj+ZDtYxDU0aVYuM5emYE93ghsjEkW7kRRWNY+ihbv/lHaTmEDvzHZnAeMKQ,iv:AJ5mJqmnH7N+vIJ5AfI6ENgE1UfqSc678NKJ2sqQOEI=,tag:rcHq3Dku8jx9Dn3rMvO83Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOWgrWVBycXdodEZFTHJy
            ZWkxcllGMzc0OUkrQmtxNEdKM2d4U2ZldXpnCmFhdytvOHRWYmwxUGxYRE1kcUJG
            ZERpemJ1TFpXOUVnQWFEWnc5aDRYZVUKLS0tIHVLWXJ3ZFdIVWJrRTE2L25WRWpt
            a0xQSTRueVBySWJZRW5iei9keEQwdlkKynQgQ8UKgtyDt23TPtlGa3mziy3bDcdx
            eiK0qOJuaWm12PV9XRZvLVp6L98d0WRY3b0APz1/wErkIKtHIHIOVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:57:13Z"
    mac: ENC[AES256_GCM,data:p6bH2eAo1S27Xz3nfssS4bHUJjYvkB/v7jc8Oka30xZzBpbfT7jzTWhWHRu+kdMaDr60h3MOS1CzbsY7R4gDyczSv728gwYE8FNzvDowHkBcEUXraBltewziUBYwhewEGpgKmPTbwEoghUnIDnq5hiHeW6wV3XMMAhYk3Dhh48g=,iv:io6U4Bu1LcVvK8CCEZlA7hLEr4ZQhghkl3CB5N5k+YI=,tag:jbCKKcRKqGgDTnpm5J6IpA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
