apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/JmVtCEUZUAZe7yVzwXr8F7dIiJs2b4L4/B4C6Xr/y5/RjWpvfIlep3luDaCPl7/V154UIv/MZHL5Q6J4fsfRhqlzQbTReHUZ9IguGoF4GO4WUPpg19SDwaRJTZ8OFD9mPtRKzPCnfRaE16Ay/JEvz5TYOLe/igDsmo6qoo7+JuOpCy9Jz+VABiwN0PjxKh89CwWQPLmN31ZKMbZkiLq2OVlQj3GCIzPXmeHKn3rlT/Hpnmj4E049m7QeLa9u/i7SEEprmvjk4KcXFOuxErxE79xYRh7IF+KQMhYKMVPj7w859jMqQB40Glakn/8Mm/fSWy+944erdrXvqUafYxDeXAl7neXbrvWT1mekAc4N3pJ/OKWCAg9Z18jIJgyRhQT,iv:s8Q1QAnLDPgt3QLtLzPuHxUHyABw2gasJ8Htg2GTafU=,tag:kUF5AZ6V/zMzY/yMrsSwTg==,type:str]
    identity.pub: ENC[AES256_GCM,data:V4KRlzHCQWyURRAncMz4Mbq9SYRJg6Jrh5WkYa0D/LrzgXU5jBOvrH07Veu+0X2KvDKDMfu4WLKltoxM5xp/y/kXDr2x1BEe7TYjE2JcdDg/qEcfUesEO6OZ5r2LVjRnXnKt8DkT2Un9jTWeVEKK4nMkcJbAcpSQ+lgh8wzXyEmJs49Q9hamp1N+RUjXvl5ZcrW3ywqp7ugAq9UrUaWhEpfgq7PLmyZa/3LhctXpbzLsJXwvL3DaiaEjGy62OyFWYIzLzusjxe/XnWCKcQ==,iv:eF2pYXggRPFIAIUzpfG6e2QF1qtfEfoCuRqpFXPrQa0=,tag:ZsjmWI2rnVl0F8KNJKzHgQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:tOxMAVOsbPd/yTKNSe1iULRiVDUxsYMTYTPJFMT7EJVgF6cBl6S52hyQvCaJnDU7bk+bKtj6vAdqK+OY5f/8i/ZSJ+d1Hp4TgBX0dfqo0uYuXPQG5h7syQwPp7Ue3O9NAY7OiVCWavQf1Tu899jXkDE3pg0POveOw8e5a1l8mWwUyj9uqPkO5Uiq2aO+Hn7cXRgygG62AjKh79DjJ1//8d0MafX1zQv4KFLb,iv:9X4SygpqRBKpAUtzNLLib42+AfYU8SQ99spB8v46RiU=,tag:184rBi0FG7K31edidFT3Bw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRnYrb241Q3RGMENVdUNT
            cjR1WCtHNDcxS3FYM3djMUlvQ1VsZWdneUJFCnQzOVpydUROczkyVklQWnRhaHNa
            NjNvSVpGZTNqTmhab0Yvb2FVQVJNYWcKLS0tIHZqaGViOUZ5SkovNDNvcm9EN1l4
            ZDc0M3pZRVcwTWhjL2hWSWxEMzVxOG8KpEjCh+XlO5zmRnQwy3g+saGFZ72nq3pj
            GMeYNQz6BoEy3JP9iAojZsxUb8pcsQCyxAjnhg2A9PxBIxcpFdYfig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:13:15Z"
    mac: ENC[AES256_GCM,data:i6mQI4FaOlrK1VEqt7DutIN6sAxgf8WHDoh3aRGclo39ugu8+/Hdlo4AHcuF/wqPdQOaSmyLC9zpEy0U+srPATn4d3Lo7431tll9oVp8RzfzPOwXCTaktSdtgvMRp+M7upWdNgDpjlOZAV+bYOdV6OmuMRO0pMr9FSlODx083A4=,iv:ZtfZSF8UYL5eIn0WmOnx5Y5761gH4nDY6QaMhe4mPi8=,tag:25yHGx5vAfF7o1ov+HZebA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
