apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:R4NZwUa71ILRS9rMI/a7vCnQU/Pyps4GT4PCSVdD5VbTiiwGuqGdQ8SZ9SOr8qMN1rVS+L970T/18gUgn1kbRVae53gCVy2nXT99GvhxDeHE/6riU+BkthADpDURj3P93lqGUZmCLYXgi8Gq+9wyNcwEr/rSMIq+gXXrQ8NlJKtHCJ/iWJ0/O0IpnBCHQs2tI+gbRSWOeKAow6A3yYjisQ2I+HEgOu5Tw3GYN1w10pyTFsFF5vnHzwGqr7L8xig29ZRBj+d60V5xgxyWVvOvRPH9o/J/tJ9fJC70pIKoZYlAqZzBRPdvLi74sDcMUVaznHZyPB5XA6i3KQAMbdVi3o4L21QmLLmEgytX6zdFlkCAF2DCbeX1r0skoID3ttzH,iv:JoBGcPJYSttPZnptttegx5Kal04q08ihSM/SDYDPRxg=,tag:3Y++DdKa8su1++sJ+TZ9Kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:2vbdEnFE1OJo+W6Bg8nUzcvWYbhBJX2yBx1xZeLlU4Djxij5OJh17B1OhBQuMOAu4A3raohAi+FO8OLycQyDlXUVFmTjvUBEJX6hCXVFPFacaimrmXfvC/1AiLBJDtCxktoZiEo1QTfeDyJzUlbBVOsA4XZAdhH+zDLHZKdnpyvOEiuG3I+QXHOvn/vpLL+I+plth/0cwdnmPzV+lQlht9FqfT4Y3VSgZYAtQ/6CAFlvetP4AfLp1YFXbrYAqNzqPU0jeMTlunjaz81xrQ==,iv:2P/4vudZEF7s369U5eHoQbHdSvjY1a+ep1L7YurLPik=,tag:VAUchWFbVBhGlAQGnxbUiQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:isgppX3LgZir9b+sMrl3P0LZ2SDjZ2fxpXiDgkIyxUR3YcvmvkRSK1FgefNin/OrxVL2AfGIDgwqQBx6ewXLHERgQzq4ZzaRCjZohLl0gpv9pfE7vCl3xMlFHlSQ0onzfeZdTF9qS2VZqKDwW89eepj86UruWS2CGy1CwHwweeRiavsvDAnAgMBDq9CvJ8gl5RjXiJZSxLv/U0Gm2mcDBwPN9UjPJUZ/1/IU,iv:k05zWwCUxdvmaIDHw0aRK/Pz8xnNIpXJw4UkjxWh6ZM=,tag:IoEYDkUS164MqGufnmcwWw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS2lHbUlKd2tvcFZ4WXBo
            WW0rN3VxRnFac2pSODJ4a000SzRJSVdKNnlrCkFoNWs2UGlVVUVZQm9PMXZiSGdG
            MU9XdUZFYm4vclg5RGJWdTB2SEZHeWMKLS0tIFE0NDV3bzh1SUgreFZOS2x0b0NE
            eTRkdGNNWXA3ZE5PaWRtdVhzeU0yZk0KFGu6py7XBCuaZVNjSc8OAJo6J7XJyEhx
            eg7cRlcU/AIPLdyaMvho2agxa4Im7+iW01nQBLOMEgT9SV66R+q8iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:11:19Z"
    mac: ENC[AES256_GCM,data:ssWppdhZrZ3CGg7TSIx8TD9+CU51J3APqk39BP6K8esSg67wZr6l8cV3YSLjMNBBeHwPm9OE6qjO5078/MerpS+y/9ZaIdQQP/6U4ZiQj5rorA+qp/bts1Rna6iWa3GzIAQp2AWvG7hA8RI/ZKTLbsouC9ysKjU/IOriWG9RGoc=,iv:pvCCadzm1v5Q6AMBlJXRcBcvoFMYWsw3BXFvUe5UUow=,tag:KCWMmQvTfVVS4xAEx0meBw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
