apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nJPNHbdYN5O88hEqwnmXfhv5YpXQYdML7NjtfX93WYdL5Moyra8rniu/JYS4B2+qhQYrUhdlB5MZo5xGU6V9IX83wRPG1ZDLhVurWp8QufnDQhY4cZgfuHFH3DP8R29FZ2Rzx8t9pPrJ6DW+085SK6gr65mM4T1tzE0rjhpInV+H3SEcHyGwPSYx+0tWdrcTFUpJ9UQdEZ3Z9CDTn5vzZo6xrQpPrYxfNiKV8HaPOMbqtQ9iATlp3yh48J26SIn4hwhQrU4xkeIAYMMzpEscCwF39p2x+BHWa6UftXbB2J9jnAF0lXEDdtmS/6pzFzc7m6bS44elyVc2HqZ84y1MOkIGiPumZ8shZr9JzOoqChqeGOPn6LDCEvU133Ymqhfe,iv:baCAdI6UjR7mKJMTi9gzX/271FYyS3Tb3uxM11fq2xg=,tag:IogdEadzHEE4jf0LLnwrNg==,type:str]
    identity.pub: ENC[AES256_GCM,data:elLVsLF5+bQrTS0VOMSsikxUfDayjZ8nQQmOZlb8NqeLf0f20KwEaTH2UQdh6cWulywuq2k2gjaXLrKpj8s208n0tnDi2pEoxPZJKCTyCVnB1I5tZmjXs4e++DGSQDdDtWq35BW5Sgm2VosZhREcnCZ9mOFkpCIeUoOFGLbuzcZbg/Zknghqtf/BpvCvd//oAHmKJXsP3gbF/xvrFaLdhDpXl9g75p6E7aMb/O5dnG7aaPAE2Gk4UWSSL8hV2EQBFf3re+TnZTK5+GlbZw==,iv:oDPIwx6KpW8L72BvrrzKtpWPYeBV6JmMUFxb70y3+bw=,tag:L6vKPIRmPREFcNFP0huNgg==,type:str]
    known_hosts: ENC[AES256_GCM,data:2juKRRepnEHFDt/rAEW9v0L4wlSkJRZguw7R3ygyPmsRfLb/BRdLPlmVGmhxOM2axUwBEG98tZI9y5H1AkUCc2K/vYu6r9oxEPT8ROTIT/053UBaYhEFk7PAwN9538Iia8BF9z5h8ktkNnpZTkPwm8HZEFI2YYIQmiedSuf6h65t+EfXLVfoecbK+JSQFLJHwEoYiy91njvkvZ01bfRYdV4z+FYLZmSCNZcC,iv:/yabylRrI6kRgx26UIETUbWD1uzDYQ2oz8fuusU7+PM=,tag:6iQyB0+DbECI28Mt9oeKmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY2V1bGtKMEllb1RjRisv
            YmxPdFFPZXBrU0NiTjV0MkVDV0lmdFcxQmh3CnZoL3U1Q1J4bTlBbHBjMGJ0cy9l
            QXdtNC9OcUJla1EzZGFVMUoyMG03ZVkKLS0tIGhpQ1d5VUhiUDdoZFpBRDZqYWJs
            VnI0akJyUFhkb1l1VTZNblZneFd5aW8K0IluNmP+S2WtyiP28rumvsL4AYkP53W8
            sgQDSYYV72hNxQhvFfEiq6svQY/myTHrYHZ5lo3YNGevSCOWhnk3dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:21:11Z"
    mac: ENC[AES256_GCM,data:DWYaLGXib0xresk/ZBw80ok48ozn5gq9ZaTamn/Pni5yrB1CyUIIBUu1e3mkx4xL6ruI7OB+CAY02jDtaDy7VjWVTqmzradYSJK5EFP++xpObqYsWeYf33MPgyVOEjgcLRfwJthgXr7kYMsiZnXFZDnYayLFXw+CGEi9WVzwmeM=,iv:JdgdcuiAe4v+vtsBVPrwByHKBkm4FpAoIdbmpBYBHIA=,tag:dL8ZkZ76WD+eb1MFg1bZzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
