apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5HeExFf4cfKSFXaNetAhoRB0xC+aYueCvgOtGRSzP53ZGU+siYtvQVoaLwA60gQXJ57Qdlr3SHMw7Cd5HgigCHQrnCox2ouF15zXLXbvr6BJGcC+UEfHpr6iA2nEKUZkrmcW6V52xsD9KhkX2h5dvt1mrkyj8ftfeWTI1UQmfqbAtawMd/SkwF0yQv2PjA9KwQT6CYLywy/VVdXBEHK9GF6N33WPKBxudZ6Hpn5Xr1ybH5fSzNUP5dN1VQfigW0kVtXfn2Eqx6FEIf+EbNYxOkWJOEq61nT+VuYcMktaCVb78YSFcuVLqGCAjtlY7LLao83EByTkRutj2TUfY2WjidYLYrfzktbpMK2PIaLcwwp5Dmgl56awK2AusDhtrCEU,iv:RxWcaSG8Ou4LoUl9bKFlERlXrGjdeChJ4xO8czOed7U=,tag:ShmV4lcbm9aviioHQlAoHw==,type:str]
    identity.pub: ENC[AES256_GCM,data:XvCQGe+Ic+S2jw2IX5DwrV68Ss7pWDujjrhlWOFSr5dTC5uKpz3cw8zEUoZTXPWU42y/H9uMfOTsRwe+Td8idv1q/SCpzB0m0P9j2gHNuaX4WY/XMAyS8fiK95SVF4/1ruR7VhyMfBjomI36lF+UXvLZW/cRx04udUGYDn++tHCFasmYCDROoghW3X/Dxohlq19VP/mruuCxS2I2RAEAjRXLTpuVSTw0I1rpZB97hTxy9GYG6z7miZE8VrtDp3FsbfFhR6GK7j2BOLs3ZQ==,iv:h7u3qTlGnfjhLfP+R4cWj1TFbOdm9lSYKd6VN1WgW04=,tag:T0jNWQ1kDHlq7Rmew2mFJw==,type:str]
    known_hosts: ENC[AES256_GCM,data:H2oETDorTpwUXHzfDelx5ypI2BMwHbzzapQBEeAJBFw8PQFm9JZDJ+cuPsaqY8NM8vfVOPNpd2wEtn0OU4zUACz0omgjDhCnKg+YaB0fG5ClTaoJAP02zXmcCD9WrOGwQCazX8IxvQSCvUHjZSgkXq399wykyFgDxNeTxtHREbLoZOdyDK/qr8tvO1SsAPTdFigA6AfO1jSW+y6W2LE7X4t/4WZw9paZLfGr,iv:ZvVZ7Wwx8pG/uijPR3jq5oJXi4wZ7xaXEIgngjdNDuQ=,tag:EGrMOYBWXvtBdKoTaTstUQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS3lxdUtpSmNXeWRDSzJN
            TjEzNC9SZTcvQitDRkZ4SVNIbU1rdlVVYmxvCmlndmd5YndPZFIzQWdBZG9XUXFm
            R3dNK0E4TVZhYXFKdm0vcjZqOUdNUE0KLS0tIDc3elZLeEpzWlBqT2ozbDFVVmRB
            ZFlPT29ZK1dyZlBuMnVtSFR3Z1RiUTgKG0FJX4Cfy0zN+KtUm/0tTk6honqaPYmP
            UrL5AgPWbWPRDiUNRWX6UIySPkzV1iBeUKqYxwxY4B04ALOtrb9Xqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:38:07Z"
    mac: ENC[AES256_GCM,data:MYB4nIV87oqmr2ngyXjMzfaf8i+EucZOeeF8CaCeBM9+m+eEjqLL0dy9S5ndy3hSwBeb53jFvizbCpjwhwL4DvwxFaTLi8l08YlrkjfkpfeHeR2oK4K1vA51+pXoxCdhxpedRxWcSTeX3rF5+sjTwaMzCC66zrckt+vYv7plybQ=,iv:XttG5hW+4deAkHLATthjQ99dI6sIRlY+ioJlG9C5LRQ=,tag:w5xBuyQ5molzU8qpRMpckg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
