apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EIKn/vQnwHBm8XtXn+pxIntEFthxhgZF3263K//X/TragPLej0GnDS3eR29U77+0pPM0l3oAlz02uT3gHJUI8Q9y/Q1wfjdOHNaShMCoamjkopdh6vc7MotWfnwPWSZMVbr9rJSWe7hzaLMUTpEEmat0+hF/rPE3Ji5c78+bjRsLGjGvrqTygcPkAdxVczBnNN2NoFrmd/ipVSOW8NYB1EZYDWuP1nTM5MY8lTsP7WvNOgxZObDQKk/g8UWDiFGQ9Sh8ZWDryBhwMaUlwiQvZ2MvDLN6OsN6HijGrnDO/Xk383vB7IwscvHC5yIIgYZGm41o5Ru0JwcGFJNPbuPnhjY1dJpC6xGjptNYiH1SIJrJjPxaFQLxM8Nxxz1q5l0Y,iv:TwEooKvyKBe4naMCvXsGDnsj9VIn/32S++kBVDvk5uI=,tag:oNTe9wRd+N1OVAFdcsFmNQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:aANBvg2cj7fTzNxg98+lGZlPAyNbsH34O8PMF2a7fpcNZgpX4ezuI81kvrW8bl/tKCFfQoP1/k2m4eKlQa8qnpIV6t6vwNhcwmpuatlMBMTJdx8IfBNCzikplI77sk9Hiq2TQmJDWA3Rnnr75wTqR9B8Dq+E3CkqhWtz7hM9CpcGc3HrMheNMpKJgAuIJDQhmPipfSv07mIohMp89RsWgWOqAcAnv/Bt+kbKdDajxk2hjKFBIZCRPAGKNZ/c+vIW36b5C2KagDY02eK/ng==,iv:ME9IKy50O9nmB/sEmp8+Bh3gnnqQtpbIBW1wEG0tF1U=,tag:gJmD0ixQuPS9B7QKYNR6IA==,type:str]
    known_hosts: ENC[AES256_GCM,data:LXpyTn7pxbyFmDhH8eg63LyGQtZu+dsvdfQosydrrD8Y6p4ceMRFLsxpz8DvqUfoEW9fc7t6rei3gP6p8z5ihxWYSj97jhKjU7xav5uR4Cm5hu6a3DTllSo3qNWgrs6r4LOjxWqqlIBBP2bhYWT4+QcUsuJiynNoT1hi9BzbjJd5vhiwIJOPZI5bgOnK/G8tVBgVUT0DUkWp5VSu3tBTwvTM1aX34HfiXLkM,iv:XPeTDTyELh23Mz5ms8OwGq3HTddwwhQ5Ndo5MRzZfZs=,tag:cjUBi5uwrne5XHqIP/JMwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SU45RktwYWt1ZnJDRjB5
            WjhHTHBuVWVmQlBpdkxrMlZLSEY2ZU84c2wwCjU2WG5RaE56SC9kYmhPUUFZaVhK
            b2o5OFEwMVZQbVljMVZkZndXWDA4OXMKLS0tIHh2WWdFZC9nVW01RS9MY0xqYlhZ
            T0RTeUdpQkNXVmZ5bFR1Tm9vazMya0UKpmQRI4nWSv4R4RMu/BDgZwazOVwt30TG
            COlq2Og/HUhjUf/s/z7VfiO3Ps2vXZ/l6b9BuSUyAWK+cXvN1nZJtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:24:53Z"
    mac: ENC[AES256_GCM,data:oor0xng4J9LGHusEh6VcFAZIlUel8fjQcIf6yLzrUX2IXepyaJ1uY1ImIG2gfCsUXb+And9Ssjc3+Zn522h57wicsioMiu7UTusX/wU8iKEBcX2RlSRhJ0c0h/meryeXaUGEYIjBdMeoptIVdUvv1DmoHFT7J/6zHNkZYQ8rL7c=,iv:e1SgbRB6pModVsp/qai+End+vN/HOER+8Q6+4AVCpYc=,tag:NUtTtTt2DQY9fkvxZiB8aQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
