apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/zruclx2LFFYeC2fIDJAZC60IJy29BvmuMvBehtz8t5IJbXuke9mTOjoIRrJTXJ40IdTQS6W+qoxQpPxtZoWF5WMPIVynrmP3mBQZSeogKjA2zA6vtNpuUX/6Kw32nIMJas+lzMD8ZDcf4Z3Q69aCdksaRbDfSyh8LUw6w5uMI8zNAQHBKMCuAMUyPeZPPEkUPdhjays+LFuAxICuZPaptbMS+1dRNjF4vZjpVK50p+slEejJICiNS3uc6vY95xts+8UIazZkwsgHvIDE0cSdOruk4Md+W6ZCXBCgTAilbzJ1V8SKA3mD9gqQOwnrPd17tKajBRrbl4v43VqBSugs08Go4cSCSJ0Inhff7ANZfAUvz5Hx6QBUoHUgBmel1AB,iv:aV7KVGWqcK4chxVUoY5AkurDzudFK3FjRu2HVyercDU=,tag:4tMQDAHotguWMMY0cQB5Ow==,type:str]
    identity.pub: ENC[AES256_GCM,data:Qa3hTJCoTlA8rIfjxuIWuQc/znF20Ppbm/VtZRx0IilW3i477ZMAeG9pUllUD9wl3Ix1+fNQwXZjiJCpNtJy4/9SsjCBncPVqwwol6M8HBZkUrjI3JQ/2QDxJDjyOrFc4cuyxafbLuZVmniJ306CZu6cGbEbDbKsAzzmZTkRqLpl3MP3WueBuC2q+WZXcsaxAipno9Q0QOTcdjMnf+GTjBwH5oPci3y7TW2b1FrAt6Ouv+XUaBYSOwVN/ziCjA2MTi/MEX2yWU7hA5ZIng==,iv:QsWrPwn8rDBLGGIGlueRDVRhh/P4dRFR2McJFzHy+6Y=,tag:FSoHgVSRtJWrdkpgTpo9og==,type:str]
    known_hosts: ENC[AES256_GCM,data:KjnFIHa7gl/9/ItunNfnBIvGEJK9X4s7otChUB0A7nij+LakHgV0Gq/NcFRNSFb83kZr+/A2jOWkxsH4ubOzbeXLEAUm08T+HIbdi7m1MT0XD70zG0ajv/86ZBK6tZXlDyxtSvnGYAMvzbhaIdD1sTWpB8J0nmpxd+NmqgiEm5xk6RdzMHYYZQ+gUEte+TcpCGW2nTEaG9XOyuzTTnpWkdE8Ggqjvf8yLudA,iv:3vtoF2uY9Dd/Y62XLJNH3JkkfmBt9X11okvSqRs1wjQ=,tag:vc9krCF7xjY5/Pon6sqKRA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNWRxRDR0Ukx5RFJYTHVF
            cFErV2c4VDgzSC9IQXh0MGZqMnV3OHcveURNCjhEU0w2aC9tNE1wVU1UNldKRUdq
            Z0d6bDd0RTNJVEdPTEZ0Y25ZbzBMR28KLS0tIFlQT2F3VFZGS1VlRlF3blBNb1NB
            S0NQU0Eyc004c09UV3ZnY2ZPc3k0UVkKPvHmnDwSWnv2X//m+/soMgpa/NOt2Iyy
            JOs/3vcXOxTBR7aT4npjYNMiwtzIAUzfS+RAvo9MeBES49GS3JCrUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T06:07:59Z"
    mac: ENC[AES256_GCM,data:+0rca4Kxf71Qj7lpQ+DoUizG2UIjqOWetxeWiRuJyAeseQBZ7LR9kFHUvPn2/j6Z49oA0NLUREhY9zq18dW3CC4AadKA0o8mBAlVDzl5p7Of4fUMEIa8+i9DonU5N9VkSakzEFqGUG6JF6nCRfhLiiDCaCq2WL2GRT9r/tKcEp8=,iv:xlASXuHUPa02HYBFa3k+UQk7IbPH1zkbeNakJmBFvGw=,tag:sSvFbx0+FWdE3Yu1arF70g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
