apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:abepJbMvPML3VDb3PL54Iswfz+lb3cXb3zcPl6eEh/EIzxkFJygyzYhjBlMdjLVq536APpYhfCIymguyJT37WBxjgJG3tfp9I24RPDvC/Sft/rIajONq7iziJUbzEz/RszQKn2wK/ShliWurxduIIpYIl0BWe6N8ZeQuQPbl0TW2oFBBgYfp43/sdU0UgRQ+Ow5R6g790QqbjVEEP0ukOhhwFp9zp2Apav0/d2xwYZpbdY+bhajeNVBnjw91izdPDmuFLiIEYNnpl7CdO9TAETk/mmVsQFoXf61xGkvHMqYrVDowT1QUjTqdt/TW9jjgUho4XZzTuVqHZogltG2c6wRmCZ1qlvEufmrMUB+iNpm7ungef0wuk5tTbHUoXIvs,iv:tpVeYTS9izFZbgVf9Ly9rc21JT5t0eEJLcp2cDwJ8NA=,tag:cB2Plyf6c/AmX2j8qcJJog==,type:str]
    identity.pub: ENC[AES256_GCM,data:F4oVWkF0Ap1JgI7t2MMYHEgku9/iI+mar+d284eWhXAVKILOW4/OSTuPxJAN+GPUm0ZaLoZ65Ol0fWUfPzrW7jj7a8NLKzNMB2dJmgqbGBXeVOvX1gYGrV3z7tdghD4fYQlzCZOAAx1aelEmskffdOIKRN7/JN/x0x1BjMG8tyQ5dOoNW6xd6FfQM40DfPbn1gjP4dktPy8JgggonnHleC7Is0dFZ1SDjSuOMkd56kl5D7hPocybl4VRosD8wLiFGWeggDi2J8WUWJjKqA==,iv:lxzr3wTTI99sTBHabriAIriAwwG42ngy0WleBnLxuN8=,tag:4R6KupfyOplMzoPENWYSTQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:kU/H0/tabm6iZ3jxZ9uYzOKFTFZBEpG5L97/+TFGvJSUedPGuQSOVKntJ2rhL8Ow/hsUmMGGTsMhYznCUsTzfVR2TKb/7Ixurjegq8fNyn57fHhX7wM5+61JkiYF/eij9/PDF01PVTJcq3HU/3m1h41LZhdZ+5pxWTn67hEXjfonrec4AWIfHKfqpeMyHlOEpobeQ4qekAVAYXb4w26PvF91lSLigDrdT+Po,iv:4QAlvVyUBKiuJkTxiFamxDzNcx0U+NbTPSGp2jKf2k0=,tag:ta7HWkA4sqhjX3mkldRVeg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV1h6VTBMVldiOU5pZGxq
            d0VEVituY3ZjT2wwR3pCeldVeVpoTGRWRVNvCnF1SDJpMFFzcTVKczJkbzV1d1gx
            em9ZTEk0MUxsVEdwdGd3aEM0cUpRTXcKLS0tIGhqOVFwQTJLTlBscTlpNzdHMTFp
            c2NwMXlHc2RXS2ZFWmpsUWJFaTFrc2cKRJ5ZjgWLw7+3pIIsaiuT+csEhoJElSUx
            ysSIDsEIal4RKHkDj7Utfiy2qQL/td080oNFzvXB0GUBgT3a6yj/+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:35:21Z"
    mac: ENC[AES256_GCM,data:34gxdwap6/xdLJuj0B1bJLXncJt97xW5mEvV7jW6IovY2JDqwKale1YEUyxLq+3nrMba2r3p2GC2++WqTXMGjBtLcu/dtr+SAWXSjWtpGPNNB5zxktWDvt6/UZ9agFccrel/DDjil7tytsfSgDJV3KJQnAP67bxZcFGtrxBrqHU=,iv:Jz6MnlTWYhLvHqMpInLNxcsXU2yD2B5zySrrA7ND/Vc=,tag:lb/6waMbGefj/+a9txXxHg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
