apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hNXm78F+aP5CYfEMOTaGtuI44hg0BzMh8rkEN1SOBmXbSmwoCEC3JmZPIHLdhtxNT4EJSI6MXtjLjljO4LQLa9TG4V+r6gOypWvKq+ecuU2/YwLwobUmrHXO/wn1XAmLpffm8WFMyDZvgYsyP5qX1iW7dCsJm6ZI4pKBDgfEWJM5Oy1I9QSNI6KfFdlWxrIj/UaMYu0Ss+eTCQDIZyGLT/j+EK0F/ASXjphtdnQLZSDJ3/pU5rSBsntNs5fw9Y3PKPFGmJ+u5QAMAr5bIB1X/N/ThpfX9UIU9hNm8wFHz2MoIZwOVkEEj3uSvlyQOuKjOI1EqpPsmSStz50uXAihi+Xa2gNl+Hxo4RjTYH84yngKegTIzbrAP5ICCuUtnQVS,iv:SR+N9D893er7naoU4+k3MbbS25l4l+B//KYJujpzBTs=,tag:U7E8CQ8Nd0DtvTMBO232/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:ue7L4yoSZCpeiccj6+uZ+G8RVluW7PyuK9mlb4jiEuqbmJV8Hs2p7aVggwPVB4aS6TjxD6wrzzTvlaMRlDcFTPWF8UNDALM7t9OsW194V3u1gEb4y7ezV53EpqGKtABduCfm7pb8DF27NNAqYmw2elos2M5G4E4xdGXXDCuQSg3k33rzNxwMfKqb73dmRsl5Btl4EwWJHBRg+AwIKaMgz68ekPHPFNrwXfgJuJTihgFARVtGH7X37zSdtKhkv8IB4GpIoin4jAiDAHBQMQ==,iv:dzfsdUCjTn1jCDaAgvBeCLuKJBmYCXIdBT1w+pqUZ5g=,tag:FD3q3SYuZuJvNKGqQjpgHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:FxGdybZZshpmNovd/C1SE1IXolpOQ3tMqn5e6Jw3EMWL/MPH/bWxA2Lacc1Hc5DEzIGtCZxXhCptiO7eYvuKOwVqQ0FiILP+4KNFQquqKtZOh8BpWC9jKSBkK+kriJRR1HMCtGglmuAISwlPLnZWX2AWnLZK9zokow8i8+zn3GqrP5bGYMX25CQl11MAnCWPlJ5b9R/Gjn0/Hjv9ChRri6ZuGbnn1n7YD9DK,iv:XLqTLjmQLJbZpDj4FMdE1PRYcpcN70/m39vay5oxsB8=,tag:bolo6oEtt1KWuL36S7qHuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYWtienRSNy9LRFhIMUFs
            UjQrNVUydVlTc1QzSHNid3pzUWJ2YStma2swCm0va3ZJUXM5T1FTWXZCcTFYa0tC
            V3llaitGVlAwcTFqZThabTBrQ2xkbWcKLS0tIHp2czlpRVdXa0duK0dCemttTDBY
            TFpHaFFkN0tnRnYwbkYvUHRLdUI2L0UKPaE7uRunmlA03C1MclH2n4ElNbeXhasA
            22WhGIdd/WGyfFWlsLKNhCkI4m0mv4gkHTclHH5CEKOJPmmJUgTYHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:32:47Z"
    mac: ENC[AES256_GCM,data:H7FW/WJcRbbTMhEutNOm3Dft0DXFtN4jS26BU+HPccqjxa+/yWU00j+rOPdLCDoPVErSb4dlzaa4MU73oS4ykRuuveeEv2OWDDN5pne8C1Gdveg8ch1ZIiaWvxAveMdG44aWRoHoRYzLwGgTv936MYyxkYyaQkjMpRtZl9b1ysM=,iv:xwBesRH/523PnY7UWKRx5oBMUG2yuZUjkpgYDksYwHQ=,tag:Y2sTV/f7/AHrbQJYTnAOkA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
