apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JxzTCMOKPFZhew0QmPhu+abUfXDKrHOH3VwTMWa7vCpDmpCbSSagfHEkGXOSj+NhCpIZUFGS1S7U2LmzVSJ2TfvKJixqy4HQGuLnTOYMykuXd3+PhPf6w0gatdovoRUla6MxwdhO0FZnRmEs751qa8EEvVByQRaNDi5l9ZlPR173H8mIxBSAuf/cUcTEq3erxIDpZzwFVH2y35nFvqSFbiOOX+i5xoioDpvGwLEMGWHFNPOm4le6IKfRSB15gs433cVukWR8d7+rw506Al/pnG6v270Pe66UN6u0SMjHJdkBQuzfugU1Padbd91ipsA9xwf72nsKgxbHC9hhZPPpRlqLgZFENr95L17GAcukFMUogXWt2+QPSwg2kH/dS3o0,iv:jeWrjckfwVWv0wVvCzDJ08FCgcohAdJhEQ9ZI6NeTEw=,tag:FKO0NN3tBm+p+WlfQ9QHpA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8RUOW2emmrEa5BnOkIhHqBe8wHuR0ZMQ5lxnEseWNkvcwcaEoYdoYOEbYrCTDweavQW7KroS0ePuqaRoAqlYXxsbKfv1vhQiEhXckSqa8fkTYLY0pmetileR2j9OhgQXxbih2c8s70eCj80lxAxQ6ft/tllAPdbnS2CuhpRgjnU7UIBdjgE9tgqkbntI7/UW7meyy78qOVDB3J9AIyf8fa43sMqMqwCgJ/BqqGgquQ3TzvnUkgY6XkyahgV+06zOjpTpOYK3Xc+pcazgXg==,iv:BMnOnf87GcoUN8kAZQLpkLe0KqIs2TnEdOlUhiVS9Is=,tag:NqedjZGNRkoaQgdyHg1Fuw==,type:str]
    known_hosts: ENC[AES256_GCM,data:5kCCh5hxRArnvWDl3y7IjNdjZnFqXOwSEAwOvD7g+/+lqABXatVsLyOLmmMpoMqjhkUp+oMvpmgI16gN2d5d/z/gaLM1LvuQp2bdXH7jSycc+yRwtF0FUaMdWUoB9V9oyvJZgklh4j+IecYbQTPtMPaABS6AAH+BHKwNeJGSr1ZTAKfshzAyWVe6Fh/JP4AR8XKseh+9rEW8ivqp2R/UWYtRKce4TySIcUt+,iv:ELUKQdA7+iAWajweC+lhc6IvGK1Wk+oNDnMzSvFGkns=,tag:gLibOegPRv8x4mdVAlC8iQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc2pmMlI5am9FQWJGVVl5
            T1FMNXE4SVZxWnFaVGVYbERvcUltdXRrTnpJCnYvRmV2Z0lhY3VYUFJuT2dWYmZL
            RnJxeENPOTA4TzN0cWl3emxvOEcrM3cKLS0tIHVzdWtXMzE1MmY5MEs1M0oyNWQv
            N0N3Y3EwZklCVXdwTStnQ2FQUENUc0UKSwIRwr9tm35wJMhgYc7mTzArJBf/4cQu
            mjaccQwOnav5k7QTubm1l7jKXAWBItl6iD2+Y5wFb9qSLdyhWxXAMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T23:56:07Z"
    mac: ENC[AES256_GCM,data:XnUsAS99pA5yudVRnX80xSbiYs5cMklRPH4sbiqUHL+4NBtyG++udLMosBT9y2mlO6yYWZKGSFNkUy6JNcJbLWInV6+d6zLMGRiWSfMwClI3oIDOhco2C4EfncAMYGUfjSayP+3Vg2cOMgl+12SitdAJ1sdXAIZcsuS/ZhQTZVg=,iv:owFwMwdnJicGggTWYfHHzVazVGuq3wMELm/5CNrZ2IM=,tag:I3Vj2J2pt3Hb1CMcr7FLGA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
