apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:w5AMh06alttHz/32rwdGugqIOR04OuwicBMrr5T7nZhPVRHR4jraZmUBWdnbuqKUUnFshlsyPk5lwY6JO/wvkhDb7JCT3sLSERZvYjfSP7W6J03AAMukkVWUqJYm2QuEbKLibK38g9q2Ix3YUR7/4eOkPmQf42lHjRlzlQCtYDggpBE6Rf68+ayPVugUJlO0222A8MWIkAs8SUQj8EEOQqibZv8S+6qF7aLx8y2v8VIqoPCfwNTsN2Fjrq4CFBw5b5drCna84WyGFnOuISAOCC0H7KhA9XWKU0SlnCmR47XAjs1ayfPF/VHplsPdSPTYNS/SZ5WXNruUYPLLwQHhfgLp4PDSkwaK8LGKoEbc/Js7/30roCq3C+3XRmvf/86i,iv:U4uwylYEAgTXDUZpCSoIxlS7Ee+lycp1pvjkBL1vzZg=,tag:LoDdnSTVlsT+xSh9fSfJZQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:6FZziSV+ck8gOOdZCm8Wj1noCjAJEVJmaaCCpZbouSHtCSeSL3NDk9+VX3I5eV2F/2IpuamN11lD9LgwgqhSBRR+NpxpCtlBEQ2JfcC9Jn1UV5Awber1yTCyRQ+iSDqskDAyFzo/SV03UW17gf9RkCU/CB8P9z0DlMccmBfzOnCWXUcc/3ull1A78dMa6vDJo2kUo1ukFBkk2fiLqkfQmp6qEbX9xizBZKJOA8tD3rxrj5wMauVQtUx0Y9a3VkWjb/esenKvsc6YrDOjwA==,iv:RvMP5GUK9iCBE4Go8eHT4SBSExbApnq5R0AOyIBQTqY=,tag:MyYckNDYNNIXZvgd831lYg==,type:str]
    known_hosts: ENC[AES256_GCM,data:S34U3bCHrIbckSNQZlqfNzqLqm1ytXOzBBc1nH/zusS7fXDnsf5Scm+1lMK2mSApS4MCkkJnaQfBM2D7ViCMj+J3tFqmP8FnxltAawin4CBKEO2Fl6U1oVjE0s5P//UVNybIAoDqysxN7//PtIXwK0ZP+QBDcmv+W/3VCkaKn62he9nxhK2TB3A4NTRe+CobUgdkLCl6pbFsAwMznfh6iMQv7GyLdmTTAtUU,iv:nWaH2HRUBzlMqWAJbR/FzN4QKG6/mLB/Uinr9hKXcZc=,tag:OY1ej6br/GE/2pdoFAVzow==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTitJbE1NdXpDLzZnUVlC
            dU9ER2gwOGFkSURBWVJONjJseW9NZ2c2QUI4ClVDcTlPam1KcGtYSmc1MlY0Slpz
            WmhUTVEzWTl5ZkloWi8rUGk2cFUzWTQKLS0tIEhlOEl0VHFuQlRPOWhITzJmT2NE
            dXVOM3ZxUnlpZTZXYW5XZHJKTzEyRVEK/2pFOxjl1K71RIMsPci7tMNfHkAsLFIo
            yqLqX3dvA/qYG4GHxzJWBZDoTQ4bMuiglOy9zdXwJhw8LEgm3DY2mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:58:57Z"
    mac: ENC[AES256_GCM,data:zaMl+wzbxtQRtr5HkCdITrZ4O3to7xfdGTxBBKW5mTkA3e8TpFSXAgGD+uGCVSyDiUZiZHQXg1wTztBrr0XDZr8PDSKCyppS3D0efQUCCU+hOhptlg8lQFNDkEp52OfoODAlD3fxzbXRrbauafg/HEJepL7wX98W3ZVcnX+HhMo=,iv:cXB3LYvBTjnFG42Gp3z9ntlWy0IDfD1GtRjogMvjqz0=,tag:WV9r6ly1t9ijasGhmvL0oA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
