apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kAvAjedA3WEh37482n29LdwghtRWxOK9+I7cSwAfz9qI2mJZg+8+qRsxd6Iu011kGNqHtIn7EJ2bcD8RW+BucYq1aGkbW4Tin6+TRInRZyp3Ua30uai64q/vIjjkeA+xONPCkEFYw89Owj89lamPHdr223un2KtVAUnFj42SXQfpSkCdT6JsXcrP5XE/cMYm5PiKK84Y89GeElifXDuZuHIMvFQHdc2hGK/pmJ7y2oAe6TZhhUeMgXwB2WPydQcKNUN/bMQE+0sNxtMFW70bhaLSdmvfFdus/paK0aZim4d4+gpXorRBOgE2xeF183YJ6Q5g2LahL3mdSPoHvpj0G5SjnIdcQ+RsXPdutuHjkUlQaU8wEdz4pVFW+11ntD14,iv:bl1VF3v5+cpZseKK83DZDOxGdTlapA/TIe1VTvKyX5U=,tag:kWapHD5t3K40XQu7/rwANA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Pky+LP3NS0tMYyRa8CZ6xgWrJZ8AlfL3J1PHSRYjKVzXYfE6TVbusxmr+45ELzv7NTZsr2SPr6UftnFbdVc6B/iErTmICcY6ibWOfVCjiNYzLMz1rfOHxPurDeUZTbcRJcNSfyRQbFDn4LwIdbEki5+7CbfsRLW723WKAETzeCP/xD/2vPzKQEK7ziY94vhXa5+DAFlwhg6Mx+hRhVI+rElxbVQ8sMUu36pE92/AN1VBPfabaFhCUXOavwgueQ2q/tcezStWdSlwqwru/g==,iv:NbsXnzIRbce2tYF+D+HQMBH4BPDeIk8SrMPcvFyi2gk=,tag:n1q3r646o8lb8BVUqT/sYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:oj10GgO2v8W4N6m5BPPDyqzpYF7D25W2sXKZmN7Yg530PPDZtByHA8LumxeEwfS+osjr2mELLkAU8UQApwLvWtoIohb6qZFo/TuO3x5okZivz77nIfzMFX/VDxImSbPyDu9WC37KiGxWUFHsZ5UeCBfBIylI7b/d8/9hB/RwGhC+5+9QLpwuXkx2z9kk/zFkaXCDO3srUftz3M9qWrQtTb1lwD9upwNV+EH+,iv:Ozl9NoBNqFqa3MgOmAYHUyZOTNpNoYZBL2OeSI5znF0=,tag:cfVrUrGVAJOQeRPKB8rXVw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYkhlaUZiTmU4OWI2dC80
            TDRRS1A5YVhucHkwZXpUZVpVQy9uTGV0NjFjCitoRHRwSDVXVHpoOGtZemV6SXdF
            RXJ4ZkRZbkowMTAwSGt5MkVLU2tRVDgKLS0tIFdCMUovemlzSUpIWTBhWHZnVktU
            Z0FXb3JRRVdXT2xwYlliUXBiWkxOOTgKAp4VAGDtLsG2DMdM/KC2hlUHOW4qLERO
            CYGlJsybTMJ+PEhXS9EH9lj2UCctVfBOHz/HP0pXU9gxmCNoWe3JVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T00:01:23Z"
    mac: ENC[AES256_GCM,data:uqdnIfi7FT2tc1I0kCYy6e5rPoN2xBJDwAbserwqBQ5yoQGcAYtY+t3/VHlBVsy0xaL3gO/mgxLJ5gkeqEXZRIDu886fhDsJ1ZtE1PTdhD1cH+4oSo+9JqHMQGaTSiYneAmoMhiEL45pqKR19XlLTcpUY6ViaVL5hu+L49bcjLw=,iv:N569GjYW9JjXhz8ZFlrHdc1Ot5PhMrbVWfXypBlwvEA=,tag:4gzx2jBgrik1agJ9OlvdAw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
