apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jc2YRrlZuFo1Eqxp3E/OARY+/DFOtSsVqbfhFKBW3w+BAyArEdF8Wgch5CN8O+yiw00J5Tn6ZK47KYkab+zvx4tV6GRsi8bt7X7fatR/q5mlfLaQo6aS0oVd9i9bo5T4cnCW9rkbE3UlASXeXKhVQn75c8FssGsFFJCIlKWSroByRk3i27gCSqhLeX+pE2VvirHGUf1bfuamNJBLNJaoeRrlCjAXLZagmqeo9TjH32OXSPHTWciyEUs7mLugWcK0vyQZnBQspKW8Kdojieie9tEjl6qLcpJ5s83teSwfn2HchI6WNxxaAc7he5T12VUBaOQJv2xvxFo6BuN2GHLDeHadS1SG/QulmePqlkryJL12Tubh3lXY60mnaFnoQf49,iv:O8bHFkt6GYKHWzl4zJtF0Tg/kvWR58IyP1YtbOPyroE=,tag:o8wzFfuQ8wi6ZggEM5bAeQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:kfQGbcQOQ9kKBJYXmOg17NE0iAKTQp7GFCYv37uiSmIrqfvi2Qb/uLJUmxcfYbfAT3VyHCTfeIUnKu5gmfYqI7KX69RVHyeaFYiWiuXF1t54+DrN9VQlDLiL/mI5fqtqXsaQMBGIqpksWEWvuBZkhOz77lhWRYCkqJyM3ENHVkrJ59ZDcIic/c1WJG+RaFo6+5ILnaZ+VGqhCxbYro4OwWLIQvDUrYn051aOqaCp/mmRr13KiNjff9UiY/nMGreMrOiuy3EWERwkoqgzPA==,iv:DRSp3a99KzG3+piumQCSieebTOfJbvsNIGBOCJw8AqY=,tag:iEcD7uzjKnob3jfok3To+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:2+iqfDtU1DItQifkGW1qZeN2JMDvCtpY7RA8br+xJqw8LDKwj7HwY6/SZGIe+h44yPsjgAMpUx+x8XHbQLQMmdaS1Jo1NAib8qf2wlo8+pGF0e5DYfKhbdAIrpgKmnxC6TUaJnAzpNYb7yySP4gVog36RWsLql+y0xVYnmVTlCYhLg+Xy2ss2B09FF/CHN3DX4uPNmrsIsCtrl5QRO9JV4ac+nFlyaISrqFc,iv:lXuDS76QGv38fi2L4NxoO0oWus/VH98dkwmCxSl/HCg=,tag:1I3suV0RAQBOMPB3f3F4jQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjgyM3l6enJHdDdPU1Bn
            WUhlbEhTaE5CK1FpZU41MUJxc2lRQ0x5eWhvClVtZHJZc2dFQkMyVWxiaUxWd3Uz
            ZUpUK2NDZ29VTGMydGE0RkozRVRMRG8KLS0tIGJpb3IrTGh6TWYyNGsrbG41eVl2
            TzFjZTVIZWFud3FQc1pZZFlNQVFDeXcKEtm7IOGyEyLwmHtj8mvfT01u40XLeRys
            pVZQuQ9aKDPiRLwRR+wy/iH5mur5NHrxoKOIuCMzyoezaBtZdfBobQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T00:23:59Z"
    mac: ENC[AES256_GCM,data:Z8x9qkm+bHKVnDiBWm8QqvTF+PDjCX6rHl9M+AXHW68bj8Z0ujKerlynW0ZpVIXfZOR2bte5m83RUBdg3bGMtoLRBM2AMZ53C++SQnbK/ZfRCI6erMM0CwEVQ4KF7dS4YTNSWGb52Q502IEq82RiilD/6ewZRYSSn9a6ZO9zCLc=,iv:cclbpx2gWlECK1fUef1VqplankwC2kdU/7DJ+6/5xb8=,tag:PH+ovR4bJct0L9JsbBMpkw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
