apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZcfiF9Efj+tpLZ2is0SoygSQ2Zq63RIlRvaL6jti+gj7eJ8Q3IZKxNs+2R4kr7XV353vzKtT6uLLBciVm4KzoN3d7LPqhgwSaFpJ/1ftj5KCTMkWpr8SsWZZIYpwoYx+1pU8Ks3d1v4GaxcbiJ89vhwGwWlBUb7AeWEFsp7AgkJJU1/yUNcO0M6c4ocfJwWm7ztM28VWYH9b916a99lgOtKjzl+o6/81dJOfcVPGtkPKwSusexeEiQr3hDpf0UKHduLUUge5CJDDPnMyTpt/irq2NI2Vc9BFi5M2UU44XnCe63r3H/Lk5mgzms7MVb5rSgYqA09GkK3N+pvp7AdtJX3LNKMQqfn1pqF/1exp7kg+V98wXJx/b3KalfI30qq3,iv:F+0mG87RXNIoPvhy7qyTQz4ekNlnH4EJkQ1Rv0I5jF0=,tag:E3pWbFjVzkjRvApqGYH/dg==,type:str]
    identity.pub: ENC[AES256_GCM,data:uGgAezeyF6VZLrkigq13o7T7szZGT5enxKUi91TegxXZYKNxmLAR57NQwxn2AgbLtdLyLB/dsn37uC9yQ/leKWlQBA1eZ54kxdy/qmiv251u2pOsez4h+RbYMVad6Q/uuVOGVglXm/5Q61gYdpyM4WYRh524fm0nbNxAPoz0rOd7TuJb2NLaFtZIrue94XmCeFbVBAszcN7jT0tVTpollCQLuDb1V8jOhE9zVkbAMgNUO1m6SkhfMTOEQ+UUps5QmFDbUJcAXsWalytX0Q==,iv:GFgnCJ1E+B7Np8ySYhPW7IhhOuAKtwAiLcEw6zRl3FQ=,tag:VIHzkv74xk6RlRRx/8N2+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:po7tdprDUG9iqVhSaDi/ge7Z7jgjjW86PHFDz9LtmPAgzAIyNzw4xMTDVSixPs6P6OTLjE/B64ngAurh3u+Wn2NQNetvBexMUvYrIPg7s/spGGUCeshj4XFSXsqxcW8INILnH/0ef1zfvLAUHxobqswrL369ayRnTDg/eIzjBVdPL1LSp1Pp2pSJlqLJlN2LL4Wqwkzmi/ph4BFdMW5c3PZAW15Dn/er4epS,iv:sve+dpV2KZvEoGUrrPs4ZxeTilMqqZ6HaDu0poZxiTE=,tag:HKHjFCrrk9qr3Phs2EH34Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcDdqRGdtc2NWYzZRbEFx
            WUs2UGZWUjVhd3BGRGZlNFZ6eU5rMm9MUXo0ClZsenRFRGQ5cGNQR3ZEYjNNVitP
            YjBXMkJmaWMxV21kaFJPVHd6ZjI3eTgKLS0tIDBNUkZpc1FYN2hpek4ybkMveWxY
            TWViYkg0MHMvL2lNcS9kMGlMNlNWRW8Kt+9TH3rBeb2D4apIFFlUDSmb14UFKt3L
            rdT5TlzfVqCqUN5qMB4UMVSjopeN1a02mZI2qG1mHyjEvWMT3CAxlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T00:03:03Z"
    mac: ENC[AES256_GCM,data:FpbE5hKBbjqxnT9qkNwC0KmXjz8SNAfrIikJQAzz9mim6uyRHPHi6TRGoVHuuAYjlQ5d+i+vdP6dDfi7F762bWOgXecd8YJOV5WeCXQ/XiJaybx8iZfgKEqo8sgA4c4LCvL+kCsLlj9dI41gijoMEmxA1AB/qh9oBbvonaiasZE=,iv:faXcwAepqjvtDxax3k++JMurIMXrA2iv4jGZxopqCqY=,tag:8a1L9mEdBNDizk/veUquNA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
