apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KtJUbRczRwMSYtCcva6iATbESUcpBztqroAYwyGKrzyxXVIG4l7Lm0XAIdH4c/rQtBtAD1zU3EpR/XkyYdHbm6V+I4XHvwyNWG0vXLegZZHyMIQ5Yn+q1S3LqIoswmPrh4OY1JNyKP9EiHH3YkDhqw14loljhguP/xQB4ITqnWcIpSNmp3xLQB64sixskxJ28zteiFioBfWrXgdAL/8WEfRksxKSL3ddjjm+XeTRNJVXquV58w/Ti9H8bU3cQaV5SZjVj8RXfnGwTk9dyEvLRVPv6QqLjsE8RyGFcGaGet+E00nG7IOO0rooUzh8r3A7cScQNSkcm2Ka701EZCw1Ck2boWou+TQsfoNqhL9vHMGaCKoaJQ6c9kbhk5Z06Qwv,iv:WfluUzwUQ1iTQh+CZO/qSnqhkkX66NrcdJ1TOwXpnjA=,tag:a8k16avda/Mtk0/kXVBGRQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Et1h2OEa5atq7GAIBTz0FiaKFBIVqv//DMlxoXI0ETICYDrbINKZUJybhrieCo4vizTe/w4eWpCBSM8OMLMKOFxwYfuDNW1oPJFFGgi+//2QAUN6XyUNNY4VmExz3E1aFDF6nxwm775SxbQ9ZC/AUBdVgUu0sG1lUv71vKTJV7/chqNx+JqZHu+L4qQscZTQmM4yNpxFGt7eAoapA1eO7q6CEOwbplDoxWZJk/jG8v747Jk73ASQBWdOzqQLY8EdCnHHiINR3nAmbX8qJg==,iv:u6FuM3IECDVVrqIS5JdKAo326zcD7DjPt+NTddoc0wc=,tag:VcyLO3ef8n6z8nUvSzPrZg==,type:str]
    known_hosts: ENC[AES256_GCM,data:AP1P+9ZRi2j8Ivn/aTVlxtY9J5zjHwT6wPsNteXUNRXQFjN1aofRSmA1oPtAdGHMee0imtM9+Z7UunmrMjJBGgYACFYFwjw/s93TBVC+Y9/YcDp0ie9n9pfVLioyOYPaB0IyJmjOUl9n6a9gCkbsQmq/KLuhxeifuht62pmMV+7yk6eLkyGpn+dj46t2T4YtRaveMdTqzVifkGKxSK/zQiYx0uQi05Zsvbqe,iv:EJI5rTXdLAu7EsmoAypm3hxj1SkMpjfcSunGCcV6sTc=,tag:LRhg6UvS4YpryRAMyQ3sbQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSml1KzlGbUZ5RXNxMzJr
            d0o5MUNvTEVCdjVkYmxFeWxTcS8veHBEdjE0Cjc0NkU1Rmo0bUEvQko0N24rSTdU
            WWg2alVmZjBsUFg1bkZ1Mm9MdmlqaGcKLS0tIEdXdXUwWWZkQ2ZabERRUXhxYzhU
            bGFVNVozMDhIVzFlLzNNSHlkNnBuR0UK5MrFMuQ9nSBEdoG7MQIhTgnlqyn2kbnM
            7Jd1YfY8upwBewQSRaxRBbec+0PmX+7FXH5t7hEcfMwlSdNF5V9+fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:58:08Z"
    mac: ENC[AES256_GCM,data:llwPjq4w8QlPfG5EXQy1p7UL/7FDnTgP9HJoGYSGrRqFhzyffFvsIKLB44B7DMipUaN7V0nhHAQAxFuG9Ak/q9rGYTvRr76orxfgaY8cuXsT/B6wgXMQDy2txnfvFPNCrld72GjWgX3QfWhdslTW87J00yq/aAMK9h3GgEvUfS4=,iv:CX2GxVhWIM1RKtrKvMBqOukrMwZg0AI3GOzbvxSosEQ=,tag:CwLcOCYDGWqDqBeGLon+Lw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
