apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kclcCXtr+FVuCgEhD6+YtAMIXKUhkIjXdnSEoIBEvwDvEuyWiFZWdK9rT5wQmFZK7h4maIsdbwcPjmJkaut/17KxTFBKxy+nSI3zSJS9UK58t4c0HjaNEoFAdPsUjpSN3sFYv2fm4jhUGozl7NOdRqROG04LmVdw6kBFk7orbR4Wp2XUAC4i5HsVGKrEWLVcxP4suNYsHfg6AUB+/PqiOVZ9hN9PRug2gafaQAxwe7tRJrH0u/7MHtrQl6qdiEqhVrSAcnPRRXNroYXI5g3t8t7Xc5WZ4c6q9M5elpvqvL9lTIfWIkFuGG1SZ7v8egiV2DEdvRCYufUVsQrh050PEUgcovoEZeV5I7O4iUpRGTKgMYKF2yy3kLZ9RsxQDRBx,iv:cmVw3ijTKvb3OX7pSNFNce4WxpfyINcPZCrjEwf5vzI=,tag:Qm2mN7BQrdbz6ThEDx5HvQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:7m/I92MSyduNJfOUjDuWcfK905s4Q1BX8SQHe6OlyWYdv6bfumNksNtDrW8Kg0YZfGPvlbEvMN69arsI87ZR9EN8vXHa0mwaomOajPhKboAqkMedTO8rT17hPJZAkv201n89a/0rpcnIivBflBbL9vus1aWK38W5sRafsrJyQvsAtyhoC99nUGbIhJXGI4QlJVFMe0iyzK7DCVbzusdfMOHOxNAJ38X7sPQRGWN1ZvTAQNUeQMdKFD6YZRLfWj936M2Gq/IrbP5A6qw4RA==,iv:CyKKhNkN/OBzervrqnml2dqDya+JDx8rcMiFaq9Oz8Q=,tag:Hopa1dAKht0Uj2zFlaUpEg==,type:str]
    known_hosts: ENC[AES256_GCM,data:RLsBA51DfxP3RUsbT1zcOAiTMHzE+tVOR44QoqzHjZaYw3732E0C7H5e4uKSgTFkEqDzUjJn/y2A/p+2lIoZhUNQdX9D6hRXOPLipRKFXzgxsz2sLiYUwoMSYK4glE4QkEOWZrQS6V5o/xbS/3RcGoadpIOGsFjh8+y8/mOi8ZnOxISHA2GTtsUmrvsOSXOvwTWsE8tAxPE37LgK3iWBad+ySv0l3EKN3nXh,iv:9qI/qX5wBP/4MDCOjr3fcq4mDkz4dyFO3wCAciIufhY=,tag:Rl0Fq/Ua5IDfpL8lWCdYuA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVDBNR2ZuczA3TE1YV2R4
            RUh5d2JZbGx5a2UyUFdxTFpYT243ck9nbEQ4CjI4d3ZtVit2cG5hc2c3T0hmNlhz
            Si93YWtTdUxraGJQZDhaR3c0QXJRbXMKLS0tIGZ3anlzdHgxWjhxQUlaZDg2eVJs
            ZG5LNE0rdUY0WTFLK2dtdGFuSy9PNU0K0Ml39+BmrDe4pnsLz+6e1+rznkFHWBBx
            5/VIjJ/1RMIZpn7WW6yE/RQRzJ++eM/TotzsO3vOIMn5tQoHRnkC0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:27:38Z"
    mac: ENC[AES256_GCM,data:9wqKcH5pDyX9sY7wZrdMopUPonM4vtmxI+aY0mftViTPpwLceDQR3glPKG7nM/KcIeJJIpShG6fM2QsahvpJCxeXT4l5YozxKxY5N9mFjGC9pGUzfKn/kJOiGf9URL+D/lBCCdQe0o00Jp/qOWazbB1m/9HelKFdzmRSMCCEGgQ=,iv:4GUxk2bAA+jk7Gq9hH4f87Wv5WQgvGApdJqG+/Wz6cE=,tag:HUhM8q21GmieSpXXi6oQbw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
