apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2v4Jcf0Ef/KhDgaKwDX7b+QghsUL0WcGbLcHOk/jgiWGz/tJ6wCwn5uAvHCaAQiWiJXWGdOBlbUloZwTotg1lbTdZ4ImGyZpaMQnr2VpnLQDKxpUVczuYEnMVHcoV3IBZsdvN0XJmQSNxqTSTLoTWYMTlQSgzPnuB8QUyIIJcOk9RT6yw/IQBGocyJRt5XPostgmZ9ax0BL0joxsZg8N/wMZxJtdEC83bd6ZINPzl5rRKvr7LvGFyBjV5xViApyLFNrXvPV0g9Vjcr+vv5rQuAHEbovK/JGNAxE5E4BmXnpDZSvDQuD9o5W4rAM7wmLGwjxEzCoy01t+CGknmsQ6+Lp77kwbGD8nDxSe3ftfyxq+QpctMNl8lH2ZHGTvsE5d,iv:xhri7Mf9Vqhob5DXH9+KOPlzWkJOWMUXQAhWb3V1T08=,tag:GXdN7ZVLl+bZqJ8+HBwjAw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ktXqwHCdYaLtcZocdo+JFFX9QCjAJSKdQqPEe6UGSsxAInGBeU98BRWMH7/j0Y4z8P8sx0TMK5Vo8NPI8bgLxRdO7+nFWtpeVrWU6hLiFrUBSZDfNRIi1M1oMPrOZNp8ALh+6crjC6lA+OgebRiUCchDCbaza6mwuaGmAomc5vFz1/h6AH75/rHDstTZVVYWxgtZNIqHQLXgDLlexzAMVMF1HkyJgPCoRliF/ViDuNc5vbWXLt9YeLzUwtjmXLrEQ7S7CvC1tDOxvCPUMQ==,iv:l//IB1cPa7aIZ+0s/p5Z61GpPQPEE0rHhMP+JWGG850=,tag:Gjvs1saAmhIOGJv7MPvDlg==,type:str]
    known_hosts: ENC[AES256_GCM,data:6Mi5BHnlSmC38th4AMpt/Lr3hjUCsBSg3R6CjBYYPXXNxrgaw3zOcWTnpL1MKi8bMiQ9uaeiQfZYfQwUCMvJT1/TJUAtASlpMlMLh7E+sOmuUSRaUzyCIm4afSQ070ftZcK9sJx7Lg3yLM5tAu+iTTLYxx1r/WZ4PrF7zEJPJ3M8bZSTPYpET1sogDOTTDg7JVxJCPqKNDXexSgPa7bj7G0jAsuVZGi1+p0X,iv:6ItUG7WvOLpjJ+KbiXY5CPsiJYvFTV5yQh90bd89ViU=,tag:5f7YZnIoG2wTQ5O6Wz7nMA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWpZMHRIREJiYjhidlB5
            T3VKekJ6bjhiUWdpck5Dbm1BSFhXTGtmLzB3ClVvTVNoTmtxQWNFNU1CYXpkTnpR
            OUZWcDFnRS9kS24wa244N2R5R09SSTQKLS0tIE82THZ1a0w3ZGZXZTc3Y2hHVlJy
            K2trVlNmWmFLMU03OXlXMlNVMWd1U0UKyStGzv3OaK1hnOquW/duPKXi+XInk9BG
            dVsPoyNjiGtPQSf2QZOgY2Yi5TOZCsWuxSlzNUq4gIGuzHZPwSQX3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:43:10Z"
    mac: ENC[AES256_GCM,data:nMarysif0QrvBrB8DueP7DPH+E3kJtp/7qMXXXL/dcNVNkjwa0YMQam66OO5QwLXDjwTFJZ5/gob9jx6hcDZwYdnV4159sTbWb8JV8Ky5qFCYOP+Rj4YC5kXa0zIS4CxYlGhBfq3W/9GKTg3pndrCCTZ1VrdK2vbqqFPUls+P2s=,iv:g9T+IYaOBqIbgdwcR//elFHpwECt6CX9zW03UwIwd/U=,tag:tbzhcXIiCBaz1kg2/qm0JQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
