apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZyhzZ1cN747irpIesLm9IuHDq5ki3eeX/Y4S2mibHV+GbEPMmnHHx8greRfGfsG7dw52FQZuz5CIv6hO2MXFEq9e3zhfNIDjW2FO3Y8X1KkmyHTBDfA0NEQEO1TR5nt++4jHE/K2xr0m3ZSMP2bezfnBkPWmCD3P7rnitHckQuZOn/ge4QjhYS3SOcNTjOmB9wRt+KscbHtrsl4ZKG9qxMIBaMrtZdQM/5Plz3F5bd3tkzhFxHKkSdkXO7AHCBeHk0zYHcRUyWigoDA7fyrrF/fcYk1oZoj9NCXNoZ4NEcjmmRqqhgeqVUXoULyESk+Ecbg6Z2bQEoJxdX0HHiDIzv9uuBkDe+ZUCkZHfgfGXcLu1fWaGaH2l23vTNboZHwq,iv:l/6aiwvkKnKPAurDYXRuQEJovwEkV+3mQdNSlpk4H1g=,tag:Ic8VxFJUq9vZav6PAGRUng==,type:str]
    identity.pub: ENC[AES256_GCM,data:17VM5RRknJRg8hHeMyn9RApSZNlzXZusem6ai6NvGsgZL0fWeXbna0UXctxAIyrVludjqY8J+JISu79qgT08OCiJDRtErtliCMC4qcaKCvtjVj1SkIWF0HJwl9mVqCT25VrLAKeFQtGiJO1Gp0hdVZ4k8iMnJriMWhr2Mf073ySAsZpJHMFDG6a4d/777FLg+Xy/MW20DjerKPlrzG3GZH6wKsY9BOW8GVBSg4nRun7KcBITQGEIYj1XnlAamtzgrn24jCRXvQHjHduAuw==,iv:7EqjoS7WKa9wcC7iFGxzSl78WOHyXMoZHR4y5B3eO7E=,tag:Rggt0gv6VRi6MLLWWztyWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:zIvr5rFysu1P+iKDi7i9U7To2Oknmjww4jfqq7idK2k/jMA53zKloWNuIfTExFY2W4PS8qOXvEhPeTYH2PWHjwtuYgS404pwSEpXTjXZ/e1Dbry3t6I4J5WGN8kheBs/pGoBtu5npOYw1VESYx6DPhZHtrYDRqGH3WQsTvXc0QH7OBVJsyf27Jgk0L0AcYjJvEhcuLGUgcPOhYlAsU8wvUkNsMIVEfFMzDkf,iv:YnqQnjc6+oeVDDASOTyM9Os2eBp1drrIVvMiW0jP54A=,tag:2K4BKMGfM9o9YiQx0mko0g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTlVmUEtWcFZVM25ZN2NN
            dElSeW5xUjlidUs0YzMzcXp3ajZFZmVwK2tVCndrRG5LeldUU0V4bUNvZXRJWnAy
            RzJWaUcybkxYZ204bDJZb1Vzc3pUTHMKLS0tIHVUMWxSNjYxbmlBUmJ4R28yR2pk
            UGtWRU1nWTNnbFFBd3l3TmhsRXlGQm8KO2X1sSujsH2Sy2Ai8k17ROb0RXgDE9nB
            eKsgIGbO8m7UG+hdtIgmokkL9ZeLxJlDurq9zttClBXp6WZ3E1EvOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T09:25:19Z"
    mac: ENC[AES256_GCM,data:Jvo32HDUkJ8MfQD2lNzkERa37zgmm40NzpSTGRYi0Ugi2hkZOz95fVsuKsriiih1UFoB1GaeXrqxyxJmQC4vOXsZc4iLVOEeJZzmfvHI6lXYS10Zj//8fFZSRu6RbzzIHArRD9H6KG+mwxpAhX3y8E5I0k2FWaH5zQzIapASNFI=,iv:Mpb0+i8NagMitV0UH1WPAA5IyG01xm9e6YHeSyWmCgA=,tag:0oWbb9aBMYLfwfCkUHefuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
