apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZRJq/IPDb4pV0vW7nBWlfP4Sds4wl4n0DtMkF1TEGuWUdiC4PxkhyCJzL8za4TPg7k0iKu+hQgYyduJ5OyTBmq1FsOAKZPgflxvJwFc26Kk4suhomcyYfx3fc+1QhS/7UmfSKfcHdXMYKNUb7zrk8sxbj1bOCBr13WMqBhged3mi20KeWk7Ss6e6ClSzVOUFqowaJ2tBeaQmcqdjEQW274kp+866A7OsX+0YO2+SjR8UcmJgbiyiiL7VYEh3pvdMV3nVCDlCorotSGx/qV2ARlh4Jg4+aN8e8yr/z1ncA5Hzd0HonhCy8yYfjH5r0hiDMmSkcPacCTufTkBkMfgveRpVpdb+8V5PAsmnCRheDf2PHxZuFm05USGgvwqcpJqF,iv:/jenNps1u+VJCDw9wkzsWNDoQOVYjhvG6nf8wGnDsg4=,tag:RuKczzFx6/FoKKeHSOhwgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:MYpzKJz8kZNZqCsYqYslgNoNM1hs8FLKIZDhJlOMr9udG2EGD5ElEw8UxbtD8iqannJ3oR5gVMstiCDsdPqEszB/xN513MftZuea83cJhaXiWIAmr3rZ/9ZRsUWzrMO1Tfj7Us9AfndB4zk2im/DWEVzGiQ749vGhaDgfox9gGKnBCuSfM8QqexvaAvXq+NjTfmELj9UBZiiRaO2u8thgQrSfJY1VTKldrQrckqLVE7SxmBMefqOye05EzD1R+nAHAuPBR+4gzmlAA0ZgQ==,iv:gnmFLGu7TgOyOaZfksg65hlF930aojp3/EFR/z5aXDo=,tag:uzIG8rrTRpj8vLdW4JlkCA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8EYp6HLhX3dMICWm1UuL2h/LJ+e0skijGN4eGwAbeN64bVFC6wdVJBJ0hRJMqm8b+pRYtGRAdh/OYP/Y+s0AxzXBZ1gLWRZ5m1ijBbKJG2N5kQonW+OVRXLtLbaAt0uTk/won7J0GrBvNV1hO/QLqcfwi9LMIfxRjZXGTUD73vhc7j6qL/hUuvYT8F0qmHbfAIKmSsOHYMo45paKZGSkB39Z0PDws00yUQn8,iv:aHFotO/7iyZqythKBJ+f67ReDHd28RbXMDYM+c7iyt0=,tag:M38zhKPFU1cskoAg3WM2Ww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNDZYcGg1NnZGbUdtNlAw
            SmdLb09aRHQ5ZU95VDQ2Q1Zwb3FyV2ptT2dvCldDbWMzd0JSWG5taHpvM2Jjd2Ry
            OXQ3TERiMkVPdEx6YnQ5eSswNElpbVUKLS0tIEViejhwVG1xY0YxbFYrMFpVRVNU
            a1d0R1F3N2o2N2lHQWxPOXZvRnZ4LzgK2ICX5Xo5COmNP8x7DVCe6i3FVlhhK4cT
            l+Ulis1wIOJ9eK7gXHZG79VRWUN0KVfATqnFT/3oiVGW4lqB5Qk0nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:21:42Z"
    mac: ENC[AES256_GCM,data:2roO355gmEHKwuHpv73cOGnI6vMA55T4Sw+OQLlvbTJb7jO2Bc2+17fA6bXkeqhlR1DLXgeb/W3MlbVa3gbFtomAd10HDQkkNsWrwh3flzCYgtc5SMeZIBWgLn7e+cuBN/OIn27+F51VheckgVyacLZYitUg/dmmxm/9Cu6Ivws=,iv:0pi+EfK85Qdo1el7XEfCcqNAqd8mrYKHEk6Ghxlzzko=,tag:b8fLnZSjT33FjNAJ2XGrtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
