apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fnyeixBsCH9fiYNdcoUwf+c9ChM24yaU5uFsy2LkSZZvNaw5fgileiyH1wbv1PNmdqGaNg/gQGWcYX+iKeVG+Vlldyn0uXTJFRpqeKfHIADZxexm3X5au4WCdsyNVLJUri6MGwadACeSLSELe02fUvE8TJZtKWQEqVQ8DQXdpcrLkR3mn+rEj3Sgx31XSnRdaF7ffB67bq/RRKYfM0UJYo6ATqoG3EAo0sONCQzgAEl1fPGy7LLIp/TBR1SvzeDvVenZnnu+3Lx/CzsN5jOTkC1WdnSQ+wQeK634netsBNTo6xzw4dESdW9GrhnV3nZkMfgVMgEYC7Q2sZayi0Rz9CrZJhsSPkcstWIUnWCNvUEuiekI87YhotceGD7u38t7,iv:AnwDe9YsspNnPdM/mfjotrVFKs//YwpXcpQZ2TKOmbI=,tag:Sg2c8jKzkuBnhHNLXZFLzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:tgVG9LJ4W+FExkvmoR9fvrzV7JVLrb4JYytsLweaREEsqJLEP+fZ2Fbwka01P1RPjHC+mJHcNXU1oOhFQ4ugW/AQOVYskz5/pVCKB+mytnE+jfrM/wc4IAV5RwugK3z1qhtyI4fYKdrAv5BmUfqS2jdhML7Qt7fUszehfPldW6EhwtHVCImMu/c/gXhGFK0x76oyCa3B1/iDyBT9X21otwtm5JawhxByblXHeuRS6+A5x4nyusr/ur1t+GxiwAsd6JGVvayzysZ+n5IM6A==,iv:eC5OGNtNVezR0VLlRvOPdkhcz906SeCSsLoIYV++AUU=,tag:xkfNNX8jUz6HtWsXKqs1yg==,type:str]
    known_hosts: ENC[AES256_GCM,data:MRYRmyYJIIL9Otcr71+9Smfptmcy62xoyIIiYDlMp1xrI2bHit2zVPIGS+HqcQC8jtEmru/E5eEbBBQA9uu8tOq84DhCocTKxuU6nA1QboWaNp5RyCJC5UzDQo0MEyZkfAPdpRepGOAb+044pqZJH4tp3Ez8NFEnrzwtj7PJTs5ZbZJJqQ9kag6F/EcXcOn4n0dpF6RhIyVKP8TSDX/b6FCj2fNGqAZhelVU,iv:tkCHso3RaECiLO9EZSDAQPo8K9tn9bfSDpgU6lxVlpY=,tag:do8bWttuEjyDP21t2bFOsA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxa2FFOUdIbUxYSTBFQUtV
            ZUI3QkNTT1BCNXgrbk1wb0lwZkowS1oxdldRCmhkcEEwN0pJZkxlbnJDTk1SdGdD
            MXRHM1ZYYVNJdGMyK0dXOEUwdVp5bEUKLS0tIHVZMGdldndHbU9aQWlaOXlkcVk3
            QmQ3TC9QVEZZdm9lR0lNem5NOUpOUDQK3yGppyr1F1w6XUmH6Q+6OnKreiu71kt7
            fARr/yTcc5CLgyw4ECGwY7+O0njEOTQztPny4ZCC5G4muF+c2bdoig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T01:12:48Z"
    mac: ENC[AES256_GCM,data:jOcQDgRJYg+QRmwY3vw/adz7lWbSM6/0PEFya0RHFtkG7dBx5AGOCf5f5LbqCSIVwgjL/DyvO81tLoF4egz4w9J8IwqBJakR7GMz8owhm8R/GRENZ3GDT5qLfsKyDjqatjqgequHP3Wpv3AtauvKM9dhyufKPGm1gRq2VZhI/yk=,iv:7fiWetWpvPvK1lc2oWupzwmfcuyWGUxdrCYiJHM9d3o=,tag:mUN7z5x+MPY8MirXmOKc4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
