apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Vs9pciKAO4R92N7IzIR6KvyG0ZEJncjAiCHF3wU3dXNq/xpuXp4QyK2XKEooUVlKMWnurcHVcIr13bvV+joy2+XNTQ29aAfKeP4BD7AaJa6RhMZ8IDAQjqPArwti4QViqfn6xgHp8dS8DyvFLqrGwNGbe/WXh7mRNLP7Kj7wdCQcM8hi3KNWO8/RzMLyXO1UH0gvUMZcZul8N01yFhQwdahn60NRXVvP+D7GHMy8yCEXobn7FAsRBmzOFKZgf42KRAALLUtZYOnZ0N5ClkRCAOPZLcY8inOtK+pCWsE7rAwk19kS9rUKvJxmnInabUG1wC8qO80zrmvga7wXQNCnvwz0entS+5MisKTQ6njdAGIF+eLfOmQirRdaeAS/T2kV,iv:+q9165pvl8nbwfCAuUUHJXKR1RWNgT84NSP3/0bbmoU=,tag:BVUNhuyNAXe/CRlodL9qrA==,type:str]
    identity.pub: ENC[AES256_GCM,data:GMQIJWLCqbqlNZaeM56d67aCb7ChNlEIX1wLAOQTHIErOW4AgJbTsYEiWz+FKPjttiYECD2zdKYSSA7UkfhhLITI0JeKND3j/qNGiZ27PvOTSpInUj5UpGqVKWsNJicNx/9Hhq6ci0eS8qxJE++UAnQMhblSTGei8Eg/63OhHncsoXoizMv0MJLlW/Kbxuji5I9/AkpPE4wB1nubyFZtZZHZaXghcNJ+pz3APCdxMTKWffQTq1fTPUKx1qfQebTrebdh8u9JZEX3vhQQ/Q==,iv:iJrTFwbtQhSDpRdEQFljwh5K+cip1g4VxoAWT3jIY8Y=,tag:2dhxXbB0CHu03KB2G9+reQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:E1sDjH65X8mmtD/NmskxBs+NBsklB4w3TBSsXQKo/gMRU4In1m/me4WrWPAx1mwDvBKFvMgtimx1M/GebPfbPrTQy+Au7H/x3pWhC8cJZzn45efL/Nk/WA8g0GHHwl+0ZX9Us/3Er3fwooUC8qbOvDkmqFiYgqRlpBq/guz1R0pFYW/nUtWovAYGA9CugZozhjDy4ebXTJ0dow33OmcWx6ceO54bWUcMQdUq,iv:9w3RxpngAK10zX8uDJphZulZUZPzAEIx4hJT75Z6KVw=,tag:lArbKPI1ZwLnxhbQrdXTkw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMEdBZllqRGlwYjFVRUM2
            Y2JSQzBXUUVjWHVES1dKR1FvLzc0aUtoZ1M0CjdxQ2tVNWlsUnV5MENWWXBBaFRQ
            L1QzRml0TmVPNTJOYm9WM2JUajZvVlkKLS0tIG42RDVFK0IyOVVMVWM1ZS9zcGtO
            bEg0d0R6OU80WU5TRmhDSDFnTm13QXcKLmC8Ojw2sCuN4iRYvX/p9Ohft6T/AlGL
            UbCEghxeTmQiRnlKs2U0pFKzJmXasHdzvDZ5SqT0cYPz37USwIUrdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:28:21Z"
    mac: ENC[AES256_GCM,data:TKvLXW30ZGNmrSuCcHM93qsh8fTVyKQJOSlEBSCS/RPMMZsw/OKadg6U17pNtNxv71XhOUyFBGxi0TU2x46P1dovit5vfs1jj10i5CVAyiYEEnwTfkPTTjzymgAe7ppoW9BdyYi4Th/JAzeoHWvDpPlPOsPP7IL878qYntXXu4c=,iv:JyUjI9lVfeX/PWfs7Jsg0WYExwY7hAZHGvbHpRBmODY=,tag:7n4KrBbG/s9q/TxAnsHuEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
