apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VSpEJGFqjr08an4nz6s6WEe9zh++ECuOul2MgoX55lYSeQhIbNO0e41JSFH7HtLtjxeSOdG9iY3m5ciWLIpUUqhEiHSzSXoJRX+upxQ2xaS9h0lIznKUaRIE0q8e+hFgrJRSCGV25AXlHi+wp6p2PVZ2Fe05lxl8YpY6KpHIrwCn75Ca/jWa/fS9+Ai2fAKQAB6emJH+kbmF3E8BBKHunMeZEvPX9m4+PTGjFxgEtPQszVGQtm8ZFq6uSmnGhZanx4Q/aqMQaI/Z6+mIfpCAp3DSeTgZcZksaN2iD3eONBpo3U2CAnozSC7RcMqL9kdbx+HeUPXBFa65rgQLeMJZeW3IjKqjn84+2+2DUQCZGoyD/GHh/2Unh1/UiuM3od+h,iv:SQ4wNj1bitEjWffwSA//f1p1QRTOPYO96EyxKzghlgM=,tag:2wY6bKfEuWftP1C50yxh3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:uY3F2m5zDo0kf4Dlmyl5jS/v49Adflm0bMMKl7uIpssDgfoE1Xc5kyuUUk1GCQZdQyhX5orwGj/UwyIOE097bv81fbPxQk1SFbyV1yszzcI82Ge/bvVqO948OOzZDetXB4cNmn0Ge7McM13ja9ft9Tb81T/gGo8bG2jtLQ1vb3VUEmF8mRlWc0hG3warqEuKpD50cdb6LOtaW/D2F6MfAQJ1XiPqt1Q+SOJhJEgCvvvI1sC+MEKsV2ax+/ViP8nX/femF7LgUALO5Ds1Ig==,iv:Wr4R4b+sfqPZiAXcM7onpBQfVQOEAo44uj1fofIssy0=,tag:rCmHEiayxTAsKmguVWz+zQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:IbceT9k903m9leQO1Qky4iKWj/WuDURLzkty/ed2ucmto3N/qokQ+qqJPy+SKobYwqT2B7ApmvPY8f6iAsWrmo2sWVxRxRpDtavYN7IHJy6iN+PeXFj4JfdBzhV0Q7jZRywAe8jQi6addcuBE3hNr+Sh0OOGhkQowJZD6y1YRtwFmZUeEifDJaMGKRXNucMMnFSieC0QHL3fgdGPfCAfKI5pj7r8D6IDi7bj,iv:6TX6ZZTjqL/u/TblQd9pFc3YpkdhA+7Es/nVuopF4yQ=,tag:IjunDQjCqA/eqIvXJbx0zQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa1JDcnJldTRuNE02MEN4
            b2ZIMFFpU2hDL3Y0ck5aS3BpVkFFRjR2R0hRCjQxcGpBb2RUb2VXUFRwa2s0SEE5
            MWtyVEsrVTg3cnFuMVpZZFB2ZXhJWmsKLS0tIGlTYTdaL2RqQUFkODN1T0E3ajUv
            cG15ZmxEYUJLSjBUSlZIWlI2VDJCdDQKwcEB4vAILtOpBkv8Le+Om+DUv88O0g7J
            Ab7AN9m3DZMzyTy+mSD939349rAanAYxBLk5cZ7ufctpBNv9jS72Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:44:57Z"
    mac: ENC[AES256_GCM,data:U070U21yD4cohPZW6eB5qBWM7NjOfzCkEVYEEl29vc43TDf3x+qJgXBMhWtCFTkji6nGDCs+dyb07c+/eI7ZMp4FkyAiUxmuH2g+BX1gbPjIEWV9oL0Ss3tBhfwQfLOUJt/p049rNres16s6gGSkSXmoeUwWl+meWSy0b/kN0PQ=,iv:9OFC3xR/ZH2Z6iNEy+Bhu0n5d6uMeg8K+IlLLaxzf0Q=,tag:k++SzVAKsBLdRU2V0MTx3Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
