apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Mx5sop3SVv20+NNJk5CI58C8tWFH2kJdwGsjPbwbvtYEwIyT3gb9EgF32E5hbGIOZk+lbjPg5oZNd3kMFjIoZmSjInqzpuwpXNy0cOGvRddTLJE5nq4oshmH4tyN6jravO6YNnfV8GHD2DTec2AOVFVHjKP4qN7aR3L6scvlnoLce6YybNnEgI7eixsu+ErJODwoVxTfPz/x+ADk2wS0uB/aYmvuM3uUH4KZewgN+PEoOiMUJa5UxCOH6/voljUJEe4cAkp/PHsBuRGi3TKZi1RS5CY72kCHKs4OQfkv3OSFpJDZMJxPLKuCpJghYIHqRr058/J3/2kcbMiNe4JNMevo9qTGnxn4OBGOO3fNpNgvIlrjAzldl36r0ko9kYW5,iv:SSUzFoM4O8L8eaXdHaU9EVE0GpwVd88tw/9zktxaI9M=,tag:Qb/JLC1G3jitFzzfSx8LXA==,type:str]
    identity.pub: ENC[AES256_GCM,data:sOaxx5CKHWDCpeLi0aQPFDroJsjq57bQaLFxg6QlFatvlniIUqiSMkbH/MhMsZyAPMeib8+fMPJFjXzlD6VCEsavvyldm66TJAbHc7QaDABFmxvlCI5DvSeo0Hj3hDATMoWYYlolbJT25cmgmlhUwl9Db20IcHfUmuKjlp9ZjPl4J2TSiZeICcYycVx3M8phChOa46KUVlCvT+GjsW2v9hcwCHpQDXi8kPBrWd3HiUkwbh5xbZY0nMCEWc5Upa79WPfJhsMccfZHCaWlxQ==,iv:xY/a+SPcia7YBKzB6xzCJyDk3aR+f+MGH0NKaH6nTSA=,tag:J716gdo/7n37CnT5nAjkLg==,type:str]
    known_hosts: ENC[AES256_GCM,data:2mkYBU3o6Tlu/NkNNC7dENl4Vr8brPXZpfwomaHF1DklwQTcNZc7Zws2Z4Lyb+epI30ZFY6NjllndNwHnWrpuFpviWly4Lm7caTEmWGtBgA3qumpnrBRwx1l4up0U6ktheDkoiGBRG0nScpoTw6Lw56YqsGOJR3rQM+RUvt3o5OPgiTVSKWFT47wqpl7Boub9/IZA0VAvHxYxmfiElPADZML3+5j3nnP/xeU,iv:515lAWeN0O9fWmq4FzMf7l8w59/IPLdpCKUN5ynkadA=,tag:hWw1tkDzt03bYooZBv0tlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZmw5WXNDcVAweEJEdDhC
            WGJodkYwZE9VT0VwUXNISHlTWkpQQUxCaWx3ClM4TVVmQStmQ3lSVGo2TVZ5S0RI
            UGpnNTZYREhUMWRXc2R6aHFaQitMaE0KLS0tIFYxNUVTdUlZQXY4TzNpZUwxektk
            RUw3MENuNjZFeXRkRXA1bUM0Tm1FUkEKYfMrVR18Ryja9soFDts44zt63u+je8iO
            07QVw0YdtgSPPqNHua6fmvKjr9syNhTZNeRPEQjJvTN6245b1b/E1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:14:03Z"
    mac: ENC[AES256_GCM,data:KdGAGkCKxj6hzRiKR/vkKU8X+f3ETZQPcJAhb9SJJXgMWBhRZxDcvwC7dP4gA4bG+Xd9hPFXkuwrI2GW2pqpVoVPmHoPwdVqudFII8z0Q906zVSw/KiaYCe5CDGgcA1dA+aL/gjzhGdLRGPz7HiJtbi1kcCUWd2dbRBCJVM9ZZ0=,iv:YQTow7nx4dnY8mDiq5uszzIIP0IypEyCM7tBm/BsnlE=,tag:qfkg57qrpDymtzD+AYQPrA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
