apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Aeug0w75yPCmt1stf5Y357E5cYExKAYsaciP6mqqyP6skYNXPclcVOl28nNqOJgx3ulUrkO6qjMYaTEx2FEAw8I0egzk4Eo7QnYfnLXlYhmJZnpjBugKh8jn8cUEYrJUpGGXPv8A9dMj75ATFpooxIQVz95RmRRdWb+ZeR8z57zBuykeVtSHhg24LZZSjI7aG9LKGklj8afkUuGPvaO95rNAgriUoSx46uL9C5trB0qXbt7LC0qPgO7tldIV8sldtxlDkoAeF/P7Zfh54wpgmkANvnO4ZbplU6KWsxszlNjcLkvWwqL8LSzlDOlsndOtPHCjWV+GHZ2u4wyyKtKWDON4KEBSGDT9XQ570WN7t0+YNDSiuCXgo29/0VzZB8WQ,iv:UEWONKfXcDyi+YD/KMtqARwhrNi45SjzOYj15JsiF2U=,tag:6zZu3l1HCxdd6Wg3hsh4cw==,type:str]
    identity.pub: ENC[AES256_GCM,data:itbZU+QxGk6k9d/zImcrFu8gR79LDBx+DUCUivcMs2CVTRMkzLuczDQoA2yD9WPpNudB4BfKozZNDHeQwG1yiqUZiqojmN7jotK42ahqxQXPhNXQnsgSIEIPTzZnD0GjSFCY9kr/LDU4boc/VIY5ivd9bWcAixnyBRxArF3iLXUgUoIGlfp1Bg5N+SrpPwNbVVskKNLxd4P4YMjMo7ijQ2R+RdmIPiOWzlAf2wZdOIOiArTqyHLfAKJN03Y2DZ0AGGyfQ1gCv4kX7PI7qA==,iv:0CnHoPIpQkkHxt2zKKE3SfRdNAYpNKmp3lrSR/Wi5ks=,tag:R9C/TBXChh9HaK6LPf9Hrw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ggjGUdedgDj7g2ONyMTPT01Oh/vFNbFvd832yRUNu0E5FxebRyM2CO+KDlhbUM0f6s1QLaut4Tg+d6Qdl2z7e1xGPxXZD3mOxFAUPwtD4p7u3Ltn4MbsWEOjsY6KNd8szfrHD7YV34iiaeMt3PTwITUaOswhl7unU2lANp7+kMB0HPaLM2Mi23tlXbkGz0ThAT7EDeU4nHL7cBI8stdNxkjGQECbYfQCv5Os,iv:IX7mOV6nYwnGRzHwbtUEB/GjDwogpsbvsV2AtsrINaM=,tag:lP1mSa/NvFetwN6r8Nlfng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGV6VjlMRDhOSElKTWFn
            YmNkTUxuOHBWd2VKOGdzWVIyU05ETTVLMUQ4CnJqR083SEFIYWNzRlVwL002aW05
            clFIZ2tsRXhQY3J6QUh1M0dIaldiNmsKLS0tIFlGdXhqM21YZmducnpDdXRMRXlC
            REs5VlRiTUluREo0YU9JVjVnMUtPMFEKi4PFb+XVNgbn4OcjLYaDMp8PvjpiBIue
            ryoukYeuRgZRJdV2Y1rV7SNk5YfZ3hiF5+IiGU4Bw3lB7RDkocWmKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T00:18:21Z"
    mac: ENC[AES256_GCM,data:T3IGYGnIA7MGPLaGlyA5eubbX+s+b8deexXBHhd6X62RJGKnWStjKtLmgh8T/vw13gDJExGHi0K3sPZImePWDLRGM1bdddzDihB2smSvRvbu2Glsi8QQPlfPnEIfWGhzLKCOK9A1YkDFuqWhX0qW6mhdM3EUXexo3q3FDNfU6Ps=,iv:Pg+eCWkdfYYqoNUyJoeKXu4R1cRpXSYwkLrX71blaFk=,tag:msrV4+nOUsaLJgrSX1Xztg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
