apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SgPVus9mIquUPTofsc/uRgLIWYakK2hvgWUsPQzPU4FcpQbNmtSCGQ8ypg+pIjNORHbmYPs2qooaydsZsL4bufy2ScDBxfosi9MOw9SWM+QncZ7eXrpvZVgpMoVGczyXhFx0PwWlhvy6HcOA2sdSoqBr7kH1eM865FSgaKe1meAm9lXsSTr3EGWWIIPbn46BENhMFVlpAX3QmpQ5ia/U4pwwB4V0SMcNITsfv/ddtfY5qJhGDEuHuUWHPLFOsPBFkwNsDYtJeHuRrQwciRo4Js1xUbwVbGFbUBbtTVB657wtJgxMw87EvCRXiYKh/93aVZC3FDismvbew0ZZy4y0stol9ifBO2kk0AR3yxKU2UlxVwYf/lK8xEX2rVG6fDK1,iv:C8SQw4tXIo/0Zhl71oN/1roWLhqqLWEwHICVWwfEsTw=,tag:AAae76XJ+verduWpvLWoHQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:/hVFABVwgKZij27O8/BVX6utkurXLt0NCM0bdMb6QsqBAb0E44QmyfprXwoeiTyKJdmueBvcvc5AHYLZDqrhtw3pAdJwwjXpLe377/eV8MAmTy8N24Dqu+lX9udDtH+cyxv6F4GtOZPyyBtmTloI5oxFE8N9SC6ib4n4WKEtsZuliIm7bf0Yc7DDg95blbS0Qk6RZDoJxEqw3eRtczipn0BLw6gIob9ap+k/8RmizcdYm5XzVw+j4H41pawAjGVZX5oq7bFvmadIw7eIJQ==,iv:SjouOxYTbMIDVtRG7l06yMx7/7ZBor3Ti1KoKFPMBsU=,tag:IGELecsqKQmBMKMCzjzT9w==,type:str]
    known_hosts: ENC[AES256_GCM,data:iKFmQv0qq1GUepAjS/SfBoH+hiFPUPOl5XoVZ1GAtIZ8PkFRHVoQOCG7R4mLwchQLiIsXt/Fpk7bt0+33121ElS3/131PdU7xNb3yoQgrNfrmYXYFSUu2VxIIMYCo8DkYw7SE0Eg6HI46ruvtA0O/L3TsHtmsvh6uW1kDPjxr0A8F9JcEM2I1NkrN+Pf3ykmg94KmEfYPckhNOKmfsF6MxsD2R0T03vjfYTV,iv:zgPE7PNYc0CrE4RZnpxO7l5wnTfzKJov/VU3RQwOt70=,tag:95OjzWkorifLZ3hrt7Xyfg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMXp6NW02clYzYzgyYjdy
            Z1Q2azRNeVlabjIzVWp3Nmt2Q1BSTEEzNVh3Ckw0MGl5N1gvRjU2Sm5objA3Y0RZ
            cFhRNTdWL3ErYmhWZXR0RlpyQWhLL0UKLS0tIE9oUk5kcXhBL1ltb3djNEVDTll3
            T2hCdEpZU0FBVHhqK1FYcTQ5VC9obzgKeqrofwP6JkPA/0WhCcDZYE5FphnI1mFb
            Dz2LiS57A4Lu6660iVeObV1erJnzXIWHNakstaETVu1BbEWauOktwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:30:07Z"
    mac: ENC[AES256_GCM,data:Ipg2UhUfylBOSyvDhhXom3ufJyr/3CF51i000yA6h4kqAanBdK1TErMxmfDnTbJ+qkHN862KORfcDtpBh+8/6jypJct+yQhT98SUhid83oIRRCFKzAvH4tuZCaAY5X+sCayibrJx15GYfUCyqS9QUJgg9bHvtu8P6VuzXZJXmeE=,iv:lCOW1nCM2/qsu7nHaT0JoOAOjMC6nL9PzY3A/StOYoo=,tag:jFseGXeQnLSCo5nvbwZNjA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
