apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SgGTWXhoCk+uu96p6qMlvP4qypjxpxuHQlTB0v7eDUd/l9e41wcgM6qHdsic5QhARYcUOhnvdgBWO0Skkupc8b5IZEIA0v3c3O9PmrWqWj1CKklp3BSm7oMV+LCYywCkiTJ/8DMWTwYlOEZhK3sjCiiq317b3mW24VNJX1uu48tCX7pi0Np0TlFxKh/I6miv7UP5I/ZgPFoNp+MigWIUQfqZBgIl55ON+Hs4BNhHgWfUKj4stSMCtAVk/zHOvLVaHYJ2lu9tjFrIs2YdQ5TLv+6wOKdu1ARfRTbbcWJMLC0WQvVh1keQM1veAxamYyRBuNpQG14azOhwbeaBO5rIWZhvryg9Lumqwi58cT1oMBOroc3U1ZTR4Wn9zaEVaiQT,iv:Ro+RSRPZZTHkA0eWzdPwUEtXeGH5/rCvr4aZ4NaPk9g=,tag:Pd/JtNHbDvbM095VIX+mwQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:RwQw0j3xag/utmoFb0/5rmhom0afNJ3+9ZUmFB3FAPBWAkU8wiIB9Ne27sgPUiJ2qolCMgA8HdtcIrgqFAGu18mc0FOqv3Z2/uMiRanAy5dFD2kzj9iVMppA6r+vQBnMhr5vrWNBjordS5m5DRthRA2EKJX7S7Ul2L9Jwbkaz+0cuutM1EgwEIQ90M7MGgFaxvQxi8Y1qPAWojW7c3dcamNKtJWAcmjaOF/0hoCj+MaJYLYZqiea9OVJVmYqH450prcn7rOpPYvxjTYuBQ==,iv:s7KgQ0gKo5mk+nGGsQ9+PDq68HmFLDESwkKJHaCnAao=,tag:RKY0Xn167QMHgswtUCdxag==,type:str]
    known_hosts: ENC[AES256_GCM,data:W8+k3tJtfuP2dPVVBLyAp5COMiBtVs1XanNdi2bmeGo9nmJrEWWD9snYbKY4dI0GEBBbeosGNw/kDFVJWv0Ct1XWlW4i+j1fwaofQJXdEISawMjGneUPRHI2tD4elAbnitnIAyNT4+znUnj5Jr7dr+bQ+sQc1vzUacXGcN45/6Ue+nQFIdDKIVEzx+aZlGFemrxVEazpLkN3cEqN+fvN1tARi38/ZuPcETw9,iv:9CWrbbFQ+FxdLjAbhBJUGYPnnIDiX1YoX/5SgXKL1kE=,tag:z79r1NsHpM3x6WZJIhB1yQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWE1S1d2N3ZSMmc4RG1N
            T3R1V1JtVkZBZ1FxV0Y4dCtMOFB2Y1VDdmdVCkViNFA0VVRHMEE2NmtlZUZuM1pJ
            QWN6R3pNVzZycm1Yc1VGaSs0LzZzS0UKLS0tIDQrQ09YQWtrTHRONnpqU3F0MmM2
            b3FNTzlsZjZQUTNmTGZGVDdoNmxFTkEKswBb2bDRnl1NGTCI9JbwL2JtTcg1Q+mg
            ihAOAWQnEAcTYOx+gJpGWnZp4BnuB25KgSPB6S6A0fDogYIErRig4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T23:41:10Z"
    mac: ENC[AES256_GCM,data:B3/kNFxLNDNNss77gj5tbTC5aPwHgGGydDVc1qZPBvI6Ko9XLmbdooJYn9fNqsA5xTfx4v6tkCYSE+Zmd3nEA/qEMWHDc+qrRVEy0kyNUTrwj3qeLL5IRfHX0gr0zY8b1gSIx6ufHyP76U4kTmU1i1V8BNLPIfXK3qQGNwMRr6c=,iv:FHZ9SkXzm8NGXRKS7a438EddCTputTbY27OOXhF7ZW8=,tag:6J9tK4BFwwjdMzFt5kvGpQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
