apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mXS0hUtqaprZuU+VJh/VenLj02iElRElJhQQd+wytRhwzwvZEky/HqESFkzjCaqEDY4MVLW0IYHLI+3WF4RcKh0mILTDbQs2bxfYsg61V1OmdyeX3dj/oMchrqG7tbS/I8m41Rm/feiT1TmQu4lewfkxJU3MymMUYTHgWMWrEeJzl18pAZB9l44vg8xqcO2f0OUPoInX3DOyHKTiYt9oBNDaAbwtX2kqqqrXXzKzrCNvcTVcxEBfXkJsddpdrryD0Sxcjnmexo7add1iKJVBS2B3/x5FefC/mdOP3F3w3DtNKDVMVf6M9+/YsOliEA3ztvG3NeuQXRA5TqPYxlKZXW8+VxvbJHQLzZ+3KPOuIqst1qmKRjDu1MIN1dl9cdWN,iv:lBpyatqfcBb6ybddAKFsiOr187IqvljD7PSOQqQ0GUc=,tag:vAUq5+KIAphZeyYLTvPL5Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:2avCx4X7/GlLt3juHkI5yhFefdY3tq7jXgAsgYk36PwXSn8ePQykLSWDaM2XiuDw7Iyn3olDc53ZhisMXBm31nkIMqLH9AMmKJbhoCPipBGzsmiWxUKy35YBP7VG//ixOpml9WG7dNoOFkTmMg2mx9o3FBDHoA/n2CrDxMZc43GvBrObkA5nLvi0aCPFxdq171M78J79koaSCIRTo8h38C5HWdVmdmGHcjLZAC9WwogwVfjBZUKbug/niv5rAeLTjA3wYi5Yo3ZkWQpqdg==,iv:Flsln0KR/zaVI8FY1pOOGGkrGdCYAZeabg8PsEEA1WQ=,tag:DJ+ngLHsjab2iQoWjtrz+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:kLzctckCq+eTrXkCHuq6/srfbBkOIRnsHGyyXpu+XYt+T/tbL4oRXJhrPQMXmnK4ole1DraBIZ75BseBg04vDMiIEk0skyn9RtX2OG972GA6ju2Wt2dqhmLg4RRCNcEsmqhZH4Sb0XmFb4CUVASEMIw7IP5jGNx6+q0oVFy7dpp2dgliOCjhha31BeXXA+9DD1iDaeNSqeC2BC0dtUzDNBlv4ABEVnMUI8W1,iv:gBmRdOXVvsbF5NYOWvzSb682YIIk1J/HMQ3AcgQsW4E=,tag:ofu2U6ARnyr1tt9AKszzjw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZktHTjZaZWVXem9Tdm1Y
            cDFGQUlDcm50cVZVWlBLdTFpWWlQL2M1QlJRCmNRM2RYbEtmRWhjemthV0I3TUFa
            cERYYlMrQ2tiWS9JT2krMUt2VnpXS1kKLS0tIHZ1OFRpQUJxTFdURlUyWjZpNVF3
            aXBxUVlydzFjS2NZcytHSkgvNVNHVDgKb/iz3hoOlVuqifR2LJZ6uBPkJm2/7sbi
            UBhT8gIblKIa6UQDRYRP46l021anPAfXq6IKmUznWHDa+lpWzb8vvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:51:42Z"
    mac: ENC[AES256_GCM,data:ZmJmu/GfH8MtNYIxMMELykTxuBs7mT+Nr9x6gF3G9rrdg+EAHFfzvMx5xeuqAVxQxurg0xXwTt51pImLT0BNbCVLfhOHWcaKQY1grbQmeLqccls8HVxePprj5XcCNca3to1Fmtl7/LAhGjnrTjyxKPVJrrZEmXznp5Z4siXbHPs=,iv:HMH3vYI308tb3ZY4X0Ba3QjqCiYweTlN6e29KW0X92I=,tag:WOr2WZyZg6mH8W5m5He3EQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
