apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:o2rLnPI4FxVDUEqechAtPIb1XfAN26+U2waIFXcCnr5renbIVpA1kZcvBrQL/ObNEnYKVdw98Cjl+MTPxdmtg2534BjxY4gm+TOpsdlAiZuCBYX6GCFMMlqwb0w7BVL4ekmeMfSLLOt+cE3qQObGqeOJfQXfv4krvEAnmegWU2cTAu/Ff/wkO2FWY50I5sJAlW/LqeAp7fs0CvTJ7jvEn9W3tCDMQI5BLq6XmenRMzrf2cg4UwiAzLrqU9RZ999mSpWeSEO5yzFMjnMXIV5FbBacZzlAcA9FnpsFpLjRCmPDJKVD0P8iIp/joz0XYmdt0yOQWqLPtSnTUltj+IPzVmtsEpATEmMS/K8zhHV7gCXYRPGauGC0tqQ+SsnSF8MR,iv:VDT/DImpl23uUSiTltkQdSv4TiNOQNU9PsHeSadnQi0=,tag:Ul296LcJW7oTMEQ4zJQf7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:b694KbnUXNlmshPT7mc3Hat769XPoPK9a93Wetnur2BaGX6NFuGP+fMY/DpFW5JD4LtqQ3jS4pi0FfGsSxJ1VCot3vAvRPszofnG2Ie6ctLddJ/jJc+rpLJbof3IXO5CXoBGTm27mS+UVx0TPSb6GoaE2RiHjT8L1CVJTKdY8A+33UX95S7AD6pwdK3ne4j6k98V6aa9bF4zRznD+oHfVv56p0Du1/bCZbRJAuF1DzrvK9p1r7gx0hcptND8VzTe9Ak5JxXOS9NVqBOiXA==,iv:vy8KAIf9HxRFozOwupmhCGW8MWrTcckdT7wM45N95Xk=,tag:UtlpL6jVS7XMQV5FbxBimA==,type:str]
    known_hosts: ENC[AES256_GCM,data:UCQqOrKZ6ukR91QpXnEJzIprFXacivKAX/GkWQzvg1RNlX3+U55mcMlHuYYBsP5FlqY6vCxi5CaVqor/qodXY+/hbUfl4egfp3nTBiRvDyrsD8me5qQqowM3ki9bxez6J/bPLe5wzkQQ6pbnmIzrWpMqnv/PkRKhS/Ogy/fdY/gwJXYE/4qj5hX+Le5O+51Vdo5hzSTRzixBOAUGV9mTfIYPNznPJ59OQp3i,iv:twLxuIEWpT4kNp+VUJGI1VWXQNqAH/e7DB8WCdFC7j0=,tag:1e/qFNIbtrNhaHi0gG9nTw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdFhpaG5FNlBXY0ZRa0dH
            dGY2VjkyYll0dzVmSFBhd21ySXBDbjVjWkVNCnhnRWluQ2Zxd2xEWWkvaTFGQW1I
            Qy9rTUt2c2lQZ0ppMXoxSGxYeThPVFEKLS0tIG1PSm9vd21vQ2xuRWs5ZFgvOXEz
            WjFFdkdoRjVybjFReWZFTFdkN05CNDQKCF66PB+0lVF6IYs8YAlVwZU6UMa3r6jJ
            2nBE3riQZCJiYGYQ1b8MGcHAxfzcC114iwH9Vp2QiMBDktAABYHWzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T12:58:56Z"
    mac: ENC[AES256_GCM,data:786qViD0hQv5m/5ZJW7twcquN+MAWxyCv3hveQoYVB+HV66RGLAplVJSBiqwOuTPjOez5iWNxii6nrEpy7bNQYprfQgJe2J5Hp+4dqhpBbzxEv0WliG7dUkFEnWfnrHzzEH5RZDjm1FxY7ynyNUzqWZd0nFfpBOWW2VwtZxbApY=,iv:kM3vDqYocjy+G/n2wwrxo8oIReY0dWmre/3SVwPxf1M=,tag:RrMUoZ0YIInndNQuyDz2mQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
