apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KBNma/3rm9BO68RKXzJGafOkDNaGYz2qWjJFOvbXKnuingfH9t0VKlEgemASCuLwxOcwUOYQIpgYMm1gOYxZWTjeakU767wotZUZSlpISLTXYdmwVeyS1v4536zAOzSu6/yQoaPv6jn5ZFM6EMuO8GFrvB9qe0B9ZkkP/nQKpfoR9Oj4GlLF7Ti4iU9475ByGs46UUQTuPmtKJhbORiRa6cbngp4YtSXm/vWeD0gLPLHgtNKaRwvxqAHjeXejKZD2gc7Kp8f3Olupg1F3AIzUauDvCjy2DYD8L4J20oW6HjICPeYRHRyS6e/+hQteFUZtc/l7pcNHcLV7VQyQS0VE/5NAimAECV1HH4mbg58pv/kpECxG/tK3L5FQuEzp0so,iv:WR8CfoXGuOcM+OY+fJT8mh0YtEZT+MQDv77VSLUw1+Q=,tag:mxOInJyv9dFQ4lQyBttASw==,type:str]
    identity.pub: ENC[AES256_GCM,data:tm3ER8TR+UB0gQPEtEpy2vUWPqDaL1iW0JgZw1mg17VgI9+MrGQuEYFK1gl63Kvqj16le5O9IH1dfq9uX4kGMmn2bcP25VM4EQUiA8Qa7wxffeFUGn8Zge8DgsPFZgXomEqBaQN4zgjyQADjKFL9gY+F4EkcZuTphwYKMHqlvR6bbH68fYEVSj+MJgOEcKm2iklZKPPQl7c3SrxlcqXN5N6NWda1D4F+qmGCtBXTy45APR6cyvw/avSuLkitQdonNMlBNsQfO4f5kFlizg==,iv:Gz0I6o8LcmQFgy5vawQANgz6tRMu/M6cuA3xnsuALaA=,tag:/4JS2G9wdclEyCMByT3hqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:gKRff0qhv1siC9r40X3exIi/qF2RIn+jXWZHzQyuiih5DiLtueT3uKr7xbUAZW7r88U/6j1xIWCcJ3876IpFq2Kcgp1v+4UAn4/AqByioJDlLRUDUVMaC192i+EnXh8w/E929MpxUhOs8Uykj0mDjF5EKI1gXogXfgwMTZ6asgRe94ylff1C26XE2Uq4KJq08V8rMyIhfDsASk0Lzg1q1hix8tCTs8W4Vpcn,iv:LlLGLHREUUVkI8AEXdMwFpxhWOjZuqEwb0Okwo4C1VA=,tag:mCEP176SgxaIlvkAx2bMBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a2lzRVZZMSttbDg0TkNJ
            OUZqVkNvTnlKOThEMzN3TUQwc0NFUmtoMlVRCmVFNFVNMERpQjBCVHVFQm90N0hF
            R3ErTWFyTjQ5ZGhMbWtPV1lXV3hQR28KLS0tIFBCMDgxWFpCZG9qZXZQc01jZWl1
            aXBZNU9EMG5tZmN6dmxJOEJhbXZhZUEKbB/QXEAAUY6gRn1NDckefCc9Di6gEuGf
            kA93oyMCIigS3z/Xoz1P3yR5mvni5+sgpWYYtfxUYQ9xCeaG/CajIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T05:22:34Z"
    mac: ENC[AES256_GCM,data:1SBtv826czdnyns7gaEYinCUaFwfxTox8C6ADo9ImfW7cZ+Puh+mB01vg+ow4oZlPEIXfX2VCpv81cWfEIfAgyS33QaHKrIXpmzI7BGnjH+PDKw9TZBCJFA3WNlHMd+NkMNEKwDClVG9lC1H+tNpGSz12fvOAZZbIkfB1oBXzzY=,iv:x6s5f8BR0Zuvnfe5DsktE3C9kcitufPSfPf9gfMv4bw=,tag:zooSasnYG+mPQYrD/JveXQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
