apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ny8JWeTmudi5SO9ceHxem85/Ox+ZitRGwRq0UtfhFPyYc91PcakRyDQnljY5K+SgEuBGk9gPmy/IUmSgr79EBi1Qi+iSXzan0Cn+ZH57Ux6+WNIAlaT04NE94gI4u2yJn3AGTWPH4xXv2DsgKO4JdlFsp/WUzSCVpvKCcd34FQ85ENxFOq/OSzEuslyyC37llSCOMOXq2jc+V15r66N10Ht8ETMqfo04npglqHrjfHoXNxKhR1TR3ZGX5dbZPgqCt5fe9gt+BEOtxEf49JDQijqpW941gzwzWy1WhmdWKAZmozc6XFLC76BdfJo+QP7EAxJsdRtOkfvcngcvc+ugySqReuLSxiv+coA9/5ja/OlI/P+oIPJn+QBTa0AaEFx0,iv:S9WtSI1kuYEu8IVYONU7XTVlODEMX7qJ+skLncWk1SQ=,tag:EOJUh+oSA9DmTUqZ82Kx/w==,type:str]
    identity.pub: ENC[AES256_GCM,data:jaYmytgcSOfvBGP+1W6poxXhedlt9CVU7uRzTpdDdv0MUaEyY/QJIF1C53iYLgrcJX9Ls4c5IITF3V4wTU2cu/uwq8RA/88oPWE/mvN/9GvOS1NOx/NlZsFt6siOJyzMbH1Ctn/Q1axnNLO55qhvwxev0lcbZowpbbxtifs8MP1ECkN/cDwzxGm8RE4ub/Y/Wba/5BZgyp18JeC/zxYamNdMet3iyObpMoSpDMYcJTQPUNv8EwNf0A5I7lSNk2IO8PtKFwhlJwPZ2Gou5w==,iv:BZcqqH/UmsetgCui/v/iHDxZU7GsRoA9AX2D94RZOss=,tag:iYxGPo5BbR725Gvdjppw9w==,type:str]
    known_hosts: ENC[AES256_GCM,data:66/nO6qru8J4MwEpEpkW+cq4heP7WSrEgC+7yyhQXxQDvNsnzYo4NZNhvMOMKCl9jG0Y6TmuIBlYz1aso+STbuVGL7uGu+Ebx++OysILKRUEsvCUA75FoFJlvv2v3dfKMwRVl5eLU3UhaFWb81J5oObsV5woZd5PItDsfhO5rSql0t/P60gJrIG6Lf7impagFRt4H3l+xXPvxQG6MAJdyMHZDp47/+CWposp,iv:jtr+YUUNMQyaS1jQR+QK6eDfsi1zC4fe9aQChU77OIU=,tag:dwtM2E6SdYKDTAi8Bj5/JA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaazhHNllaVjhyV1cvSGdm
            ZXVZY09QM3QrTkY2OHZlc05zcG9BRFFRZERjCldiS3kvY2wyR2YzSE1TdUV1OUY3
            TXNjbi82RVEyYU9oUEoyaitNUnhTbjQKLS0tIFNRWExDVllqOTdUZGJtaW5NQnBH
            cGJBQkZsNFhXK2FkQWxxMG1hVXdQS2cKXlcIrpQeKyPUKZrSzT47OxYCDsSxwUFd
            raoCFYjPwC6uufu00X+K/ZGu+sjvR3/fop60gmgAMwLWHAb0wGCZzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:29:41Z"
    mac: ENC[AES256_GCM,data:ip/00dxMiNpYiJ5sd8cVOLdVkzqQ2F27ZuX34S4Mk+YfvFZ/VXlfLLSZ8VrJE7ah3GHnS349rQY+zGnfaDJsv2/8zIi8jgNEgrnCmG2DjrOvHAKclEAHlbELR82Beo2Alj8Kn7fN7Z9yvocfmcXvwcVj6RJ2fTszaRoYBwQPKmU=,iv:zPC+kNyKgB+R283w/9jlZG2tlbYfLVUPYRutynXs4JE=,tag:ytob9HeiyEWmYYF58OP+kA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
