apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HDPZAb+kyjFhJnZ5WW6X5zt+al/asBIPSD3Aropn33VJigHD/khHuWOZVr+gqiHmIUbiiJ4SvqtTqgZS0Aw/rRC/AIt951EOGDzw3Q3IUm+sfwa4oMTtSPHWuW4o+z2PwyPhu1JNApvihc7FrDIp2tIWA/s7PmaP2azswOBT41qxKfu0Ul6cmWKgXzWYwcqDpBPzNDo7elGlgtZeHnwX8QeA4tDNcM2p6Ee7YmtQ7uyVtv21W0Vo7y6LJwegjZXe7NxNriFdJDt80trl15sLzhWucBWtWUWMhrF5sANsFeK8tM16spqHiVuHIwyDeq5lUBgCJrpEPXb0QYG3dwws07WkpsqKl5OHXaArETGcgnQ95R8Jo56tj3KIqbJ9L+6H,iv:grBrQotXPzmHSs+k7HZqTVr0yy28hky+URjGZiZP0Ts=,tag:C5ZsF+i93wdkIPC+WJHp9g==,type:str]
    identity.pub: ENC[AES256_GCM,data:lllasq0j//nfsNIvkZ9TaDsiuZDf0w/rG6n4+dSZFygKQ6a1UwqinhivvYCWuZy2mHbMyvvqxuAVD9iZqwSQlZjDw44KdG5QZPssMRIBqq2DRUoDVhRL0Cps7VcPvb71z52c+fX0dKYQx7WB+Yh5vgdmf03q6uRW59wy+oGKdCcxW/lbbvLk6//Lae3XvhxWO1jVWoRF9IEOd85nNSym6fGjvby4dFlEaJ64fo22zrcAejvN+u31tdkC6+lA+P9gIYTAaXe98BpmC4iAVg==,iv:Y4uZHIlyTgmrh5PiCWmpaGC6hb+qyIZP4VdluOpVfLY=,tag:J9sozLbx2q+AE72wLAJqfQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:UueqxlsByZREZTwV2dMvyG81DK71Ts3MCGsDDU7Jip7F+kFnNGFEI8I7M5SJ4CvaoGu5kDHZ/rk2Ycjxi0R6szau7qRS19np1vtpQIPGkOl3O2hHuw0FHkh1d7l2UeK0coGzRkQ19Y5gwLh2mlmY/A0weMtBTALzch3IJL0YhfEazPvHZ8+Z/0oohnlvJAAgdgbmLguPgSYIjWZQb+dQ2B+drE30DoU4Gz/v,iv:h+LXvQ2T91UtyMPTHvXd8K2iAmxchoJPwEbugcBopeI=,tag:0Vkk12g1ST6JDDTF+0pS1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k5uw4306gahsg2a57y845fypz2yedlepk75r6dp96dhv8w59z3vqrvl895
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTUgyRjI3cHNyNVdvbUhH
            NjNBL2VrL3pEallLR1dLREVkU3RMaDRRM1UwClBlZDgyZXRZUGFhekV4bzA5QStC
            VGhUOGhySjJVOFJMS3VMdXZ4MTRVRlUKLS0tICtPN3R6NkVzQmJHNjkwS1VwSkZx
            djdodDhtRExmV3EzZGk2SHZiaGVzVDQKuwheCfQdHYVxDSejbtVrUE9RCrFQtYf8
            3m2Kx01E3vXfHY7Ra2J0hl2aizsjiXvknMMkPNMF7k2EIGjk0InzeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T17:40:39Z"
    mac: ENC[AES256_GCM,data:CMAblTILkJCS+Z75wBH5JLB8aQF3+0gWqTRTVr8gFKLx0PAsCsQPcHooks0u5xqOc2aqqIl5HtD9ef6iDIpdsfcbxD4mjHGcNH8pK5gvYGtwGzYtnq6pqevY1socZEienhcpccwM4pn52okn4L3oKoe0etWncKaOZjC6EIYBnEg=,iv:MgPkNhrBF60o9mYtnY1FM97pRYR66ZcZumoHP0eG2nc=,tag:q6q31SwuQm6uJXRn2XQvNA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
