apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ext-truenas
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/external-services/ext-truenas/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

